### ISSUE TITLE
Use a google sheet to the team page instead of JSON file 

### ISSUE THREAD

**Issue by gajindubandara** [sef-global/sef-site#1001]
**Is your feature request related to a problem? Please describe.**
Currently, the team page is using a JSON file (assets/content/json/team.json) to import data. It's more efficient to use a google sheet to update the data than using a JSON file.

**Describe the solution you'd like**
1. Instead of using the JSON file, create a new google sheet and add the data into the sheet
2. Create a google script to export the data as a URL
3. Use the URL to import data from the sheet to the web page

**Comment by miniskynet** [comment]
@gajindubandara Hello, I would like to work on this, but I'm afraid I have not done anything like this before. Would you please be able to give me guidance regarding this? 
Thank you :)

**Comment by janethavi** [comment]
I assigned the issue to you @miniskynet. You can get help from @gajindubandara or from the SEF community.

**Comment by gajindubandara** [comment]
> @gajindubandara Hello, I would like to work on this, but I'm afraid I have not done anything like this before. Would you please be able to give me guidance regarding this?
> Thank you :)

Sure!

**Comment by miniskynet** [comment]
Thank you @janethavi 
@gajindubandara can you tell me how I can get started?

**Comment by gajindubandara** [comment]
First add the data on the assets/content/json/team.json to a google sheet after that you can start writing the script

**Comment by gajindubandara** [comment]
> Thank you @janethavi
> @gajindubandara can you tell me how I can get started?

First, add the data on the assets/content/json/team.json to a google sheet after that you can start writing the script

**Comment by gajindubandara** [comment]
@miniskynet  This is the script I used for the Onelive page. Get an idea from this

![Screenshot from 2021-07-09 16-18-14](https://user-images.githubusercontent.com/63200586/125067147-7f180780-e0d1-11eb-9bc0-fe9d819a6648.png)

**Comment by miniskynet** [comment]
@gajindubandara do I need to make the google sheet with the SEF account?

**Comment by gajindubandara** [comment]
> @gajindubandara do I need to make the google sheet with the SEF account?

No, just create it with your account. After finishing the task transfer the ownership to the SEF account

**Comment by miniskynet** [comment]
Hey @gajindubandara I have a few questions.
Is this format okay? 
![image](https://user-images.githubusercontent.com/49517852/125195375-ed480000-e272-11eb-9071-65f414f1f1d5.png)
Should I make different sheets for different sections? (like advisory panel, external collaborators,  executive committee, etc. ) , or put them all in the same sheet? 
![image](https://user-images.githubusercontent.com/49517852/125195349-d30e2200-e272-11eb-8505-2b8ffcb029cb.png)
What should be filled for image and LinkedIn account columns?

**Comment by gajindubandara** [comment]
@jayasanka-sack @Gravewalker666 Should we create separate sheets for the advisory panel, external collaborators, etc. or should we put them all in the same google sheet

**Comment by gajindubandara** [comment]
@miniskynet sheet format is Ok. Use the data in the JSON file to fill the image and Linkedin columns

**Comment by miniskynet** [comment]
@gajindubandara hello, as per the message (reference to team.json file snippet) I sent previously, would this format be okay? 
and while @jayasanka-sack @Gravewalker666 gets back with a reply I'll put everything in a single sheet. 
![image](https://user-images.githubusercontent.com/49517852/125240053-3053b300-e307-11eb-9551-24439612599e.png)

**Comment by Gravewalker666** [comment]
> @jayasanka-sack @Gravewalker666 Should we create separate sheets for the advisory panel, external collaborators, etc. or should we put them all in the same google sheet

Let's make separate sheets or multiple tabs in the same sheet. See what works the best, try to find the solution that requires the minimum number of network calls.

**Comment by miniskynet** [comment]
@Gravewalker666 @gajindubandara I have attached the link to the google sheet and have included the details in separate tabs. Please take a look and tell me if it looks okay. I can move onto the scripts if this is good. 

Google sheets link : https://docs.google.com/spreadsheets/d/1fcoXrjeJUSxcU6d3x2-SvNhkR76H05sTbf8h4RfWJgU/edit?usp=sharing
