### ISSUE TITLE
IRC landing page

### ISSUE THREAD

**Issue by akshika47** [sef-global/sef-site#104]
IRC Description

-Image of the IRC call for SL researchers-

-sign up link-

-profiles of the researchers-

**Comment by bpdesilva** [comment]
We need to have a server side to approach it's high time we moved to LAMP stack or MEAN/MEVN. @jayasanka-sack shall we start working on this because Google Forms aren't going to cut it for everything. @akshika47 Thoughts ?

**Comment by akshika47** [comment]
I agree with you @bpdesilva but it is not a priority at the moment. Raise a low priority ticket for it!

**Comment by bpdesilva** [comment]
@jayasanka-sack Please check the website & update accordingly.
