### ISSUE TITLE
Update Nav Bar

### ISSUE THREAD

**Issue by bpdesilva** [sef-global/sef-site#105]
Home 

Projects
- Onelive - Landing page (Speakers,Companies or universities, tune in & Contribute)
- ScholarX - Landing page (Mentors, Companies or universities, How to get started, Contribute)
- IRC- TBA 

About
- Who we are
- Contribute ( Link to Google Form or Firestore based on program/HR)
- Get in touch (Link to Google Form or Firestore based on program)
- Team (Update page with the board & new members)
- Alumni (Move all current team members to this page)

Blog

**Comment by bpdesilva** [comment]
@akshika47 any updates to this ? @jayasanka-sack Deadline this Saturday 10 A.M

**Comment by akshika47** [comment]
This looks about right for the time being. I will double check to be sure.

**Comment by bpdesilva** [comment]
https://stackoverflow.com/questions/31954089/html-css-navigation-bar-on-multiple-pages

**Comment by akshika47** [comment]
Need to fix the order of the "About" tab as well(unless it is done already)

**Comment by akshika47** [comment]
@bpdesilva This is not yet complete. 
- [x] Need to fix the order of the "About" tab
- [x] need to right align the tabs rather than being in the middle.

**Comment by bpdesilva** [comment]
@akshika47 need to right align the tabs rather than being in the middle. ?

& Order respective to the current one ?

**Comment by akshika47** [comment]
Yeah. For the order of items inside the 'about' tab is given in the first description!

**Comment by jayasanka-sack** [comment]
@akshika47 May I close this issue?

**Comment by akshika47** [comment]
Yes, we can close this.
