### ISSUE TITLE
Add a preloader to the Team page

### ISSUE THREAD

**Issue by gajindubandara** [sef-global/sef-site#1053]
**Is your feature request related to a problem? Please describe.**
The team page is taking some time to load the data to the page. It shows as in below for few seconds

![Screenshot from 2021-07-27 12-09-23](https://user-images.githubusercontent.com/63200586/127107642-87e7139c-f360-45d3-a9dd-4752d0a7e798.png)
**Describe the solution you'd like**
Add a preloader to the team page to avoid that

**Comment by gajindubandara** [comment]
I'm working on this

**Comment by janethavi** [comment]
@gajindubandara For the same issue, will you be able to make the buttons(SEE MORE and SEE LESS) visible after the images are loaded?

**Comment by gajindubandara** [comment]
> @gajindubandara For the same issue, will you be able to make the buttons(SEE MORE and SEE LESS) visible after the images are loaded?

I tried with the preloader thing. So after the preloader, when the page is visible you can only see the SEE MORE button and all the images are loaded at that time. Is that what you meant?

**Comment by janethavi** [comment]
No no. While the preloader is working, both the buttons should be hidden(because no point of having both the buttons until the images appear). Currently, before the images are loaded both the buttons are visible. So that makes no sense because still the images are not loaded. So it would be nice if we can make both the buttons hidden until the preloader is complete. Once the images are loaded we can display the appropriate button.

**Comment by gajindubandara** [comment]
> No no. While the preloader is working, both the buttons should be hidden(because no point of having both the buttons until the images appear). Currently, before the images are loaded both the buttons are visible. So that makes no sense because still the images are not loaded. So it would be nice if we can make both the buttons hidden until the preloader is complete. Once the images are loaded we can display the appropriate button.

Yeah! I got it. I'll look into that

**Comment by gajindubandara** [comment]
@janethavi I'll create a new issue for that and I'll send a PR for that
