### ISSUE TITLE
ScholarX - landing page Structure

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#106]
This is regarding issue #94.

Create a landing page for ScholarX. 
The page should include the following details. But we need only the structure. Use dummy texts when creating the page.

- What is ScholarX?
- Why ScholarX?
- Mentor List with their (at least)LinkedIn links
- ScholarX Video
- Student Guide - You can get an idea from the Student Guide
- How to be a ScholarX? - there is a Google Form for this created. The embed code will be provided.
- How to be a mentor? 
- FAQ

create a directory named scholarx in root directory and inside that create a file named index.html

Use this template [template.html](https://github.com/SustainableEducationFoundation/LiveWeb/blob/master/template.html)

Components: [components.html](https://github.com/SustainableEducationFoundation/LiveWeb/blob/master/examples/components.html)
 
Please read issue #94 for more details.
 
[ScholarX_Student_Guide.pdf](https://github.com/SustainableEducationFoundation/LiveWeb/files/2989579/ScholarX_Student_Guide.pdf)

[ScholarX_Mentor_Guide.pdf](https://github.com/SustainableEducationFoundation/LiveWeb/files/2989578/ScholarX_Mentor_Guide.pdf)

**Comment by jayasanka-sack** [comment]
Edit this page:
https://github.com/SustainableEducationFoundation/LiveWeb/blob/master/scholarx/index.html

**Comment by jayasanka-sack** [comment]
Use this page: 
https://github.com/SustainableEducationFoundation/LiveWeb/blob/master/scholarx/index.html

**Comment by Gravewalker666** [comment]
ill do it

**Comment by Gravewalker666** [comment]
Done #109 pr
