### ISSUE TITLE
Onelive speaker linkedin profiles are loading in the same tab

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#1064]
**Describe the bug**
https://sefglobal.org/onelive 
On the onelive page, the speaker LinkedIn profiles are loading in the same browser tab. It's better to load the LinkedIn profile in a new tab

**To Reproduce**
1. Go to 'https://sefglobal.org/onelive'
2. Go to the speakers section
3. Click the linked in button on a speaker profile

**Expected behavior**
Open the linked in profile in a new tab instead of opening in the same tab

**Screenshots**
![image](https://user-images.githubusercontent.com/27498587/127815652-bd450b7c-157c-4e09-afb6-ba914ea5f559.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOs BigSur
 - Browser [e.g. chrome, safari] Google Chrome

**Additional context**
N/A

**Comment by pasindur99** [comment]
If @Isuru4043 not working on this, I can send a PR for this issue.

**Comment by Gravewalker666** [comment]
yeah @pasindur99 please go ahead
