### ISSUE TITLE
Fix FAQ sections' in Scholarx 2021 page

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#1068]
**Describe the bug**
The FAQ sections(FAQ for mentors and mentees both) of the [ScholarX-21](https://sefglobal.org/scholarx/archive/2019/) have lost the consistent look when comparing it with other FAQ sections in other pages([Onelive](https://sefglobal.org/onelive/), [IRC](https://sefglobal.org/irc.html)). 

**To Reproduce**
1.Go to the The FAQ sections of the [ScholarX-21](https://sefglobal.org/scholarx/archive/2019/) page
2. See the CSS difference.

**Expected behavior**
These cards need to have a padding inside as the other cards(in other FAQ sections). But this change should apply only to the FAQ section and it should not change the other cards(Featured stories) on this page.

**Screenshots**
![Screenshot from 2021-08-03 21-58-44](https://user-images.githubusercontent.com/35697678/128052220-566eb87e-c130-4422-a563-3423dd875588.png)

**Comment by anjula-sack** [comment]
We have the same issue in the scholarX summer page.

**Comment by miniskynet** [comment]
@janethavi @anjula-sack  ScholarX 2021 page and summer page both use the same CSS right?

**Comment by anjula-sack** [comment]
@miniskynet yeah but seems like a class missing in the FAQ section. I'm not sure

**Comment by miniskynet** [comment]
@janethavi can I work on this?

**Comment by miniskynet** [comment]
@anjula-sack can you please assign this to me?

**Comment by anjula-sack** [comment]
sure go ahead
