### ISSUE TITLE
Fix profile issues in scholarx

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#1071]
**Describe the bug**
There are a couple of small bugs which are as follows.
1) The image of `Hasini Weerathunge(PhD Student, Boston University)` is wrong
2) The photos of Dr. Charith Peris, Rukshani Somarathna, and Ashane Fernando are stretched.

**To Reproduce**
1. Go to https://sefglobal.org/scholarx/2021/
2. Click `SEE MORE` in the mentors section
3. See the above issues

**Expected behavior**
Please find the correct images from the following links and upload them to the correct path in `Cloudinary`. 
1) [Hasini Weerathunge](https://drive.google.com/file/d/1bMNTJzUWpkeZMm47_GfIXkIMhezgkLcu/view?usp=sharing)
2) [Dr. Charith Peris](https://drive.google.com/file/d/1gOlXVK3jKAUsPl2Ey4zW3yawf8gjyWDu/view?usp=sharing)
3) [Rukshani Somarathna](https://drive.google.com/file/d/1K_WaRlkMP9iAFmM2fLzhrpIXruv4nu0p/view?usp=sharing)
4) [Ashane Fernando](https://drive.google.com/file/d/141kpCAh12VNd1oA0OK1rFQt0avVc8UE-/view?usp=sharing)

**Comment by janethavi** [comment]
@gajindubandara Will you be able to upload these images into Cloudinary and update this thread with the links?

**Comment by gajindubandara** [comment]
Sure! I'll do that

**Comment by gajindubandara** [comment]
@janethavi I added the images to the Cloudinary and fixed the issue on the google sheet

![Screenshot from 2021-08-05 12-02-53](https://user-images.githubusercontent.com/63200586/128302601-aa583953-2ff5-458a-8426-821f35271229.png)

**Comment by janethavi** [comment]
Great work @gajindubandara!
