### ISSUE TITLE
Spelling mistake in scholarx redirection message

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#1079]
**Describe the bug**
<img width="465" alt="Screenshot 2021-08-06 at 19 12 54" src="https://user-images.githubusercontent.com/27498587/129082581-9ea8715d-79d7-4436-86cc-7e797c6bcf00.png">
Spellings of ScholarX is wrong. One letter ('r') is missing

**To Reproduce**
1. Go to 'https://sefglobal.org/scholarx/'
2. Check the redirection message
3. See error

**Expected behavior**
It should be "Redirecting you to the current ScholarX program."

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Chrome 

**Additional context**
N/A

**Comment by fustroli** [comment]
Hello!
I would like to take this issue please.

**Comment by Gravewalker666** [comment]
Sure @VWRoli, go ahead.
