### ISSUE TITLE
Add a preloader to Onelive & IRC pages 

### ISSUE THREAD

**Issue by gajindubandara** [sef-global/sef-site#1082]
**Is your feature request related to a problem? Please describe.**
The Onelive & IRC pages are taking some time to load the data to the pages. It shows as in below for few seconds

![Screenshot from 2021-08-15 10-18-23](https://user-images.githubusercontent.com/63200586/129467502-44205a2a-fc17-4148-8e86-2721825f7b03.png)
![Screenshot from 2021-08-15 10-18-37](https://user-images.githubusercontent.com/63200586/129467503-915efff2-563d-474e-913b-d397bbe70bca.png)

**Describe the solution you'd like**
Add a preloader to Onelive & IRC pages to avoid that 
* Take a look at the PR for the Team page preloader (https://github.com/sef-global/sef-site/pull/1077)
* Already the CSS is created for the preloader
* Add the related content to the HTML files

**Comment by fustroli** [comment]
I would like to take this issue.

**Comment by Piumal1999** [comment]
@VWRoli Yeah sure.
