### ISSUE TITLE
Replace ScholarX 2021 mentor profile images with Cloudinary URLs

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#1084]
**Is your feature request related to a problem? Please describe.**
Some of the mentor profile image links are not replaced with Cloudinary images. Click a mentor profile to see the error.
https://sefglobal.org/scholarx/2021/
![image](https://user-images.githubusercontent.com/27498587/129537540-b6baf903-306b-4fdd-8ee4-d9d97c2cfa88.png)

**Describe the solution you'd like**
Replace ScholarX 2021 mentor profile images with Cloudinary URLs

**Describe alternatives you've considered**
N/A

**Additional context**
@gajindubandara can you put the instructions and the image links here, so someone can work on this

**Comment by gajindubandara** [comment]
Replace `img src="images/{{image}}"` in the ScholarX 2021 index.html (Line 620) with `img src="https://res.cloudinary.com/dsxobn1ln/image/upload/{{image}}"`

**Comment by Hasthikagirihagama** [comment]
I would like to work on this issue
