### ISSUE TITLE
Place Pull Request/ Commits session in a more discoverable place 

### ISSUE THREAD

**Issue by akeel230** [sef-global/sef-site#1093]
**Is your feature request related to a problem? Please describe.**
We currently have the PR session inside the Best practices session, it's hard to discover it. And the PR session has to be more highlighted than being in the best practices session.

**Describe the solution you'd like**
Move it out to the README.md under a separate PR session

**Describe alternatives you've considered**
Move up the PR session inside  the Best practices document itself

**Additional context**
https://sef.discourse.group/t/improve-readability-of-our-repositorys-codes/333

**Comment by akeel230** [comment]
Im working on this, Thanks

**Comment by akeel230** [comment]
@janethavi @Gravewalker666 @anjula-sack is it better to remove the PR and commit session from the best practices md and replace it in the README.md completely?

**Comment by jayasanka-sack** [comment]
Do you mean "section"?

**Comment by jayasanka-sack** [comment]
Moved to: https://github.com/sef-global/sef-handbook/pull/7
