### ISSUE TITLE
Add preloaders to ScholarX 2020 & 2019 mentee's section

### ISSUE THREAD

**Issue by gajindubandara** [sef-global/sef-site#1094]
**Is your feature request related to a problem? Please describe.**
On the ScholarX 2020,2019 pages, the mentee's section is taking some time to load the data

**Describe the solution you'd like**
Add preloaders to ScholarX pages to avoid that

* Take a look at the PR for the IRC page research intern's section  (https://github.com/sef-global/sef-site/pull/1092)
* Already the CSS is created for the preloader
* Add the related content to the HTML files

**Comment by fustroli** [comment]
I would like to take this issue.
