### ISSUE TITLE
Replace Scholarx21 link with the summer Scholarx21 link

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#1096]
**Describe the bug**
The ScholarX-21 link should be replaced with the new ScholarX-21 Summer page.

**To Reproduce**
1. Go to `Projects` from the navigation bar and click `ScholarX`
2. It will redirect to the old scholarx-21 page.

**Expected behavior**
This link should be replaced to the new scholarx-21 summer page(https://sefglobal.org/scholarx/2021/summer/). This link should be replaced in two places. Please find them below.
1) Navigation bar-> Projects -> ScholarX
2) Home page -> Project Section -> ScholarX

**Comment by Gravewalker666** [comment]
@janethavi I don't think we intend to show this edition as the newest scholarx program on the site. 
We made this page just to redirect users from the scholarx platform for more details.

**Comment by janethavi** [comment]
Oh Sorry. I created this issue as per the discussion on the slack channel. Please confirm and let me know if this is not relevant.

**Comment by Gravewalker666** [comment]
Oh, I wasn't aware of such a discussion. Can you please direct me to the conversation? :)

**Comment by janethavi** [comment]
@Gravewalker666 I tagged you into the thread. Can you have a look?

**Comment by Gravewalker666** [comment]
@janethavi yeah i checked :) 
Please proceed with this.

**Comment by Bluechai03** [comment]
Good day! I'm interested in tackling this issue, can I take it?

**Comment by janethavi** [comment]
Sure go Ahead @Bluechai03 !

**Comment by Bluechai03** [comment]
Thank you, I just made a PR :D
