### ISSUE TITLE
Fix Featured Stories section in scholarx summer page

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#1099]
**Describe the bug**
The [ScholarX summer page](https://sefglobal.org/scholarx/2021/summer/) `Featured Stories` section is empty. The data is not visible in this section.

**To Reproduce**
1. Go to [https://sefglobal.org/scholarx/2021/summer/](https://sefglobal.org/scholarx/2021/summer/)
2. Scroll down to 'Featured Stories'
3. See that the blogs are missing

**Expected behavior**
The data(blogs) should be populated in this section.

**Comment by miniskynet** [comment]
can I work on this? @janethavi

**Comment by janethavi** [comment]
Sure go ahead @miniskynet !

**Comment by miniskynet** [comment]
@janethavi only the "see more" button has to be removed right? 
And the featured stories section is empty?
