### ISSUE TITLE
Fix CSS inconsistancy in Upspeak page

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#1101]
**Describe the bug**
In the [Upspeak page](https://sefglobal.org/upspeak/), `This is what our past participants had to say.....` heading does not follow the CSS formating of the other pages headings.

**To Reproduce**
1. Go to [https://sefglobal.org/upspeak](https://sefglobal.org/upspeak)
2. Scroll down to `This is what our past participants had to say.....` section
3. See the inconsistency 

**Expected behavior**
This heading should be like the other headings on the website. Refer to any page(eg:- [OneLive page Upcoming Events section header](https://sefglobal.org/onelive/) and get the exact CSS classes that have been used in the section header.

**Comment by lilRaptor99** [comment]
can I work on this? @janethavi

**Comment by janethavi** [comment]
Sure go ahead @lilRaptor99

**Comment by lilRaptor99** [comment]
While working on this issue, I found that the styles of `.testimonial-section .main-topic` and `.testimonial-section .paragraph` are duplicated on lines 17, 46, and 42, 54 of the `assets/css/global-custom.css` file.

![image](https://user-images.githubusercontent.com/72651307/131397769-47dcefd1-7ebc-4060-b6e6-9bc185f3bf3c.png)

The styles in `.testimonial-section .main-topic` are related to this issue.
@janethavi  what should I do? Should I delete those duplicated styles?

**Comment by Gravewalker666** [comment]
@lilRaptor99 nice catch, :)
yes please do and include it in the commit description. 
Before you do please take another look if it has the same content.

**Comment by lilRaptor99** [comment]
> @lilRaptor99 nice catch, :)
> yes please do and include it in the commit description.
> Before you do please take another look if it has the same content.

Alright @Gravewalker666
