### ISSUE TITLE
Developer badges page profile picture 404 error

### ISSUE THREAD

**Issue by Gravewalker666** [sef-global/sef-site#1107]
**Describe the bug**
Developer badges page profile picture is not loading, the request for it receives a 404 status code. 

**To Reproduce**
1. Go to `/developers/?user=<hive-user-name>&badge=5`

**Expected behavior**
It should be able to fetch and render the image from sef hive

**Screenshots**
<img width="452" alt="image" src="https://user-images.githubusercontent.com/45477334/133795992-0f9b9195-3bbd-4b50-a54f-e79a5e1a51a9.png">

**Comment by akeel230** [comment]
ill work on this
