### ISSUE TITLE
Edit ScholarX Summer page Take a look at our past ScholarX section

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#1108]
**Describe the bug**
The [ScholarX summer page](https://sefglobal.org/scholarx/2021/summer/) `Take a look at our past ScholarX` doesn't show any difference to the section above it. 

**To Reproduce**
1. Go to [ScholarX summer page](https://sefglobal.org/scholarx/2021/summer/)
2. Scroll down to `Take a look at our past ScholarX` section
3. See that this section looks same as the section above it.

**Expected behavior**
Make this section's background colour to white. eg :- [ScholarX-21](https://sefglobal.org/scholarx/2021/)

**Comment by deshankoswatte** [comment]
@janethavi I'll work on this.

**Comment by janethavi** [comment]
Go Ahead! @deshankoswatte
