### ISSUE TITLE
ScholarX Landing page - Changes

### ISSUE THREAD

**Issue by akshika47** [sef-global/sef-site#111]
- [ ] "Premium Mentoring by Sri Lankans" convert to -> _"Premium Mentoring by Sri Lankans for Sri Lankans"_
- [ ] Two images must be changed. Could be something related to Sri Lanka or mentoring!
- [ ] Height of the mentor boxes needs to be the same
- [ ] Description of the mentor boxes needs to be ordered properly. At the moment they are properly ordered within each box.
- [ ] Delete the student guide part
- [ ] "Find a mentor for me section" - content. change "The deadline for the program is on 14/04/2019, Application link can be found below For more information write to us via sustainableedufoundation@gmail.com" -> _"The deadline for the first phase of the program is on 14/04/2019, Application link can be found below For more information and to be added to the waiting list for the next phase of the program, please write to us via sustainableedufoundation@gmail.com"_
- [ ] "How to be a Mentor?" section :  We are always in the look for exceptional mentors. Please write to us with your cv via our email : sustainableedufoundation@gmail.com
- [ ] FAQ section : Font size needs to be changed, it seems it is not matching to the other sections of the page. and also the last question's bullet points are bigger than its previous line. That needs to be changed as well.

**Comment by jayasanka-sack** [comment]
ack
