### ISSUE TITLE
Update ScholarX-21 page

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#1111]
**Is your feature request related to a problem? Please describe.**
The current [Scholarx-21](https://sefglobal.org/scholarx/2021/) page is not linked anywhere on the webpage. Currently, the [ScholarX summer page](https://sefglobal.org/scholarx/2021/summer/) is linked on the website under Scholarx. The correct way of doing this change is to add a new section on the [Scholarx-21](https://sefglobal.org/scholarx/2021/) to link the [ScholarX summer page](https://sefglobal.org/scholarx/2021/summer/).

**Describe the solution you'd like**
On the [Scholarx-21](https://sefglobal.org/scholarx/2021/) page, between the `Mentors Section` and the `Featured Stories` this new section should be added. The Figma design for this section is attached below.
![Untitled](https://user-images.githubusercontent.com/35697678/134026072-08366345-127f-4a0d-9e2d-e7bdfbd50918.png)

The button should be linked to [ScholarX summer page](https://sefglobal.org/scholarx/2021/summer/). The navigation bar link to ScholarX should also be changed to [Scholarx-21](https://sefglobal.org/scholarx/2021/). The home page `At SEF, We Have Something In Store For Everyone!` section ScholaX link should also be changed to  [Scholarx-21](https://sefglobal.org/scholarx/2021/).

Use the default colours to the section heading and to the button. The illustration image can be found at the link below.
https://drive.google.com/file/d/1TZ4GToXxAR1BhhCv_uCfB8-q9Hj-CHTg/view?usp=sharing

**Comment by lilRaptor99** [comment]
@janethavi Can I work on this?

**Comment by janethavi** [comment]
Sure go ahead @lilRaptor99!
