### ISSUE TITLE
Introduce checkboxes to mentors section of ScholarX-21

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#1112]
**Describe the bug**
On the `mentors section` of the [Scholarx-21](https://sefglobal.org/scholarx/2021/) page, currently, there are buttons to filter the mentors. Instead of buttons, it will be a good UX feature if we introduce checkboxes. 

**To Reproduce**
1. Go to [Scholarx-21](https://sefglobal.org/scholarx/2021/) page
2. Scroll down to `Mentors section`
3. See the buttons

**Expected behavior**
The mentor filtering options should be on checkboxes while the `Show All` will be kept as a button. Once the `Show All` button is clicked, all the options should be checked and the entire list should be displayed. Additionally, these checkboxes should be center-aligned instead of left align.

**Comment by lilRaptor99** [comment]
@janethavi can I work on this?

**Comment by janethavi** [comment]
Sure go on @lilRaptor99
