### ISSUE TITLE
Rename the Dev team name with Engineering team in the Team pages 

### ISSUE THREAD

**Issue by akeel230** [sef-global/sef-site#1116]
**Is your feature request related to a problem? Please describe.**
We have decided to rename the Dev team as the Engineering team. We need to change the name in the teams page 

**Describe the solution you'd like**

![Screenshot (475)](https://user-images.githubusercontent.com/83522139/135720687-ef5825f2-b153-4106-8e83-83635be03d0b.png)

**Describe alternatives you've considered**
To recreate go to team.html see the h1 tag which has the Dev team name, replace it with Engineering team name

**Comment by jaebirds** [comment]
Fixed this in #1119

**Comment by akeel230** [comment]
@jaebirds can u please add the issue number and edit the preview link, so we can review the PR and merge it. Thank you
