### ISSUE TITLE
Make the Upspeak card for our projects session in the Home page

### ISSUE THREAD

**Issue by akeel230** [sef-global/sef-site#1117]
**Is your feature request related to a problem? Please describe.**
Create the upspeak card and add the information in the card

**Describe the solution you'd like**

![Screenshot (474)](https://user-images.githubusercontent.com/83522139/135721067-903d49e8-ef5e-41dd-bffa-4b4748c67bc6.png)

**Describe alternatives you've considered**
To fix the issue go to index.html file , find the our projects section , create the card following the same design 

**Additional Info**
Will have to get the information needed from the responsible parties

**Comment by pasindur99** [comment]
Can I work on this issue?

**Comment by janethavi** [comment]
Sure! Go ahead @pasindur99

**Comment by pasindur99** [comment]
Thank you! @janethavi 
Sorry to interrupt. @akeel230 You mentioned in the squad call that you will work on this issue. Is it okay that I work on this?

**Comment by akeel230** [comment]
@pasindur99 no it's completely fine, I said ill be helping with the issue since the information for the Upspeak card is missing, ill find the information and give it to you, till then u can make the design with dummy text.

**Comment by pasindur99** [comment]
Okay sure. Let me know when you gathered the information. Thank you @akeel230
