### ISSUE TITLE
Redesign the title name in the Home page 

### ISSUE THREAD

**Issue by akeel230** [sef-global/sef-site#1118]
**Is your feature request related to a problem? Please describe.**
The Sustainable Education Foundation name needs redesigning 

**Describe the solution you'd like**

![Screenshot (473)](https://user-images.githubusercontent.com/83522139/135721391-93b71688-3088-4215-baeb-cf44188f3aab.png)

**Describe alternatives you've considered**
To fix the issue go to the index.html file, find the Sustainable Education Foundation name,  design the name to suit the theme.

**Additional context**
Assign yourself to get further information on precise design requirements.

**Comment by gajindubandara** [comment]
I would like to work on this

**Comment by akeel230** [comment]
I'll work on this because the exact color and font sizes etc. are not known. we might have to change it several times and check so ill give it a go.Thanks
