### ISSUE TITLE
Onelive - landing page Structure 

### ISSUE THREAD

**Issue by bpdesilva** [sef-global/sef-site#112]
- What is Onelive? : “OneLive” is an interactive webinar series done every weekend with the experts in their fields. “OneLive” is a trademark program of SEF with the vision to expand the knowledge of Sri Lankan students and it will allow you to interact with the speaker via asking questions live. “OneLive” is the future of knowledge sharing and it is a popular medium for Sri Lankan students who seek for inspiration.

- Why Onelive?
- People & Universities(Significant)
- Onelive Video
- Tune in - Youtube Playlist link or Facebook Play list
- Onelive Snippets =>  Render : 2 Onelive Snippets
- How to be a speaker?
- FAQ

**Comment by 99sumedha** [comment]
Doing

**Comment by jayasanka-sack** [comment]
Did some changes
