### ISSUE TITLE
Change the order of the cards

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#1123]
**Describe the bug**
On the home page under the `Our Projects` section the card order needs to be changed. The same order needs to be applied to the navigation bar, projects menu.

**To Reproduce**
1. Go to [https://sefglobal.org/](https://sefglobal.org/)
2. Scroll down to `Our Projects` section
3. See the current order
4. See the navigation bar projects list as well

**Expected behavior**
The order should be as follows.

`Home page cards order`
1st Line :- ScholarX -> IRC -> OneLive
2nd Line :-  Academix -> UpSpeak -> Student Ambassador

`Projects menu order` (Already fixed with #1124)
1. ScholarX 
2. IRC
3. OneLive
4. Academix 
5. UpSpeak
6. Student Ambassador

**Comment by ManishOffi** [comment]
Hey @janethavi ,
Please can you assign me ?

**Comment by Ambareen15** [comment]
please can you assign this to me

**Comment by Piumal1999** [comment]
> Hey @janethavi , Please can you assign me ?

Yeah sure. @ManishOffi you can start working on this issue

**Comment by akeel230** [comment]
@Ambareen15 Sorry for the inconvenience caused, we have the first request first serve policy, Please note that there will be plenty of issues to work on in our Repos, Which will be available soon.  Thank you for your request.

**Comment by Piumal1999** [comment]
@akeel230 I created a separate issue for the navbar update(@ManishOffi had already sent a PR for the navbar). So I'm removing the assignee.

Therefore this PR is now open for anyone. 

Now, only this part is needed to be done in order to complete this issue:
> Fix Home page cards order
1st Line :- ScholarX -> IRC -> OneLive
2nd Line :- Academix -> UpSpeak -> Student Ambassador

**Comment by akeel230** [comment]
@Piumal1999 thanks

**Comment by oneamanish** [comment]
see my pull req.

**Comment by Piumal1999** [comment]
@oneamanish @akeel230, I already reviewed the pull request and requested some changes. @oneamanish Please add the request changes and update the pull request description. Let us know if there's any problem.

**Comment by ghost** [comment]
Shall I work on this issue?

**Comment by ghost** [comment]
Thank You
