### ISSUE TITLE
Remove the (emoji) Image from the one live page

### ISSUE THREAD

**Issue by akeel230** [sef-global/sef-site#1130]
**Is your feature request related to a problem? Please describe.**
Remove the (emoji) Image from the one live page which is not suitable for the design 

**Describe the solution you'd like**
Remove the Image which contains the emojis below the see more button of the "Take a look at our past OneLives" section

**Screenshot**

![Screenshot (536)](https://user-images.githubusercontent.com/83522139/138460537-8143a9ba-9d64-463f-9955-2f01815f1f84.png)

**Additional context**
Find the image in the HTML doc either by inspecting or by code and remove the emoji image.

**Comment by Tegridy** [comment]
Hi @akeel230 
Could you assign me to this issue ?

**Comment by Piumal1999** [comment]
Yeah sure! @Tegridy
