### ISSUE TITLE
Change the footer background-color of the One Live page 

### ISSUE THREAD

**Issue by akeel230** [sef-global/sef-site#1131]
**Is your feature request related to a problem? Please describe.**

The background color of the one live page footer is not separated from the section above. Change the background color of the 
footer to match the design in the rest of the pages

**Describe the solution you'd like**

Go through the footer designs of the other pages, see the footer is clearly separated from other sections in the page
change the color of the footer to separate it from the rest of the sections
![Screenshot (538)](https://user-images.githubusercontent.com/83522139/138461277-3eae7869-b502-4dc3-a8c5-98e22ee6dc20.png)

**Describe alternatives you've considered**

This may be a bug due to a misplacing a div tag inside a footer, or an indentation fault.
Go through the code to find the error 

**Additional context**
Using the inspect tool in a web browser might help in this task

**Comment by pasindur99** [comment]
I'm about to start working on this as we discussed on stand-up call. Please assign this task to me. Thank you.
