### ISSUE TITLE
Fix screen responsiveness of the home testimonial cards

### ISSUE THREAD

**Issue by gajindubandara** [sef-global/sef-site#1133]
**Describe the bug**
Home page testimonials are not responsive for some resolutions

**Expected behavior**
Fix the screen responsive issue of the testimonial cards

**Screenshots**
![Screenshot from 2021-10-25 09-16-32](https://user-images.githubusercontent.com/63200586/138631948-db65eaa3-e127-4b88-82a1-cf59d8b3f558.png)
![Screenshot from 2021-10-25 09-16-51](https://user-images.githubusercontent.com/63200586/138631952-57ba6370-edc4-4939-9043-c0e941c51dee.png)

**Comment by Piumal1999** [comment]
Duplicate issue #1128
