### ISSUE TITLE
Add Box shadows to testimonial section in the Home page

### ISSUE THREAD

**Issue by akeel230** [sef-global/sef-site#1136]
**Is your feature request related to a problem? Please describe.**
the current testimonial section does not have box shadows, it is not visible since the background color is not white

**Describe the solution you'd like**
Change the background color to white, add box shadows to testimonial boxes to match the design of the projects cards 

![Screenshot (543)](https://user-images.githubusercontent.com/83522139/138718818-9aea755f-55a1-4f5c-83fc-e0485abe89c5.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by wilsonfurtado2000** [comment]
assign this to me

**Comment by Piumal1999** [comment]
I assigned you @wilsonfurtado2000. Feel free to contact us if you need any clarifications.

**Comment by gajindubandara** [comment]
I'll work on this
