### ISSUE TITLE
Relocate the Join the team button 

### ISSUE THREAD

**Issue by akeel230** [sef-global/sef-site#1137]
**Is your feature request related to a problem? Please describe.**
The " Join the team" button has to be moved just below the volunteer description of the "At SEF, We Have Something In Store For Everyone!" section.

It is currently below the testimonial section 

**Describe the solution you'd like**

![Screenshot (545)](https://user-images.githubusercontent.com/83522139/138719981-fdf1ea87-cb07-430e-8fb8-ae451a9aba3f.png)

**To fix the issue**
move the text and the join the team button below the volunteer description and above the Press coverage section.
![Screenshot (546)](https://user-images.githubusercontent.com/83522139/138720142-06f390c8-9b77-4c08-9353-3e730e775e73.png)

**Additional context**
This would further enhance the flow on the home page

**Comment by GauravKesarwani** [comment]
Could you assign this issue to me.

**Comment by Piumal1999** [comment]
Assigned @GauravKesarwani

**Comment by AkshayHere** [comment]
Hi @Piumal1999, Looks like this issue is still open. 
I would like to work on this one.

**Comment by Piumal1999** [comment]
Yeah sure @AkshayHere
