### ISSUE TITLE
Update Academix URL

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#1145]
**Is your feature request related to a problem? Please describe.**
 We added the SSL certificate for the server which was used to deploy AcademiX platform. So we need to change the http URLs to https.

**Describe the solution you'd like**
Change the academic URL (`http://apps.sefglobal.org/academix/`) to `https://apps.sefglobal.org/academix/` in homepage project card and navbar dropdown
Homepage location: /index.html
Navbar location: /assets/content/static/navbar.html

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by 99sumedha** [comment]
Hi @Piumal1999,
I would like to solve this issue.
