### ISSUE TITLE
Adding the Our journey so far Image from the  "New hire induction" Google slide

### ISSUE THREAD

**Issue by akeel230** [sef-global/sef-site#1150]
**Is your feature request related to a problem? Please describe.**
This is an enhancement for the "New content for the website" project 
https://sef.discourse.group/t/new-content-for-the-websites/362/8  

**Describe the solution you'd like**
Add the roadmap from the Google slide into the Home page Below the "our projects" section.

**Describe alternatives you've considered**
![2bacf22d547cacb5c9e7dfc673f3a5558b0d755b](https://user-images.githubusercontent.com/83522139/147359884-f6fa7fb5-a3d1-426e-9bc2-6bc12a72c170.jpeg)

**Additional context**
Summarize the point form content into a paragraph (request assistance if needed)

**Comment by Madhawa97** [comment]
Assign me please
