### ISSUE TITLE
Make the SEF email in the FAQ section of the Upspeak page into a redirecting Link

### ISSUE THREAD

**Issue by akeel230** [sef-global/sef-site#1155]
**Describe the bug**
In the Upspeak page under the FAQ section in the "How do I become a facilitator?"
and "How do we partner with SEF on the program?" questions when opened we can see the info@sefglobal.com Email address
But it is plain text. We can make it a clickable redirecting Link.

**To Reproduce**
1. Go to the Upspeak page from the Home dropdown
2. Scroll down to FAQ secion
3. Open the second and third Questions
4. See the email is not in link form

**Expected behavior**
For the email to be available as a clickable link (The "link" tag in HTML is used to define a link between a document and an external resource.)"

**Screenshots**
![Screenshot (747)](https://user-images.githubusercontent.com/83522139/149542293-46d60e2b-3b89-4e20-9c3c-5e8b46ba7fa6.png)

**Comment by YoshithaRathnayake** [comment]
Shall I work on this?

**Comment by VishwaAmarasinghe** [comment]
Shall I work on this ?

**Comment by akeel230** [comment]
@VishwaAmarasinghe Sorry since @yoshitha has requested to work on the issue first, ill have to assign it to him. But stay in touch there will be plenty of issues to solve soon. Thank you both of you for requesting to solve this.
