### ISSUE TITLE
Update the preview link generator to add a comment on the PR

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#1157]
**Is your feature request related to a problem? Please describe.**
To complete the template with the preview link, developers must edit the PR with the PR number. It necessitates extra effort, and new contributors find it difficult.

**Describe the solution you'd like**
Update the preview link generator to add a comment on the PR with the preview link.

**Comment by anjula-sack** [comment]
Shall we close this? @jayasanka-sack

**Comment by jayasanka-sack** [comment]
Yeah, it's not possible to achieve it without using the GitHub API.
