### ISSUE TITLE
Create a common Navbar and a footer

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#116]
- [x] Create two html pages for navbar and footer in /assets/content directory.

- [x] Create a js script to load above components dynamically.

- [x] Link the script to every page.

**Comment by Piumal1999** [comment]
i'll do it

**Comment by Piumal1999** [comment]
done pr #117

**Comment by jayasanka-sack** [comment]
Thanks @Piumal1999 👍
