### ISSUE TITLE
The footer year should be changed in the academix

### ISSUE THREAD

**Issue by VishwaAmarasinghe** [sef-global/sef-site#1166]
**Is your feature request related to a problem? Please describe.**
The footer year is wrong. It should be 2022
**Describe the solution you'd like**
The footer year should be 2022.

**Describe alternatives you've considered**
Make the footer year correct by adding script.

**Additional context**
N/A

**Are you working on it?**
Yes

**Comment by VishwaAmarasinghe** [comment]
Shall I work on this ?

**Comment by Piumal1999** [comment]
Hi @VishwaAmarasinghe, the frontend of the academix application is in [academix-frontend](https://github.com/sef-global/academix-frontend) repository. It is built with React and also the design is a bit different. So we can't reuse the sef-site navbar style for academix.

**Comment by VishwaAmarasinghe** [comment]
@Piumal1999 I changed this to make the footer year correctly. Is it okay .

**Comment by VishwaAmarasinghe** [comment]
Can you assign me for this?
