### ISSUE TITLE
Change the Email colour in Acedemix

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-site#1167]
**Describe the bug**
Currently there is purple color in the email link

**To Reproduce**
1. Go to '[Academix Page](https://apps.sefglobal.org/academix/)'

**Expected behavior**
Change the email link color to blue

**Screenshots**
![image](https://user-images.githubusercontent.com/97069900/151894905-f3c45d90-57f5-4020-b086-0d890efc81b7.png)

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by Piumal1999** [comment]
Hi @YoshithaRathnayake, We use purple colour as the primary colour on Academix page. So the existing email link colour is ok with that design.
FYI, academix application is in the [academix-frontend](https://github.com/sef-global/academix-frontend) repo
