### ISSUE TITLE
"Our Journey so far" section information update

### ISSUE THREAD

**Issue by akeel230** [sef-global/sef-site#1168]
**Is your feature request related to a problem? Please describe.**
The information in our journey so far section is outdated. and a HIVE thread is created by @akshika47 with the new data input.

**Describe the solution you'd like**
Get the information from the Hive thread and replace the info with the existing data for the same structure design
https://sef.discourse.group/t/change-our-journey-so-far-content-on-the-landing-page/390

**Additional context**
The design will be the same only the data is to be updated

**Are you working on it?**
No

**Comment by Madhawa97** [comment]
I'd like to work on this.

**Comment by akeel230** [comment]
Sure @Madhawa97 You can work on it.

**Comment by akshika47** [comment]
I think the design also need to be responsive, on my screen it looked a bit out of shape.

**Comment by Madhawa97** [comment]
Okay @akshika47 I will work on it.

**Comment by Madhawa97** [comment]
Pushed the requested changes. would like to receive your feedback.
