### ISSUE TITLE
Update the Academix project link

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#1170]
**Is your feature request related to a problem? Please describe.**
- AcademiX project link has been changed but the site has the old one. We need to update the link with the new one.

**Describe the solution you'd like**
- Find the places with `https://apps.sefglobal.org/academix/`
- Replace them with `https://sef-academix.herokuapp.com/`

**Additional context**
- Use find and replace to replace this easily

**Are you working on it?**
No

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by anjula-sack** [comment]
> Shall I work on this ?

sure go ahead

**Comment by YoshithaRathnayake** [comment]
Thank you @anjula-sack
