### ISSUE TITLE
Add archives section to Scholarx 2022

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#1172]
**Is your feature request related to a problem? Please describe.**
The archives section is missing on https://sefglobal.org/scholarx/2022/

**Describe the solution you'd like**
Add the archives section. (Similar to the archives section in https://sefglobal.org/scholarx/2021/)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Are you working on it?**
No

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by Piumal1999** [comment]
Assigned @YoshithaRathnayake
