### ISSUE TITLE
Add ScholarX 2021 and ScholarX summer to archives

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#1173]
**Is your feature request related to a problem? Please describe.**
We need to add scholarx 2021 and scholarx summer to the https://sefglobal.org/scholarx/archive/ page

**Describe the solution you'd like**
Create a cards for scholarx 2021 and scholarx summer in https://github.com/sef-global/sef-site/blob/master/scholarx/archive/index.html

**Describe alternatives you've considered**
N/A

**Additional context**
Contact the scholarx team to verify the status of scholarx summer before moving it to archive

**Are you working on it?**
No

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by Piumal1999** [comment]
Assigned @YoshithaRathnayake
