### ISSUE TITLE
Remove "Find a mentor for me" section from ScholarX summer

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#1174]
**Is your feature request related to a problem? Please describe.**
The "Find a mentor for me" is still there on the scholarx summer page even after the end of the program. Need to remove that  section.

**Describe the solution you'd like**
Remove the "Find a mentor for me" section

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Are you working on it?**
No

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by Piumal1999** [comment]
Yeah @YoshithaRathnayake
