### ISSUE TITLE
Update Website Content of the SEF team

### ISSUE THREAD

**Issue by dinuka-rp** [sef-global/sef-site#1178]
Move the following people from the Executive Committee section to the Alumni section
- Kithmin
- Amaya
- Ramith
- Chalani

---

Update the list of new APMs with the following names, under the Executive Committee section
- Shimani Attygalle
- Visal Rajapakse
- Dinuka Piyadigama
- Ashen Hirantha
- Nayanathara Hendeniya
- Shadini Kalansooriya

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by Piumal1999** [comment]
The content on team page is loaded from a google sheet using a script. We should update that sheet to add the new profiles. Am i right? @gajindubandara @Gravewalker666

**Comment by dinuka-rp** [comment]
@YoshithaRathnayake sure, please do

**Comment by anjula-sack** [comment]
### Update

* Move the last year's scholarX team to the alumni section except for Kithmin Wickremasinghe.
* Add this year's team, All of them are Assistant Program Managers

    - Ashen Hirantha
    - Visal Rajapakse
    - Nayanathara hendeniya
    - Dinuka Piyadigama
    - Shimani Umesha Attygalle
