### ISSUE TITLE
Rename apply button in scholarX 2022 page

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#1179]
**Is your feature request related to a problem? Please describe.**
Currently we are in mentee application so that apply as a mentor button needs to be changed
<img width="441" alt="image" src="https://user-images.githubusercontent.com/43912578/159286291-9c54feff-2398-4484-961c-2982348e3c4b.png">

**Describe the solution you'd like**
- Rename the button to `APPLY AS A MENTEE`

**Are you working on it?**
No

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by anjula-sack** [comment]
> Shall I work on this ?

sure go ahead
