### ISSUE TITLE
ScholarX prog content: FAQ deadline mismatch with program timeline

### ISSUE THREAD

**Issue by dinuka-rp** [sef-global/sef-site#1181]
The deadline in the FAQ doesn't match with the timeline (7th of April 2022).
![image](https://user-images.githubusercontent.com/47103883/159292042-32480da9-203e-415f-93c2-23af3e3a11b3.png)

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by Piumal1999** [comment]
> Shall I work on this ?

Yeah @YoshithaRathnayake
