### ISSUE TITLE
Change all the projects FAQ sections' topics to 'Frequently Asked Questions'

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-site#1186]
**Is your feature request related to a problem? Please describe.**
Currently, in upspeak in the FAQ section there is 'FAQ' but in IRC, OnLive, Student Ambassadors in the FAQ section there is 'Frequently Asked Questions'

**Describe the solution you'd like**
Make the all projects' FAQ section to 'Frequently Asked Questions' except scholarx

**Screenshots**

IRC
![image](https://user-images.githubusercontent.com/97069900/159910149-ee396449-bbfa-4cc1-87c8-accd75f36ae1.png)

OnLive
![image](https://user-images.githubusercontent.com/97069900/159910305-e94f3411-e62e-49d0-8773-8bc9aff72936.png)

Student Ambassadors
![image](https://user-images.githubusercontent.com/97069900/159910520-e10c7ed6-d4cb-4348-8af0-6783551eed62.png)

Upspeak
![image](https://user-images.githubusercontent.com/97069900/159910855-8acedf5e-92a9-4241-924b-8a770645c1d0.png)

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by anjula-sack** [comment]
> Shall I work on this ?

sure, Go ahead. :)
