### ISSUE TITLE
Update the ScholarX 2022 page FAQ section

### ISSUE THREAD

**Issue by Gravewalker666** [sef-global/sef-site#1187]
#### Definition of done: 
The answer for the question "How are mentors assigned?" under FAQ for mentees should be changed to what's given in this issue.

**New content**

> Mentor information and areas of expertise are published on the SEF ScholarX platform. Students will be asked to pick their choice of mentor and will be assigned to a mentor based on their choice as well as the relative strength of their application.

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by Gravewalker666** [comment]
Sure go ahead @YoshithaRathnayake
