### ISSUE TITLE
Fix the error in Scholarx Archive 2021 page Check out our archive button

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-site#1194]
**Describe the bug**
Currently, in [Scholarx Archive 2021](https://sefglobal.org/scholarx/archive/2021/) page `Check out our archive` section the link in the button is wrong and it is redirecting to this [link](https://sefglobal.org/scholarx/archive/archive).

**To Reproduce**
1. Go to '[Scholarx Archive 2021](https://sefglobal.org/scholarx/archive/2021/) page'
2. Scroll down to '`Check out our archive` section'
3. Click on '`Check out our archive` button'

**Expected behavior**
Replace this link https://sefglobal.org/scholarx/archive in the anchor tag of the button.

**Screenshots**

![image](https://user-images.githubusercontent.com/97069900/162620778-5136d68e-bdf1-403c-98fd-e391950a27e0.png)

**Are you working on it?**
Yes

**Comment by anjula-sack** [comment]
We removed that from the page right? @YoshithaRathnayake

**Comment by YoshithaRathnayake** [comment]
Oh!
Yes, Sorry @anjula-sack.
I will close the issue.
