### ISSUE TITLE
Update ScholarX 2022 timeline

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#1197]
**Is your feature request related to a problem? Please describe.**
- We need to update the [ScholarX 2022 timeline](https://sefglobal.org/scholarx/2022/).

**Describe the solution you'd like**
- Update the timeline with the following.

Community bonding	                 15 May, 2022 - 28 May, 2022
Official start date of ScholarX	29 May, 2022
Mid-Evaluation	                         31 Aug, 2022
End Evaluation	                         31 Dec, 2022
Graduation

**Are you working on it?**
No

**Comment by miniskynet** [comment]
@anjula-sack please assign this to me
