### ISSUE TITLE
The developer badges page profile image is not loading

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#1199]
**Describe the bug**
- The developer badges page profile image is not loading

**To Reproduce**
1. Go to [developer page](https://sefglobal.org/developers/index.html?user=anjisvj&badge=5)
2. See profile image is not loaded

**Expected behavior**
- The profile image should load properly

You can find the URL generating function [here](https://github.com/sef-global/sef-site/blob/master/developers/functions.js)

**Screenshots**
<img width="284" alt="Screenshot 2022-07-19 at 3 59 03 PM" src="https://user-images.githubusercontent.com/43912578/179729655-32f7b147-28a2-4e70-85b3-c966fb5c2d6d.png">

**Are you working on it?**
No

**Comment by Tharindu37** [comment]
I would like to work on this

**Comment by anjula-sack** [comment]
> I would like to work on this

sure go ahead

**Comment by anjula-sack** [comment]
A working URL is looked like this https://yyz1.discourse-cdn.com/free1/user_avatar/sef.discourse.group/anjisvj/240/7_2.png
@Tharindu37
