### ISSUE TITLE
Add colored indicator to mark to present time line of month in ScholarX page

### ISSUE THREAD

**Issue by dave-v0** [sef-global/sef-site#1202]
**Is your feature request related to a problem? Please describe.**
In the timeline of the ScholarX page, there is no colored indicator to display the current position of the ScholarX process

**Describe the solution you'd like**
Addition of a colored indicator to the present month in the timeline

**Describe alternatives you've considered**
Adding a blue-colored indicator to the timeline

**Additional context**
![image](https://user-images.githubusercontent.com/104125359/181002479-4fb5445d-0cc6-40e9-90cd-9ee8956abbcd.png)

**Are you working on it?**
Yes

**Comment by dave-v0** [comment]
@anjula-sack Can I work on this, please?

**Comment by anjula-sack** [comment]
> @anjula-sack Can I work on this, please?

sure go ahead

**Comment by YoshithaRathnayake** [comment]
@anjula-sack This issue is not closed yet right?
