### ISSUE TITLE
Update scholarX team in the team page

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#1203]
**Is your feature request related to a problem? Please describe.**
We need to update scholarX team in the team page.

**Describe the solution you'd like**
* Move the last year's scholarX team to the alumni section except for Kithmin Wickremasinghe.
* Add this year's team, All of them are Assistant Program Managers

    - Ashen Hirantha
    - Visal Rajapakse
    - Nayanathara hendeniya
    - Dinuka Piyadigama
    - Shimani Umesha Attygalle
   
* Update the google sheet
* Upload the images to the Cloudinary

**Comment by kumuditha-udayanga** [comment]
I would like to work on this

**Comment by anjula-sack** [comment]
> I would like to work on this

Awesome, go ahead

**Comment by anjula-sack** [comment]
Thank you @kumuditha-udayanga for getting this done.
