### ISSUE TITLE
Add SEF handbook link to the navbar and the footer

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#1205]
**Is your feature request related to a problem? Please describe.**
- We need to add the SEF handbook link to the SEF site

**Describe the solution you'd like**
- Add a link called `Handbook`  to the navbar and the header
- Link it to https://handbook.sefglobal.org/
- Open the link in a new window

**Are you working on it?**
No

**Comment by YoshithaRathnayake** [comment]
Shall I work on this?

**Comment by anjula-sack** [comment]
> Shall I work on this?

Go ahead @YoshithaRathnayake

**Comment by YoshithaRathnayake** [comment]
> > Shall I work on this?
> 
> Go ahead @YoshithaRathnayake

Thank you @anjula-sack
