### ISSUE TITLE
Add the slack channel invitation link to the site

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#1210]
**Is your feature request related to a problem? Please describe.**
- We are missing the slack channel invitation on the site.

**Describe the solution you'd like**
- Add the link to the navbar and the footer alongside the social media links

Link: https://join.slack.com/t/sefheadquarters/shared_invite/zt-1ds9bjtli-ry~ggwf2kSJ_j5src89GBQ

**Are you working on it?**
No

**Comment by athulmekkoth** [comment]
can I work on this?

**Comment by anjula-sack** [comment]
> can I work on this?

sure go ahead

**Comment by YoshithaRathnayake** [comment]
@anjula-sack this pr still not closed because the pr was not linked with the issue number right? So you have to do it manual no?

**Comment by anjula-sack** [comment]
> @anjula-sack this pr still not closed because the pr was not linked with the issue number right? So you have to do it manual no?

yes
