### ISSUE TITLE
Sort the alumni section in the team page

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#1211]
**Is your feature request related to a problem? Please describe.**
- We need to sort the alumni section based on their role in SEF

**Describe the solution you'd like**
- Rename Webmaster to Software Engineer
- Sort the names in the team google sheet based on the below order,

Deputy Chairperson
Chief Executive Officer
Chief Technology Officer
Chief Marketing Officer
Chief Communications Officer
Creative Design Executive
Product Manager
Program Manager
Secretary
Assistant Secretary
Assistant Program Manager
Marketing Executive
Operations Executive
Public Relations Executive
Systems Architect
Senior Software Engineer
Software Engineer
Associate Software Engineer
Graphic Designer
Creative Designer
UI & UX Designer

**Are you working on it?**
No

**Comment by kumuditha-udayanga** [comment]
I would like to work on this

**Comment by anjula-sack** [comment]
Thanks for getting this done! @kumuditha-udayanga
