### ISSUE TITLE
Add the hive discourse group link on the site

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#1212]
**Is your feature request related to a problem? Please describe.**
- We are missing the Hive discourse group link on the site.

**Describe the solution you'd like**
- Add the link to the navbar and the footer alongside the social media links

Link: https://sef.discourse.group/

**Are you working on it?**
No

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by YoshithaRathnayake** [comment]
So I should use the sef icon no? @anjula-sack

**Comment by YoshithaRathnayake** [comment]
If not can you please send me a icon? @anjula-sack
