### ISSUE TITLE
Increase size of SEF logo in the SEF website navbar

### ISSUE THREAD

**Issue by dave-v0** [sef-global/sef-site#1214]
**Describe the bug**
The SEF logo in the navbar is too small

**Expected behavior**
Enlarged SEF navbar logo

**Screenshots**
![image](https://user-images.githubusercontent.com/104125359/183500949-1905b268-bd73-45be-9f53-ec797c214ca8.png)

**Are you working on it?**
Yes

**Comment by dave-v0** [comment]
@anjula-sack Can you assign me on this, please?

**Comment by anjula-sack** [comment]
> @anjula-sack Can you assign me on this, please?

sure go ahead
