### ISSUE TITLE
Increasing text size in SEF website navbar

### ISSUE THREAD

**Issue by dave-v0** [sef-global/sef-site#1217]
**Describe the bug**
The text in the SEF navbar is too small 

**To Reproduce**
1. Go to 'https://sefglobal.org/'

**Expected behavior**
Increased text size in navbar

**Screenshots**
![image](https://user-images.githubusercontent.com/104125359/183826884-558b50ab-a095-40f2-98fc-c6d9fc59450a.png)

**Are you working on it?**
Yes

**Comment by dave-v0** [comment]
Can you assign me to this issue, please? I'd like to work on it @anjula-sack

**Comment by anjula-sack** [comment]
> Can you assign me to this issue, please? I'd like to work on it @anjula-sack

Now it seems okay since the logo is bigger.

**Comment by dave-v0** [comment]
> 

okay then!
