### ISSUE TITLE
Fix the SEF blog link to open in a new page

### ISSUE THREAD

**Issue by dave-v0** [sef-global/sef-site#1219]
**Describe the bug**
The SEF Blog opens and loads in the same page when clicked

**To Reproduce**
1. Go to '[(https://sefglobal.org/)]'
2. Click on 'Blog'
3. See error

**Expected behavior**
The blog link should open in a new tab when clicked

**Screenshots**
![image](https://user-images.githubusercontent.com/104125359/184518552-17981288-a630-4f7b-897b-95b23e22b178.png)
![image](https://user-images.githubusercontent.com/104125359/184518562-bc3ecfb2-5d80-4c23-ba8d-59b962155c0b.png)

**Are you working on it?**
Yes

**Comment by dave-v0** [comment]
I'd like to work on this, can you assign me to this please? @anjula-sack

**Comment by Tharindu37** [comment]
I'd like to work on this.

**Comment by anjula-sack** [comment]
> I'd like to work on this.

This is assigned to @DilinaBandara
