### ISSUE TITLE
Removed unused images for the asset folder

### ISSUE THREAD

**Issue by dave-v0** [sef-global/sef-site#1220]
**Describe the bug**
There are many unused images in the SEF site of the asset folder

**To Reproduce**
1. Go to 'https://github.com/sef-global/sef-site/tree/master/assets'

**Expected behavior**
Remove all unused images from the asset folder of the SEF site

**Screenshots**
![image](https://user-images.githubusercontent.com/104125359/184519721-f3bf9afd-9360-4f7b-ad2a-6698caee3495.png)
![image](https://user-images.githubusercontent.com/104125359/184519728-18630630-4d7d-4f16-9e8c-f410f23e0fe7.png)
![image](https://user-images.githubusercontent.com/104125359/184519734-a64c14ad-b477-46d6-9cc8-78fa0bc1fd82.png)
![image](https://user-images.githubusercontent.com/104125359/184519738-e62a20c4-ea2a-436f-bad7-16132fe74600.png)

**Are you working on it?**
Yes

**Comment by dave-v0** [comment]
Can you assign me to this @anjula-sack ?

**Comment by anjula-sack** [comment]
> Can you assign me to this @anjula-sack ?

go ahead
