### ISSUE TITLE
The hero image is missing in past ScholarX pages

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#1227]
**Describe the bug**
The hero image is missing in past ScholarX pages

**To Reproduce**
1. Go to [ScholarX archive](https://sefglobal.org/scholarx/archive/)
2. Click on a card ex:([2019](https://sefglobal.org/scholarx/archive/2019/))
3. See the image is missing

**Expected behavior**
- The hero image should be there

**Screenshots**
<img width="860" alt="image" src="https://user-images.githubusercontent.com/43912578/190889819-e5d3a3f1-721e-444b-8e63-9fa6ea4d2116.png">

**Additional context**
- Use this image
![findmentor](https://user-images.githubusercontent.com/43912578/190889868-19a2535f-79de-47fa-8be2-a5b84515f492.png)
- Add this to this path `/assets/img/scholarx/findmentor.png`

**Are you working on it?**
No

**Comment by Tharindu37** [comment]
I would like to work on this
