### ISSUE TITLE
Remove "Apply as a mentee" button from the scholarX 2022 page

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#1229]
**Is your feature request related to a problem? Please describe.**
- Since we are no longer in the mentee application we can remove that button

**Describe the solution you'd like** 
- Remove "Apply as a mentee" button

<img width="433" alt="image" src="https://user-images.githubusercontent.com/43912578/193415301-c0cd5179-7041-40fa-8265-36b9e2940f68.png">

**Are you working on it?**
No

**Comment by tarunvashishth** [comment]
I want to work on this

**Comment by anjula-sack** [comment]
> tarunvashishth

sure go ahead :)

**Comment by vikash485** [comment]
Hello @anjula-sack , can I contribute towards this issue for my first hacktoberfest?
