### ISSUE TITLE
Make header sticky

### ISSUE THREAD

**Issue by SamikshaSankar** [sef-global/sef-site#1230]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Make header sticky 

**Describe alternatives you've considered**

**Additional context**

**Are you working on it?**
Yes/No

**Comment by SamikshaSankar** [comment]
Please assign me this issue

**Comment by yogesh-9999** [comment]
@SamikshaSankar please assign me this issue

**Comment by anjula-sack** [comment]
> Please assign me this issue

go ahead @SamikshaSankar

**Comment by sathmikaDev** [comment]
@Piumal1999 @anjula-sack   hello, can you assign me also ?

**Comment by Piumal1999** [comment]
Hi @SamikshaSankar, any update on the this?

**Comment by YoshithaRathnayake** [comment]
Can you assign me @Piumal1999 ?
