### ISSUE TITLE
Align the Success Stories page in mobile

### ISSUE THREAD

**Issue by dave-v0** [sef-global/sef-site#1231]
**Describe the bug**
Currently, the Success Stories page is not properly aligned in the mobile view

**To Reproduce**
1. Go to 'https://sefglobal.org/success_stories/'
4. See an error

**Expected behavior**
The page is supposed to be center aligned in mobile view

**Screenshots**
![image](https://user-images.githubusercontent.com/104125359/193418220-90f2b22c-652b-4a7f-a419-1a26e812272b.png)

**Are you working on it?**
Yes

**Comment by Madhawa97** [comment]
Hi @DilinaBandara. Have you tried refreshing afterwards?

**Comment by dave-v0** [comment]
Hi @Madhawa97 yes I did, it is properly right now
![image](https://user-images.githubusercontent.com/104125359/193419988-6d53d0c9-481e-4ee0-ac60-7dd878ff5581.png)

Are you supposed to have the option to have more spacing in the right when dragging the page to the left?
![image](https://user-images.githubusercontent.com/104125359/193420003-bb324736-d10f-431f-92f0-3c13bef296bf.png)

Can you take a look and let me know please. Thanks

**Comment by Madhawa97** [comment]
@DilinaBandara its not suppose to happen and I can't replicate it when resizing the window. but It happens sometimes if I choose the iPhone 12 dimensions. not all the time though. and With a refresh it get fixed.
![Screenshot 2022-10-01 at 22 36 48](https://user-images.githubusercontent.com/70215958/193420384-e37620e4-fb71-47ab-8a04-5e73612dd0f5.jpg)

**Comment by anjula-sack** [comment]
This seems to happen even if you visit it using the mobile directly. @Madhawa97

**Comment by Madhawa97** [comment]
doesn't happen on Samsung M11 device. @DilinaBandara can you also verify this?

**Comment by dave-v0** [comment]
Couldn't test on M11, but tested on a Nokia 2.3 device, and faced the same issue
![image](https://user-images.githubusercontent.com/104125359/193456259-7530ff54-705d-485b-b193-345fb38df37c.png)

Can you take a look regarding this?

**Comment by Madhawa97** [comment]
Strange. It looks good on M11, Pixel 4a, Xiaomi Note 8 and iPhone 13. But yeah sure. I will further look into it.

**Comment by Madhawa97** [comment]
Hey @DilinaBandara. Came across this exact issue again. Couldn't find what's causing this though.

**Comment by Piumal1999** [comment]
> Hey @DilinaBandara. Came across this exact issue again. Couldn't find what's causing this though.

@Madhawa97 I think this occurs due to the long URLs in the descriptions. Those cannot be broken into 2 lines.

<img width="501" alt="image" src="https://user-images.githubusercontent.com/27498587/195285262-d0b16e3d-33b8-4afd-bea6-895f7ed7eeeb.png">

**Comment by Madhawa97** [comment]
Any common/ recommended method to make to broken into 2 lines? @Piumal1999 
Or its better if we can detect if there is a url and render it as a hyperlink. looks better as well as functional.

**Comment by Piumal1999** [comment]
Maybe something like this? Is it possible to do with the data on the google sheet?

Example:
<img width="789" alt="image" src="https://user-images.githubusercontent.com/27498587/195286803-c5318443-9ba7-403e-8f98-30ff74ed195a.png">
⬇️
<img width="789" alt="image" src="https://user-images.githubusercontent.com/27498587/195287151-df5fb79e-819f-4d05-b4d9-db880ea07049.png">

**Comment by Madhawa97** [comment]
Yes. It's successful. need a small change in the code though. Otherwise it renders with the anchor tag. Shall I create an issue and assign @geethaka-Nrs for this? Or I'm not sure if we can reopen this issue again @Piumal1999

**Comment by Piumal1999** [comment]
> Shall I create an issue and assign @geethaka-Nrs for this?

Yeah, sure
