### ISSUE TITLE
Edit spacing in text of Success Stories page

### ISSUE THREAD

**Issue by dave-v0** [sef-global/sef-site#1234]
**Describe the bug**
There is unwanted spacing in the text on the Success Stories page

**To Reproduce**
1. Go to 'https://sefglobal.org/success_stories/'

**Screenshots**
![image](https://user-images.githubusercontent.com/104125359/193418838-eb2620e3-f858-4b31-8f82-2ab038e77b2b.png)

**Are you working on it?**
Yes

**Comment by yogesh-9999** [comment]
hey @anjula-sack please assign me this issue
