### ISSUE TITLE
Add more spacing between topics and buttons in dev page

### ISSUE THREAD

**Issue by dave-v0** [sef-global/sef-site#1236]
**Describe the bug**
There is less space between topics and buttons whereas it is very close to each other

**To Reproduce**
1. Go to 'https://sefglobal.org/devpage.html'

**Expected behavior**
There should be more spacing between topics and buttons

**Screenshots**
![image](https://user-images.githubusercontent.com/104125359/193419467-bbd0d972-71c1-49c7-995d-b7ae42e4d444.png)

**Are you working on it?**
Yes

**Comment by yogesh-9999** [comment]
Hey @DilinaBandara please assign this issue to me
