### ISSUE TITLE
Add a loading skeleton to success stories page

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#1238]
**Is your feature request related to a problem? Please describe.**
On the success stories page, It takes a few seconds to get the content through the API, render it using mustache and display it on the page. We can display some kind of animation until the content is rendered properly.

**Describe the solution you'd like**
Display a loading skeleton until the loading is completed.
Examples: 
loading animation on https://sefglobal.org/team

**Describe alternatives you've considered**
N/A

**Additional context**
Suggest a design by commenting it on here.
Get it approved **before** start developing.

**Are you working on it?**
No

**Comment by Madhawa97** [comment]
I would like to work on this @Piumal1999
