### ISSUE TITLE
Add "Success Stories" page link in drop down menu

### ISSUE THREAD

**Issue by dave-v0** [sef-global/sef-site#1247]
**Is your feature request related to a problem? Please describe.**
Currently, we cannot access the success stories page since there is no link available to visit in the website

**Describe the solution you'd like**
Add  Success stories page link to the drop-down menu

**Describe alternatives you've considered**
Add a Success stories page link to the drop-down menu

**Are you working on it?**
Yes

**Comment by dave-v0** [comment]
Can you please assign me @anjula-sack

**Comment by Madhawa97** [comment]
Hi Dilina. I was assigned to this in the previous stand up. We decided to add it to the ScholarX page instead of adding it on the navigation menu.

**Comment by dave-v0** [comment]
@Madhawa97 Sure Madhawa, not a problem :)
