### ISSUE TITLE
Update the slack invitation link

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#1248]
**Describe the bug**
The current slack invitation link has expired. Please update it with the following link: https://join.slack.com/t/sefheadquarters/shared_invite/zt-1h5zt3go4-wnRDDpecbWiTdpDv1VUoVg

**Places to update**
- [ ] Menu (Join us > slack)
- [ ] Footer 

**Are you working on it?**
No

**Comment by Madhawa97** [comment]
I would like to work on this @jayasanka-sack

**Comment by RandilaP** [comment]
Can i work on this
