### ISSUE TITLE
Update Scholar X timeline

### ISSUE THREAD

**Issue by dave-v0** [sef-global/sef-site#1253]
**Is your feature request related to a problem? Please describe.**
The Scholar X timeline has not been updated

**Describe the solution you'd like**
Changing the indicated to the necessary date

**Describe alternatives you've considered**
Adding the colored indicator to the necessary date

**Additional context**
![image](https://user-images.githubusercontent.com/104125359/193731693-5bdcc6df-96e8-4a61-b9c7-f8912757b390.png)

**Are you working on it?**
Yes

**Comment by dave-v0** [comment]
Can you assign me to this please @anjula-sack

**Comment by anjula-sack** [comment]
A better solution might be to make it update automatically. @DilinaBandara
