### ISSUE TITLE
Align the links properly in footer in Mobile view

### ISSUE THREAD

**Issue by dave-v0** [sef-global/sef-site#1254]
**Describe the bug**
Currently, the links in the footer is not properly aligned in the mobile view

**To Reproduce**
1. Go to 'https://sefglobal.org/'
2. See error

**Expected behavior**
The links in the footer should be aligned properly

**Screenshots**
![image](https://user-images.githubusercontent.com/104125359/193732734-f4670f36-257a-4282-9200-24b1f0436e1a.png)

**Are you working on it?**
Yes

**Comment by anjula-sack** [comment]
Thank you @DilinaBandara for identifying this bug, but there's an issue for this already https://github.com/sef-global/sef-site/issues/1207
