### ISSUE TITLE
Add suitable icons to mobile view navbar

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#1257]
**Is your feature request related to a problem? Please describe.**
In the mobile view navbar, 3 items have the same icon. (About us, initiatives, join us). Replace those with suitable icons that match with the names.

<img width="465" alt="image" src="https://user-images.githubusercontent.com/27498587/193853057-2648ae36-be3f-4eb2-9656-76c660489bc5.png">

**Describe the solution you'd like**
Add suitable icons. Use fontawesome icons.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Are you working on it?**
No

**Comment by harsitagarwalla187** [comment]
Can i work in this issue?

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?
