### ISSUE TITLE
Change the directory name of the success stories

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#1261]
**Is your feature request related to a problem? Please describe.**
Current URL for ScholarX success stories page like `success_stories`. It needs to be `success-stories`. You can read about this [here](https://www.toro.com/en/brand-manager/brand-applications/digital/website-digital-property-policy/url-naming-best-practices#:~:text=Always%20use%20a%20hyphen%20(%2D),of%20the%20words%20for%20evaluation.).

**Describe the solution you'd like**
- Rename the success stories page directory from `success_stories` to `success-stories`

**Are you working on it?**
No

**Comment by itzwow** [comment]
I would like to work upon it can you kindly assign it to me

**Comment by ashutosh7i** [comment]
i want to work on it, please assign it to me

**Comment by Piumal1999** [comment]
Assigned @itzwow
