### ISSUE TITLE
Add meta tags to the engineering page

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#1262]
**Is your feature request related to a problem? Please describe.**
The engineering page is missing a meta description. We need to add it for better SEO.

**Describe the solution you'd like**
- Add the below description as the meta description

The engineering team is the backbone of the SEF community. This team is saturated with potent young talent who engage in various challenges when it comes to contribution. 

**Are you working on it?**
No

**Comment by itzwow** [comment]
I would like to work on this issue. Can you kindly assign it to me

**Comment by 2201monesh** [comment]
Hey @anjula-sack can you please assign this issue to me
