### ISSUE TITLE
Success Stories page footer thematic break is went down

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-site#1265]
**Describe the bug**
Currently, Success Stories page footer thematic break is went down

**To Reproduce**
1. Go to 'Success Story Page'
3. Scroll down to 'footer'

**Expected behavior**
FIx it like the home page footer

**Screenshots**
Home

![image](https://user-images.githubusercontent.com/97069900/194710882-0ea1b082-e5ad-4cb4-bd68-9c847de40b63.png)

Success Story Page

![image](https://user-images.githubusercontent.com/97069900/194710944-661e1f93-65fe-485f-9503-dcf9c1f4e4ca.png)

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by anjula-sack** [comment]
> Shall I work on this ?

sure

**Comment by YoshithaRathnayake** [comment]
> > Shall I work on this ?
> 
> sure

Thanks @anjula-sack
