### ISSUE TITLE
Increase the margin of the Apply Now button in Join Us Page

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-site#1266]
**Describe the bug**
Currently, the Apply Now button is sticked to the paragraph in the top of the button in Join Us page

**To Reproduce**
1. Go to 'Join Us Page'
3. Scroll down to 'Apply Now Section'

**Expected behavior**
Increase the margin between the button and the paragraph

**Screenshots**
![image](https://user-images.githubusercontent.com/97069900/194712057-eedc9e3a-9ffd-41bd-ab79-c068523f5397.png)

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by anjula-sack** [comment]
> Shall I work on this ?

yeah sure

**Comment by YoshithaRathnayake** [comment]
> > Shall I work on this ?
> 
> yeah sure

Thanks @anjula-sack
