### ISSUE TITLE
The footer icons are sticked in the mobile view

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-site#1267]
**Describe the bug**
Currently, footer icons are sticked together in mobile view (from 419 resolution)

**To Reproduce**
1. Go to 'sef site'
3. Scroll down to 'footer'

**Expected behavior**
Add a margin to fix it

**Screenshots**
![image](https://user-images.githubusercontent.com/97069900/194712887-4ecdf4d1-a566-4ef5-b030-c4d763a6957f.png)

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by Tharindu37** [comment]
I would like to work on this

**Comment by anjula-sack** [comment]
> Shall I work on this ?

I assigned @Tharindu37 cuz you already have two assigned issues

**Comment by YoshithaRathnayake** [comment]
> > Shall I work on this ?
> 
> I assigned @Tharindu37 cuz you already have two assigned issues

Ok 👍
