### ISSUE TITLE
Fix the slack and hive link in the nav bar to open in a new window

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-site#1271]
**Is your feature request related to a problem? Please describe.**
Currrently, the slack and the hiv link in the nav bar is opening in the same window

**Describe the solution you'd like**
Fix it to open in another window

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by anjula-sack** [comment]
> Shall I work on this ?

sure
