### ISSUE TITLE
ScholarX 2022 page alignment is off

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/sef-site#1274]
**Describe the bug**
The entire scholarx 2022 page is not aligned center and has a small extra space on the right side of the page.

**To Reproduce**
1. Go to 'https://sefglobal.org/scholarx/2022/'
2. See error

**Expected behavior**
All content should be aligned properly.

**Screenshots**
![Screenshot 2022-10-09 at 15 19 50](https://user-images.githubusercontent.com/70215958/194750222-7e8269e6-d928-4ceb-ae2e-1d5355b99777.jpg)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 105
 

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
I think from #1272 issue it is fixing @anjula-sack

**Comment by YoshithaRathnayake** [comment]
So shall I do this from my issue ?
