### ISSUE TITLE
Move scholarx success stories folder inside the scholax folder

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/sef-site#1275]
**Is your feature request related to a problem? Please describe.**
The scholax `success-stories` folder should be inside of the scholax folder so that the url will be displayed as `https://sefglobal.org/scholarx/success-stories/`

**Describe the solution you'd like**
move the `succes-stories` folder from root to the `scholarx` folder. and update the access url on the `scholarx 2022` page

**Are you working on it?**
No. (I will invite a friend, Actually)

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by YoshithaRathnayake** [comment]
please assign this issue to me
