### ISSUE TITLE
Fix thematic break styles removed with #1268

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/sef-site#1276]
**Describe the bug**
The hr tag (thematic break) on the story card takes so much space and their previous styles has been removed with the #1268 

**To Reproduce**
1. Go to 'https://sefglobal.org/success-stories/'
2. Scroll down to a card
3. See error

**Expected behavior**
The hr tag on the card should not intervene with hr tag on the footer.

**Screenshots**
![Screenshot 2022-10-09 at 16 05 15](https://user-images.githubusercontent.com/70215958/194752008-51507ec0-6110-46a3-ad8c-d3c051a9dabc.jpg)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 -  Version Latest

**Are you working on it?**
No. (Invited a friend)

**Comment by Madhawa97** [comment]
Hi @anjula-sack Can you not assign me. I invited a friend.

**Comment by YoshithaRathnayake** [comment]
So if you are not working on this shall I work on this?

**Comment by YoshithaRathnayake** [comment]
That's a bug made myself no so I will fix it myself. Is it ok @anjula-sack and @Madhawa97 ?

**Comment by Madhawa97** [comment]
It's okay @YoshithaRathnayake. I'm trying to get new collaborators involved with SEF.

**Comment by geethaka-Nrs** [comment]
I was invited by Madhawa. Can you assign me, please

**Comment by YoshithaRathnayake** [comment]
> It's okay @YoshithaRathnayake. I'm trying to get new collaborator involved with SEF.

Ok 👍 I will give him the chance

**Comment by Piumal1999** [comment]
> I was invited by Madhawa. Can you assign me, please

Sure. Assigned @geethaka-Nrs.

**Comment by YoshithaRathnayake** [comment]
@Piumal1999 better if you put the hacktoberfest tag also right?
