### ISSUE TITLE
Make the blog and the handbook links in the navbar to open in another window

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-site#1281]
**Is your feature request related to a problem? Please describe.**
Currently, the blog and the handbook links in the navbar are opening in the same window

**Describe the solution you'd like**
Make the blog and the handbook links in the navbar to open in another window

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by jayasanka-sack** [comment]
I think it's okay to open the handbook from the same window.  @anjula-sack @Piumal1999 What do you think about the blog?

**Comment by YoshithaRathnayake** [comment]
> I think it's okay to open the handbook from the same window. @anjula-sack @Piumal1999 What do you think about the blog?

@anjula-sack told it's ok @jayasanka-sack

**Comment by YoshithaRathnayake** [comment]
> I think it's okay to open the handbook from the same window. @anjula-sack @Piumal1999 What do you think about the blog?

@Piumal1999 ?

**Comment by anjula-sack** [comment]
> I think it's okay to open the handbook from the same window. @anjula-sack @Piumal1999 What do you think about the blog?

I think it's better to open external links in a new window.

**Comment by YoshithaRathnayake** [comment]
> > I think it's okay to open the handbook from the same window. @anjula-sack @Piumal1999 What do you think about the blog?
> 
> I think it's better to open external links in a new window.

@anjula-sack can you assign me for this also?

**Comment by Madhawa97** [comment]
I also think opening `blog` and `handbook` links in a different tab would be better. From UX wise and also because of the different headers etc. @jayasanka-sack

**Comment by YoshithaRathnayake** [comment]
Can any one assign me please?

**Comment by Madhawa97** [comment]
How about if we assign these smaller issues for the newcomers?

**Comment by YoshithaRathnayake** [comment]
> How about if we assign these smaller issues for the newcomers?

I think I won't able to work on #1466 #1441 like issues if you can, pls assign them for others bcs I am still learning and hard to do that for me. I want a help to do that. Pls assign this for me @Madhawa97

**Comment by Madhawa97** [comment]
Well, no worries @YoshithaRathnayake I can unassign you if you say so. But you can take your time and give those a try. I think you weren't that far away with the #1441.

**Comment by YoshithaRathnayake** [comment]
> Well, no worries @YoshithaRathnayake I can unassign you if you say so. But you can take your time and give those a try. I think you weren't that far away with the #1441.

Yeah yeah I thought its an good experience if I do that therefore I will work on it @Madhawa97
