### ISSUE TITLE
Change the background color of the success-stories section of ScholarX 2022 page

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/sef-site#1284]
**Is your feature request related to a problem? Please describe.**
The `success-stories` section on the `scholarx 2022` page is not highlighted.

**Describe the solution you'd like**
The `success-stories` section on the `scholarx 2022` page should have a different background color (background-color: #f4f5f7;), so that the users can clearly  identify the section separately.
![Screenshot 2022-10-09 at 17 16 31](https://user-images.githubusercontent.com/70215958/194764644-1c82ea85-6488-4020-8a0b-2778c5a46c85.jpg)

**Are you working on it?**
No. @geethaka-nrs will work on this.

**Comment by geethaka-Nrs** [comment]
I'd like to work on this issue

**Comment by anjula-sack** [comment]
> I'd like to work on this issue

Go ahead @geethaka-Nrs
