### ISSUE TITLE
Font in the success stories seems to be different in Safari

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#1285]
**Describe the bug**
- Font in the success stories seems to be different in Safari

**To Reproduce**
1. Go to the [success stories](https://sefglobal.org/success-stories/) page in safari
2. Go to the [success stories](https://sefglobal.org/success-stories/) page in chrome
3. See the difference in fonts

**Expected behavior**
The font should be same as in chrome

**Screenshots**
- Chrome 
<img width="415" alt="image" src="https://user-images.githubusercontent.com/43912578/194765040-2349bc78-42fc-4e2b-883d-c2528803ce9e.png">

- Safari
![image](https://user-images.githubusercontent.com/43912578/194765065-c67319df-f56d-4248-9f56-3575206e2898.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser - Chrome

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: IOS 16
 - Browser: Safari
 
**Are you working on it?**
No

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by anjula-sack** [comment]
> Shall I work on this ?

I don't think you'll be able to reproduce this since it happens on safari. Are you using a mac?

**Comment by YoshithaRathnayake** [comment]
> > Shall I work on this ?
> 
> I don't think you'll be able to reproduce this since it happens on safari. Are you using a mac?

Yes I thought that bcs I don't have mac

**Comment by anjula-sack** [comment]
> > > Shall I work on this ?
> > 
> > 
> > I don't think you'll be able to reproduce this since it happens on safari. Are you using a mac?
> 
> Yes I thought that bcs I don't have mac

yeah let's leave it to someone else

**Comment by YoshithaRathnayake** [comment]
> > > > Shall I work on this ?
> > > 
> > > 
> > > I don't think you'll be able to reproduce this since it happens on safari. Are you using a mac?
> > 
> > 
> > Yes I thought that bcs I don't have mac
> 
> yeah let's leave it to someone else

yeah sure

**Comment by anjula-sack** [comment]
@Madhawa97 any idea about this?

**Comment by Madhawa97** [comment]
give me 20mins. I have to try something new I found earlier. So far even I try specify the style for the webkit, it changed on the both browsers.

**Comment by Madhawa97** [comment]
Hi @anjula-sack. Just tried adding;
`@media screen and (-webkit-min-device-pixel-ratio:0) {
    .story-section .highlight {
        color: red;
    }
}
`
but it still updates both browsers. Do you happen to know any other method?

**Comment by Madhawa97** [comment]
@geethaka-Nrs would you like to work on this? we can get rid of the bold styling which make the view from both browsers identical. It looks good as well. 
![Screenshot 2022-10-14 at 22 34 44](https://user-images.githubusercontent.com/70215958/195903585-0fefc2a9-7cc1-4e31-8300-a9d8724087cd.jpg)

**Comment by geethaka-Nrs** [comment]
Yeah sure. Can you assign me please
