### ISSUE TITLE
Success story card header text shouldn't be justified

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#1286]
**Is your feature request related to a problem? Please describe.**
Success story card header text shouldn't be justified

<img width="378" alt="image" src="https://user-images.githubusercontent.com/43912578/194765420-35ca2c3d-bfee-4a8d-bd76-24f42574da78.png">

**Describe the solution you'd like**
- Remove ` text-align: justify;` from the story card header

**Are you working on it?**
No

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by anjula-sack** [comment]
> Shall I work on this ?

sure
