### ISSUE TITLE
There is no gap between social icons in the footer, on mobile devices

### ISSUE THREAD

**Issue by sathmikaDev** [sef-global/sef-site#1289]
**Describe the bug**
There is no gap between social icons in the footer, on mobile devices.

**To Reproduce**
1. Go to https://sefglobal.org/
2. Click on inspect elements
3. Scroll down to the footer

**Expected behavior**
set a y axis margin

**Screenshots**
![footer-icons](https://user-images.githubusercontent.com/99987075/194768501-bae99cf7-d528-4e35-bb9c-a3afb9f880a4.PNG)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser google chrome
 - Version 106.0.5249.103

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
I think it's fixing from #1269 PR @Sathmikasenadheera01

**Comment by sathmikaDev** [comment]
ah yes !
