### ISSUE TITLE
Fix colliding of buttons in Engineering Team pages mobile view 

### ISSUE THREAD

**Issue by VishwaAmarasinghe** [sef-global/sef-site#1294]
**Describe the bug**
The view in github button and the open project button collide together in the engineering team page mobile view.

**To Reproduce**
1. Go to 'https://sefglobal.org/devpage.html'
2. Scroll down to '....'
3. See error

**Expected behavior**
The button shouldn't collide. The open project button should go down.

**Screenshots**
![image](https://user-images.githubusercontent.com/90438593/195061677-c8f6a47d-05d6-4378-9274-09a6acabcc0d.png)

**Desktop (please complete the following information):**
 - OS:Windows
 - Browser :Chrome

**Additional context**
N/A

**Are you working on it?**
Yes

**Comment by Anurag-Singh-04** [comment]
Hey @Piumal1999 I would like to work on this issue. Can you please assign this to me.
