### ISSUE TITLE
Add a thematic break to navbar

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-site#1295]
**Is your feature request related to a problem? Please describe.**
Currently, the difference between the navbar and the body can't see.

**Describe the solution you'd like**
Add a thematic break to navbar, like `academix` page

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by YoshithaRathnayake** [comment]
Tell me your suggestions for this. Is it good @anjula-sack @Piumal1999 @jayasanka-sack @Gravewalker666

**Comment by YoshithaRathnayake** [comment]
How about this ?

![image](https://user-images.githubusercontent.com/97069900/195092363-ba0b16c4-9a90-4319-ab43-efa4f84d76db.png)

**Comment by anjula-sack** [comment]
> How about this ?
> 
> ![image](https://user-images.githubusercontent.com/97069900/195092363-ba0b16c4-9a90-4319-ab43-efa4f84d76db.png)

I feel like it's not required. WDYT @jayasanka-sack @Piumal1999 ?

**Comment by jayasanka-sack** [comment]
Yes @anjula-sack, I feel the same. 
Anyway, many thanks to @YoshithaRathnayake as usual! We are delighted to have you on board! <3

**Comment by YoshithaRathnayake** [comment]
> Yes @anjula-sack, I feel the same. Anyway, many thanks to @YoshithaRathnayake as usual! We are delighted to have you on board! <3

👍
