### ISSUE TITLE
ReadMe.LK link on press coverage section is not working

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#1297]
**Describe the bug**
The ReadME.lk post about SEF is no longer there. The link redirects to a 404 error page.

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/27498587/195114618-bf097444-ee82-4e11-abdc-9d284417737e.png">

<img width="1455" alt="image" src="https://user-images.githubusercontent.com/27498587/195114737-2e422629-6541-46de-be91-a3316be1582b.png">

**To Reproduce**
1. Go to Homepage
2. Go to `Press Coverage` section
3. Click on `README.lk` logo

**Expected behavior**
N/A

**Additional context**
N/A

**Are you working on it?**
No

**Comment by Piumal1999** [comment]
@jayasanka-sack @anjula-sack Shall we just remove that logo? 
Are there any other articles suitable for the press coverage section?

**Comment by anjula-sack** [comment]
> @jayasanka-sack @anjula-sack Shall we just remove that logo? Are there any other articles suitable for the press coverage section?

If the article is not existing we can remove it. 
cc: @akshika47

**Comment by Tharindu37** [comment]
I would like to work on this

**Comment by anjula-sack** [comment]
> I would like to work on this

sure go ahead.

**Comment by jayasanka-sack** [comment]
I think it's okay to replace the link with https://readme.lk/ instead of removing the logo. 

@Piumal1999 @anjula-sack

**Comment by RandilaP** [comment]
May I work on this

**Comment by Piumal1999** [comment]
Update: We need to remove the link because the post is no longer there on the readme.lk site

**Comment by Madhawa97** [comment]
shall I do it?

**Comment by anjula-sack** [comment]
> shall I do it?

sure, @Madhawa97

**Comment by Nelka97** [comment]
Can I work on this?

**Comment by Madhawa97** [comment]
Sure @Nelka97. Please go ahead
