### ISSUE TITLE
Hero section of Join Us page is not well aligned

### ISSUE THREAD

**Issue by sathmikaDev** [sef-global/sef-site#1298]
**Describe the bug**
Hero section of Join Us page is not well aligned both mobile and large screens.

**To Reproduce**
1. Go to https://sefglobal.org/join-us.html
2. Click on inspect elements
3. See error

**Expected behavior**
Components in the hero section should be well aligned and responsive

**Screenshots**

*Desktop view*

![3dkgd1Efz1](https://user-images.githubusercontent.com/99987075/195127571-8b7ecb8c-9dbb-4bb1-8232-9156596f8126.png)

*mobile view*

![chrome_nVld9WaUMl](https://user-images.githubusercontent.com/99987075/195127592-5887e12a-6097-4109-9afb-bf07cd64c9b2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser google chrome
 - Version 106

**Are you working on it?**
Yes

**Comment by Piumal1999** [comment]
Assigned @Sathmikasenadheera01
