### ISSUE TITLE
Increase the gap between the image and the topic in the `Sign Up as a Researcher` Section at the IRC Page

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-site#1302]
**Is your feature request related to a problem? Please describe.**
Currently, in the mobile view the gap between the image and the topic in the `Sign Up as a Researcher` Section of IRC page in less and its like sticked

**Describe the solution you'd like**
Add a margin to one of them

**Screenshots**
![image](https://user-images.githubusercontent.com/97069900/195147734-11f41119-1c30-4873-9a55-68feca395924.png)

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by RandilaP** [comment]
May I work on this

**Comment by YoshithaRathnayake** [comment]
> May I work on this

Please, I will work on this ok?

**Comment by anjula-sack** [comment]
> > May I work on this
> 
> Please, I will work on this ok?

Go ahead
