### ISSUE TITLE
Reduce the width of "Our mentors and speakers are from" section

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#1305]
**Is your feature request related to a problem? Please describe.**
The "Our mentors and speakers are from" section is a bit longer than the other sections of the sef-site homepage. (In larger screen sizes)

<img width="1405" alt="image" src="https://user-images.githubusercontent.com/27498587/195255871-719da5eb-1a3c-4859-9100-ac5b46d9e6ef.png">

**Describe the solution you'd like**
The width should be equal to the default container width.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Are you working on it?**
No

**Comment by Konara98** [comment]
shall i work on this?

**Comment by YoshithaRathnayake** [comment]
> shall i work on this?

Are you still working on this? if not I will work on this @Konara98 ?

**Comment by Konara98** [comment]
Still working on it. i'll open a pull request soon.

**Comment by YoshithaRathnayake** [comment]
> Still working on it. i'll open a pull request soon.

Ok
