### ISSUE TITLE
Update the mustache template to display hyperlinks on SX Success Stories page

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/sef-site#1306]
**Is your feature request related to a problem? Please describe.**
Currently there are few URLs displayed in the scholarx success stories page. We need to display them inside a hyperlink.

**Describe the solution you'd like**
Update the google sheet and update the mustache template to display the hyperlinks.

**Additional context**
This issue was initially discovered by @DilinaBandara with #1231 

**Are you working on it?**
No. @geethaka-Nrs will work on this.

**Comment by geethaka-Nrs** [comment]
I'd like to work on this
