### ISSUE TITLE
Make discourse icon look similar to other icons in navbar

### ISSUE THREAD

**Issue by VishwaAmarasinghe** [sef-global/sef-site#1308]
**Is your feature request related to a problem? Please describe.**
The discourse icon in the navbar does not look similar to other icons because the discourse icon's background colour should be the colour of the discourse icon's color and the background colour should be white colour.

**Describe the solution you'd like**
Make changes to css file by changing colour code.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Are you working on it?**
Yes

**Comment by VishwaAmarasinghe** [comment]
Shall I work on this?

**Comment by Piumal1999** [comment]
Sure @VishwaAmarasinghe

**Comment by VishwaAmarasinghe** [comment]
Thank you @Piumal1999
