### ISSUE TITLE
Fix the alignments in the All Pages breaking from the navbar

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-site#1310]
**Describe the bug**
The alignments in the body of the All Pages are ugly. The problem is in the navbar.

**To Reproduce**
1. Go to 'All Pages'

**Expected behavior**
Fix the alignments in the Navbar

**Screenshots**
Engineering Team Page
![image](https://user-images.githubusercontent.com/97069900/195972546-9dcb92bd-1e47-4986-b0c5-4d3098a9beab.png)

Upspeak
![image](https://user-images.githubusercontent.com/97069900/195972487-4a8c6d4f-e414-42b6-9dbd-09d356d397c5.png)

IRC
![image](https://user-images.githubusercontent.com/97069900/195972519-371ddf46-5e16-4c09-ad13-c059f7d9bebe.png)

ScholarX
![image](https://user-images.githubusercontent.com/97069900/195972594-c773016c-a57b-43c2-b9cd-06a521544e6a.png)

Student Ambassador
![image](https://user-images.githubusercontent.com/97069900/195972617-12a1b211-3171-420d-86d1-9515fde39117.png)

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by YoshithaRathnayake** [comment]
@anjula-sack can you assign me for this issue?

**Comment by YoshithaRathnayake** [comment]
@Piumal1999  can you assign me for this issue?

**Comment by Piumal1999** [comment]
Hi @YoshithaRathnayake, I couldn't reproduce this error. In which screen sizes does this occur?

**Comment by YoshithaRathnayake** [comment]
> Hi @YoshithaRathnayake, I couldn't reproduce this error. In which screen sizes does this occur?

992 resoluyion upwards in mentioned sites (above) @Piumal1999 . See the footer area you will be able to find the bug

**Comment by Piumal1999** [comment]
Ah right. Assigned @YoshithaRathnayake

**Comment by YoshithaRathnayake** [comment]
> Ah right. Assigned @YoshithaRathnayake

Thanks @Piumal1999
