### ISSUE TITLE
Reduce the gap between the button and the topic in the IRC Page

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-site#1314]
**Is your feature request related to a problem? Please describe.**
The gap between the sign up button and the topic of the `Sign up as a Researcher` section in IRC Page is increased and it seems like the sign up button isn't belongs to the Sign up as a Researcher section

**Describe the solution you'd like**
Reduce the gap between the button and the topic in the IRC Page

**Screenshots**
![image](https://user-images.githubusercontent.com/97069900/195834363-be9917e5-a141-447d-8e72-690261b8a9ae.png)

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by anjula-sack** [comment]
> Shall I work on this ?

sure go ahead
