### ISSUE TITLE
"text-justified" class have made unnecessary spaces

### ISSUE THREAD

**Issue by sathmikaDev** [sef-global/sef-site#1316]
**Describe the bug**
In the home page, some sections have used `text-justified` class with `<p>` tags. It has created unnecessary spaces between words.

**To Reproduce**
1. Go to https://sefglobal.org/
2. Scroll down to our journey so far section
3. See error

**Expected behavior**
`text-justify` class should be replaced with `text-left` or `text-right`.

**Screenshots**
![y1AGPWLn1u](https://user-images.githubusercontent.com/99987075/195866976-02d70ec1-690f-4e53-9168-925d4ec9a6cc.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 106

**Are you working on it?**
Yes

**Comment by sathmikaDev** [comment]
Hi, @Piumal1999 I'd like to work in this

**Comment by Piumal1999** [comment]
@anjula-sack WDYT? Did we use the justify alignment intentionally?

**Comment by anjula-sack** [comment]
> @anjula-sack WDYT? Did we use the justify alignment intentionally?

I don't think so let's remove it

**Comment by anjula-sack** [comment]
> Hi, @Piumal1999 I'd like to work in this

Go ahead @Sathmikasenadheera01

**Comment by sathmikaDev** [comment]
> > Hi, @Piumal1999 I'd like to work in this
> 
> Go ahead @Sathmikasenadheera01

🙌🙌

**Comment by Madhawa97** [comment]
It was intentional initially, but yeah if it looks better without the justifying you can remove it. Try the css builtin `text-align: justify` property as well. It's a bit different from the one from the bootstrap. @Sathmikasenadheera01

**Comment by sathmikaDev** [comment]
> It was intentional initially, but yeah if it looks better without the justifying you can remove it. Try the css builtin `text-align: justify` property as well. It's a bit different from the one from the bootstrap. @Sathmikasenadheera01

I'll try it. 🙌

**Comment by sathmikaDev** [comment]
> > It was intentional initially, but yeah if it looks better without the justifying you can remove it. Try the css builtin `text-align: justify` property as well. It's a bit different from the one from the bootstrap. @Sathmikasenadheera01
> 
> I'll try it. 🙌
![kMyrPgxuT9](https://user-images.githubusercontent.com/99987075/195889393-36bb6a65-a61f-4152-87e4-16b86cd03a5b.png)

@Madhawa97  I think it's also same as before
