### ISSUE TITLE
Adjust gap between press coverage logos in mobile view

### ISSUE THREAD

**Issue by RandilaP** [sef-global/sef-site#1317]
**Describe the bug**
In mobile view press coverage section logos has to increase the gap between them.

**Screenshots**
![image](https://user-images.githubusercontent.com/106733522/195868087-e6c34913-8b29-409b-9c0b-b12dcead2bfc.png)

**Are you working on it?**
Yes

**Comment by RandilaP** [comment]
@anjula-sack @jayasanka-sack May I work on this

**Comment by anjula-sack** [comment]
@RandilaP are you working on this?

**Comment by YoshithaRathnayake** [comment]
> @RandilaP are you working on this?

If he isn't working on this, shall I ? @anjula-sack
