### ISSUE TITLE
Blog : Page load optimization 

### ISSUE THREAD

**Issue by bpdesilva** [sef-global/sef-site#132]
Blog articles take up to 40 seconds to load need to speed this up.

- [ ] Increase the speed in which the articles are loaded.
- [ ] Fit the content into the template in the most suitable method.

**Comment by akshika47** [comment]
@Piumal1999, Until we have a way to do this task. Please link our medium blog (https://medium.com/@SustainableEduF) instead of the existing Blog page cos it does not look pretty.
