### ISSUE TITLE
Editing grammar and punctuation in the Success Stories Page

### ISSUE THREAD

**Issue by dave-v0** [sef-global/sef-site#1322]
**Is your feature request related to a problem? Please describe.**
I'd like to professionally edit the grammar and punctuation in the success stories page

**Describe the solution you'd like**
Adding in and changing grammatical-based requirements

**Are you working on it?**
No

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by miniskynet** [comment]
The grammar and punctuation errors have been fixed
https://docs.google.com/spreadsheets/d/1uHklcBq5KD21Qoz_sYvwUO6qn_297hxVIN0MkF8zUxs/edit#gid=0
