### ISSUE TITLE
The button in the Become one of the Volunteers in the home page is sticked to the topic

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-site#1327]
**Describe the bug**
The button in the Become one of the Volunteers in the home page is sticked to the topic

**To Reproduce**
1. Go to 'Sef Site'
3. Scroll down to 'Become one of the Volunteers Section'

**Expected behavior**
Increase the margin of the button

**Screenshots**
![image](https://user-images.githubusercontent.com/97069900/195973878-acbb3bcd-798d-4e19-ab6e-8874cee1175d.png)

**Are you working on it?**
Yes

**Comment by super-duper-sp** [comment]
Please, assign this issue to me. I would like to work on this.

**Comment by YoshithaRathnayake** [comment]
> Please, assign this issue to me. I would like to work on this.

Pls, I will work on this ok? @super-duper-sp
