### ISSUE TITLE
Add the leader board link to SEF site nav bar

### ISSUE THREAD

**Issue by miniskynet** [sef-global/sef-site#1328]
**Is your feature request related to a problem? Please describe.**
The SEF site navbar does not have an option to navigate to the leaderboard 

**Describe the solution you'd like**
Add an option on navigation bars 'join us' dropdown to navigate to the leaderboard

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
I would like to work on this

**Comment by YoshithaRathnayake** [comment]
pls assign me @miniskynet

**Comment by miniskynet** [comment]
oh I saw this now @YoshithaRathnayake . I was already working on this. Sorry about that.

**Comment by YoshithaRathnayake** [comment]
> oh I saw this now @YoshithaRathnayake . I was already working on this. Sorry about that.

OK @miniskynet
