### ISSUE TITLE
Website Changes

### ISSUE THREAD

**Issue by akshika47** [sef-global/sef-site#133]
Let's keep this issue as the main issue covering all the changes that needs to happen to the website. 

Please add the changes the have you in your mind as comments, so we can create individual issues out of them.

I will be editing the description according to the comments.

NP - Not a High Priority 

| Section | Description | Issue number |
| ------------- | ------------- | ------------- |
| All Pages | Github links needs to be added | NP |
| Home Page | Testimonial heights are un-even | - |
| Team Page | New Team needs to be added | - |
| Alumni Page | Alumni needs to be added | - |
| OneLive Page | All the OneLive speakers needs to be added | - |
| OneLive Page |  Spelling checks needs to be done | - |
| Careers Page | Separate page needs to be added for careers | - |
| IRC Page | Create a page for "IRC" | #145 , #104 |
| IRC Page | Link the Signup form | #165  |
| Blog Page | Make it nice  | #132  |
| New Page | Create a new page for 'Press' and possibly add it under About section  | - |
| New Page | Create a new page for media/resources, things like logos and logo guidelines could be hosted here  | - |

**Comment by tsuresh** [comment]
@jayasanka-sack Please close the finished issues

**Comment by Piumal1999** [comment]
only admins can edit this?
@jayasanka-sack

**Comment by akshika47** [comment]
I added you as an admin @Piumal1999

**Comment by akshika47** [comment]
@Piumal1999 You  can hyperlink the issue number to the issue itself.
