### ISSUE TITLE
Align the icons center in the Our Mentors And Speakers Are From Section in the mobile view

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-site#1330]
**Describe the bug**
The icons in the Our Mentors And Speakers Are From Section are aligned to right in mobile view

**To Reproduce**
1. Go to 'SEF SITE'
3. Scroll down to 'Our Mentors And Speakers Are From'

**Expected behavior**
Align the icons center in the Our Mentors And Speakers Are From Section in the mobile view

**Screenshots**
![image](https://user-images.githubusercontent.com/97069900/195984225-b0e6566d-28eb-4e78-9954-66206269bdcf.png)

**Are you working on it?**
Yes

**Comment by Tharindu37** [comment]
I would like to work on this

**Comment by YoshithaRathnayake** [comment]
> I would like to work on this

Please, I will work on this @Tharindu37

**Comment by Tharindu37** [comment]
@YoshithaRathnayake Ok

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake Ok

Thank you

**Comment by YoshithaRathnayake** [comment]
@anjula-sack can you assign me to this?

**Comment by anjula-sack** [comment]
> @anjula-sack can you assign me to this?

Go ahead. @YoshithaRathnayake

**Comment by YoshithaRathnayake** [comment]
> > @anjula-sack can you assign me to this?
> 
> Go ahead. @YoshithaRathnayake

Thank you @anjula-sack
