### ISSUE TITLE
Fix the alignment of the upspeak page's tablet view

### ISSUE THREAD

**Issue by VishwaAmarasinghe** [sef-global/sef-site#1336]
**Describe the bug**
The alignment of the Upspeak page's tablet view is ugly because there is lot of space above and below the image. Also, the text is aligning to the left side of the page so much.

**To Reproduce**
1. Go to 'https://sefglobal.org/upspeak/'
2. Click on 'inspect'
3. Scroll down 

**Expected behavior**
It should look like what we see in the mobile view.

**Screenshots**
![image](https://user-images.githubusercontent.com/90438593/196013837-004b1555-50de-4103-b9f9-d4d25431ee64.png)
![image](https://user-images.githubusercontent.com/90438593/196013842-70d9ac13-c8e1-4c95-b1a8-74725c6278ac.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome

**Additional context**
N/A

**Are you working on it?**
Yes

**Comment by VishwaAmarasinghe** [comment]
Shall I work on this?

**Comment by anjula-sack** [comment]
> Shall I work on this?

Go ahead @VishwaAmarasinghe

**Comment by VishwaAmarasinghe** [comment]
Thanks @anjula-sack
