### ISSUE TITLE
Remove the duplicate footer element and restructure the code

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#1339]
**Is your feature request related to a problem? Please describe.**
This is the footer we currently use. It contains 2 footer elements.
<img width="675" alt="image" src="https://user-images.githubusercontent.com/27498587/196085608-ec3d61c6-de02-4079-a01f-d713bce08f5f.png">

The code of the footer can be improved by referring to the argon documentation.

**Describe the solution you'd like**
1. Remove the extra footer element
2. Remove the `has-cards` class. (Otherwise, it will be displayed in a different design)

**Describe alternatives you've considered**
N/A

**Additional context**
Refer to the footer of https://demos.creative-tim.com/argon-design-system/examples/landing.html

**Are you working on it?**
No

**Comment by Konara98** [comment]
Shall i work on this issue.
