### ISSUE TITLE
Increase the section paddings of IRC page

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#1340]
**Is your feature request related to a problem? Please describe.**
The bottom padding of the Researchers section and the Interns section of the IRC page is set as zero. So the 2 sections are cluttered.

-
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/27498587/196088973-5d3cbda8-7907-4a6d-9c86-5e556bb727db.png">

-
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/27498587/196088998-15892469-caab-4fee-a789-16884cb26cf8.png">

**Describe the solution you'd like**
Remove the `pb-0` classes. So it can have the default padding size.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Are you working on it?**
No

**Comment by Konara98** [comment]
Shall i work on this

**Comment by YoshithaRathnayake** [comment]
I would like to work on this, can you assign me pls @Piumal1999
