### ISSUE TITLE
Make the sef github leaderboard link in the navbar to open in the same window

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-site#1343]
**Is your feature request related to a problem? Please describe.**
Currently, the sef github leaderboard link in the navbar is opening in a new window

**Describe the solution you'd like**
Make the sef github leaderboard link to open in the same window

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by anjula-sack** [comment]
It's better to open the leaderboard in a separate tab. @YoshithaRathnayake

**Comment by YoshithaRathnayake** [comment]
> It's better to open the leaderboard in a separate tab. @YoshithaRathnayake

Ok @anjula-sack
