### ISSUE TITLE
With the sticky header the `Our Projects` section is sticked to the nav

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-site#1354]
**Describe the bug**
Currently, when I click the explore button in home page its scrolling to the `Our Projects` section and its look likes sticked to the nav bar

**To Reproduce**
1. Go to 'sef-site'
2. Click on 'explore btn'

**Expected behavior**
Add a margin when scrolling to the `Our Projects` section

**Screenshots**
![image](https://user-images.githubusercontent.com/97069900/197347728-5bc8e62e-50c5-442a-954c-f4086d059dcb.png)

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by anjula-sack** [comment]
Now this is fixed with the latest updates to the navbar @YoshithaRathnayake

**Comment by YoshithaRathnayake** [comment]
> Now this is fixed with the latest updates to the navbar @YoshithaRathnayake

Oh yes from the reduction of the padding right? @anjula-sack
