### ISSUE TITLE
With the sticky header the top of the all pages is covered with the navbar

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-site#1355]
**Describe the bug**
Currently, top of the all pages is covered by the navbar bcs of the sticky header

**To Reproduce**
1. Go to 'every page'

**Expected behavior**
Add a margin to the navbar

**Screenshots**
![image](https://user-images.githubusercontent.com/97069900/197347857-109d42b4-a729-46a9-99fd-c60acd6c9ba0.png)

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by anjula-sack** [comment]
> Shall I work on this?

Go ahead. Let's reduce the padding of the navbar as well

**Comment by YoshithaRathnayake** [comment]
> > Shall I work on this?
> 
> Go ahead. Let's reduce the padding of the navbar as well

Sure @anjula-sack
