### ISSUE TITLE
Change the title from 'Featured Stories' to 'Featured Articles' in previous ScholarX programs

### ISSUE THREAD

**Issue by miniskynet** [sef-global/sef-site#1356]
**Describe the bug**
The ScholarX pages in the archive (2019,2020 and 2021) have the title as 'Featured Stories'

**Expected behavior**
The title should change to 'Featured Articles'

**Screenshots**
**Expected look:**
![image](https://user-images.githubusercontent.com/49517852/197375522-67f7f8ad-7f6c-46d0-9eb4-0df3820665d6.png)
**Current state:**
![image](https://user-images.githubusercontent.com/49517852/197375589-b151f479-53c7-4d3a-8419-ba02aeb6ceac.png)

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
I'd like to work on this, can you assign me please? @miniskynet
