### ISSUE TITLE
Remove the "Join the Family" heading in the student ambassador page mobile view

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#1368]
**Is your feature request related to a problem? Please describe.**
- There's a heading on the student ambassador page only in the mobile view. We don't need that heading.

**Describe the solution you'd like**
- Remove the `Join the Family` heading

<img width="416" alt="image" src="https://user-images.githubusercontent.com/43912578/198185418-b21743ff-f4f7-4a59-9e9b-e303f45ccda0.png">

**Are you working on it?**
No

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?
