### ISSUE TITLE
Add meeting links to SEF handbook Engineering page

### ISSUE THREAD

**Issue by miniskynet** [sef-global/sef-site#1373]
**Is your feature request related to a problem? Please describe.**
The [engineering page]([url](https://handbook.sefglobal.org/organisation/engineering-team)) of the SEF Handbook is missing links for general meetings, standups, knowledge sharing sessions, etc

**Describe the solution you'd like**
Include the links for general meetings, standups, knowledge sharing sessions, etc on the [engineering page](https://handbook.sefglobal.org/organisation/engineering-team) of the SEF Handbook

**Are you working on it?**
No

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by anjula-sack** [comment]
This issue needs to be created in the [SEF handbook](https://github.com/sef-global/sef-handbook) repo. But it's okay since it's already created here. @miniskynet

**Comment by YoshithaRathnayake** [comment]
> This issue needs to be created in the [SEF handbook](https://github.com/sef-global/sef-handbook) repo. But it's okay since it's already created here. @miniskynet

So @anjula-sack is it ok if I work on this?

**Comment by miniskynet** [comment]
sorry about that @anjula-sack. Should I close this and open one in the handbook repo?

**Comment by YoshithaRathnayake** [comment]
> sorry about that @anjula-sack. Should I close this and open one in the handbook repo?

I think it is better if you can transfer the issue @miniskynet

**Comment by anjula-sack** [comment]
> sorry about that @anjula-sack. Should I close this and open one in the handbook repo?

No need. @YoshithaRathnayake mention this issue in your PR.
