### ISSUE TITLE
Change the colour of Frequently Asked Questions section in STUDENT AMBASSADOR

### ISSUE THREAD

**Issue by VishwaAmarasinghe** [sef-global/sef-site#1374]
**Is your feature request related to a problem? Please describe.**
The colour of Frequently Asked Questions in STUDENT AMBASSADOR is the colour of the navbar. So it should be different as other sections.

**Describe the solution you'd like**
Change colour of the Frequently Asked Questions section.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Are you working on it?**
Yes

**Comment by VishwaAmarasinghe** [comment]
Shall I work on this?

**Comment by dilankavishka** [comment]
can I work with this?

**Comment by VishwaAmarasinghe** [comment]
Please can I work on this?

**Comment by YoshithaRathnayake** [comment]
Are you still working on this? @VishwaAmarasinghe

**Comment by VishwaAmarasinghe** [comment]
> Are you still working on this? @VishwaAmarasinghe

yeah
