### ISSUE TITLE
Add the blog and the handbook link to the readme.md file

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-site#1376]
**Is your feature request related to a problem? Please describe.**
Currently, the blog and the handbook link are not in the readme.md file

**Describe the solution you'd like**
Add the blog and the handbook link to the readme.md file

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by anjula-sack** [comment]
We can link the handbook only @YoshithaRathnayake

**Comment by YoshithaRathnayake** [comment]
> We can link the handbook only @YoshithaRathnayake

Ok @anjula-sack
