### ISSUE TITLE
Update the scholarX 2022 featured stories

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#1381]
**Is your feature request related to a problem? Please describe.**
We need to update the scholarX 2022 featured stories

**Describe the solution you'd like**
Replace the following places,
1. Update the script link: https://github.com/sef-global/sef-site/blob/80c92f4bdf2e6cdcdf1a68afa972af17328d751a/scholarx/2022/functions.js#L33 

with `https://script.google.com/macros/s/AKfycbxoEfCuQK2x57cHG0HG0YlljD6FoKbIwygdEz0wkt6ex4YAxEviuLdwJbiXKNZwA-k64g/exec`

2. Update the author image link: https://github.com/sef-global/sef-site/blob/2dcf6276cfebefec29fa9232eb671069954b35c2/scholarx/2022/index.html#L674 
with `https://res.cloudinary.com/dsxobn1ln/image/upload/c_scale,h_200,w_200/{{author_image}}`

3. Update the blog image link: https://github.com/sef-global/sef-site/blob/2dcf6276cfebefec29fa9232eb671069954b35c2/scholarx/2022/index.html#L667 
with `https://res.cloudinary.com/dsxobn1ln/image/upload/c_scale,w_400/{{image}}`

**Are you working on it?**
No

**Comment by anjula-sack** [comment]
@YoshithaRathnayake is working on this

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake is working on this

Sure @anjula-sack can you assign me please
