### ISSUE TITLE
Rename check out archive button to past programs

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#1396]
**Is your feature request related to a problem? Please describe.**
- We need to rename this button
<img width="636" alt="image" src="https://user-images.githubusercontent.com/43912578/202881234-1d48f2c8-661d-4731-aa16-fcecbd246320.png">

**Describe the solution you'd like**
- Rename the `Check Out Our ScholarX` button to `Past ScholarX Programs` in  https://sefglobal.org/scholarx/2022/ page

**Are you working on it?**
No

**Comment by anjula-sack** [comment]
@Tharindu37 Can you work on this?

**Comment by Tharindu37** [comment]
@anjula-sack sure
