### ISSUE TITLE
Rename the archive directory to past programs

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#1397]
**Is your feature request related to a problem? Please describe.**
- We need to change the archive as past programs

**Describe the solution you'd like**
- Rename this archive https://github.com/sef-global/sef-site/tree/master/scholarx/archive directory to `past-programs`
- Update all the links that referring that directory as well

**Are you working on it?**
No

**Comment by Tharindu37** [comment]
I would like to work on this
