### ISSUE TITLE
Featured stories author image width issue

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#1399]
**Describe the bug**

**To Reproduce**
1. Go to [Scholarx page](https://sefglobal.org/scholarx/2022/)
2. Scroll down to the Featured stories section
3. See  the author images

**Expected behavior**
- Author image should be a circle

**Screenshots**
<img width="379" alt="image" src="https://user-images.githubusercontent.com/43912578/202887651-2cb9f849-2a64-46bb-a29c-9370c375be6a.png">

**Aditional Information**
- These stories are fetched from an API and populated using a template
- You need to update this template to fix this https://github.com/sef-global/sef-site/blob/99dc496ad4f4f5040d573a856161eb9ab493f78e/scholarx/2022/index.html#L661

**Are you working on it?**
No

**Comment by anjula-sack** [comment]
@Tharindu37 can you work on this?

**Comment by Tharindu37** [comment]
@anjula-sack Sure

**Comment by janithlahirukariyawasam** [comment]
How about this solution @anjula-sack ?
![image](https://user-images.githubusercontent.com/88109775/202892251-675ceb0a-037c-4d7b-aa4e-f0aaa5660a95.png)
