### ISSUE TITLE
Issues when we open the Featured Articles section on different devices.

### ISSUE THREAD

**Issue by janithlahirukariyawasam** [sef-global/sef-site#1402]
**Describe the bug**
There are some bugs when we open the featured articles section on different devices.
( Tab screen > 8.5-inch )

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://sefglobal.org/scholarx/2022/
2. Go to the Featured article section
3. View the section using different screen sizes.

**Expected behavior**
**I believe it is good to use two rows to show both read time and the author of the article.**

**Screenshots**
![Screenshot 2022-11-20 191139gggg](https://user-images.githubusercontent.com/88109775/202908127-55d444b8-f459-4cf7-8f68-ab5b7aa96855.png)

![Screenshot 2022-11-20 192508](https://user-images.githubusercontent.com/88109775/202907947-085d7a06-e238-4557-b213-ce13b956a064.png)
![Screenshot 2022-11-20 193508](https://user-images.githubusercontent.com/88109775/202907962-1ccbdf6e-65ea-42fe-b2b4-270448eca530.png)

**Are you working on it?**
Yes

**Comment by janithlahirukariyawasam** [comment]
Shall I work on this? What is your opinion?

**Comment by anjula-sack** [comment]
> Shall I work on this? What is your opinion?

Thanks for identifying the bug @janithlahirukariyawasam Please go ahead
