### ISSUE TITLE
The header and the footer are not loading on the ScholarX summer 2021 page

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#1406]
**Describe the bug**
- The Header and the footer are not loading on the ScholarX summer 2021 page

**To Reproduce**
1. Go to [ScholarX 2021 Summer page](https://sefglobal.org/scholarx/past-programs/2021-summer/)
2. See the header and footer is missing

**Expected behavior**
- The header and the footer need to be there

**Screenshots**
<img width="1678" alt="image" src="https://user-images.githubusercontent.com/43912578/202987090-4c69c726-d95f-4c20-a8ad-1c351a3835ba.png">
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/43912578/202987138-8983f45f-e541-452e-80d4-c697c10e4b67.png">

**Additional context**
- Check how the header and the footer are being loaded in other pages

**Are you working on it?**
No

**Comment by Tharindu37** [comment]
I would like to work on this

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by anjula-sack** [comment]
> Contributor

Go ahead @Tharindu37
