### ISSUE TITLE
The program timeline is crashed in Scholarx 2021 summer page

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-site#1407]
**Describe the bug**
The program timeline is crashed in Scholarx 2021 summer page

**To Reproduce**
1. Go to https://www.sefglobal.org/scholarx/past-programs/2021-summer
3. Scroll down to 'Timeline'

**Expected behavior**
Fix the bugs in the timeline

**Screenshots**
![Screenshot_20221121-140957-1](https://user-images.githubusercontent.com/97069900/203004338-2a6f864f-a027-475b-a7fd-eb867b36523b.jpg)

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by anjula-sack** [comment]
> Shall I work on this ?

sure
