### ISSUE TITLE
Remove the duplicated scholarx summer page 

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#1410]
**Is your feature request related to a problem? Please describe.**
- There's a duplicated scholarX summer page. We can remove that file.

**Describe the solution you'd like**
- Remove the duplicated summer page 
https://github.com/sef-global/sef-site/blob/master/scholarx/past-programs/2021/summer/index.html

**Are you working on it?**
No

**Comment by anjula-sack** [comment]
@miniskynet can you work on this?

**Comment by miniskynet** [comment]
sure will work on it @anjula-sack
