### ISSUE TITLE
Issue in program timeline section in ScholarX page

### ISSUE THREAD

**Issue by janithlahirukariyawasam** [sef-global/sef-site#1411]
**Describe the bug**
Issue in the project timeline section.
**Issue is visible when you view the project timeline section using smartphones.**

**To Reproduce**
1. Go to 'ScholarX-2022'
2. Scroll down to 'Project Timeline'  
3. See error

**Expected behavior**
Try to fix the issue using HTML tables.

**Screenshots**
Issue
![image](https://user-images.githubusercontent.com/88109775/203148580-f7d419ba-d1ab-41f6-b6ac-04d06be3eae6.png)

![image](https://user-images.githubusercontent.com/88109775/203148434-752f8f30-be81-411c-a03a-70bbb52648c8.png)

**Additional context**
After fixing the bug using HTML tables.
![fix](https://user-images.githubusercontent.com/88109775/203146684-2812fa8e-5a2d-452e-9079-00beaa60c2cb.png)

**Are you working on it?**
Yes

**Comment by janithlahirukariyawasam** [comment]
Shall I work on this?

**Comment by YoshithaRathnayake** [comment]
> Shall I work on this?

Thank you @janithlahirukariyawasam for telling this bug. @anjula-sack will assign you.
