### ISSUE TITLE
Get content and Implement functionalities in new ScholarX Archive page

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/sef-site#1413]
**Is your feature request related to a problem? Please describe.**
We implemented the initial UI for the ScholarX Archive page in #1388. Now all the content (data) and the functionalities (filtration) should be completed.

**Describe the solution you'd like**
Get the content via API and display it in the archive section. Implement filter funcitons.

**Describe alternatives you've considered**
None

**Additional context**
![Screenshot 2022-11-23 at 01 53 31](https://user-images.githubusercontent.com/70215958/203413908-127ee0de-f529-472c-a2a0-79469565af36.jpg)

**Are you working on it?**
Yes

**Comment by Madhawa97** [comment]
I'm working on this.

**Comment by YoshithaRathnayake** [comment]
> I'm working on this.

Sure @Madhawa97
