### ISSUE TITLE
Fix the alignments of the footer in scholarx archive page

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-site#1415]
**Describe the bug**
Currently, the alignments in the footer of scholarx archive page is not good.

**To Reproduce**
1. Go to 'https://sefglobal.org/scholarx/archive'
3. Scroll down to 'footer'

**Expected behavior**
Fix the alignments of the footer in scholarx archive page.

**Screenshots**
![Screenshot_20221123-065631-1](https://user-images.githubusercontent.com/97069900/203453454-91380475-5cec-4e03-a089-e3505bb8c72b.jpg)

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by Madhawa97** [comment]
Hey @YoshithaRathnayake. Do you know why this issue is present only on the Archive page?

**Comment by YoshithaRathnayake** [comment]
> Hey @YoshithaRathnayake. Do you know why this issue is present only on the Archive page?

Yeah, there is a global css class in styles.css file for the themetic break which reduce the hr margin

![image](https://user-images.githubusercontent.com/97069900/206738000-7ff70b92-2b25-401d-ab94-98eac870b0c5.png)

https://github.com/sef-global/sef-site/blob/5e2577fcbaa6998f452706cdcfeb44b4ea138d12/scholarx/archive/styles.css#L19-L21

We should remove that @Madhawa97

**Comment by YoshithaRathnayake** [comment]
Can you assign me @Madhawa97 ?

**Comment by YoshithaRathnayake** [comment]
Can you assign me @Madhawa97 ?

**Comment by YoshithaRathnayake** [comment]
@anjula-sack can you assign me for this?

**Comment by YoshithaRathnayake** [comment]
Shall I work on this? @anjula-sack
