### ISSUE TITLE
Link the Send Us a Pull Request text to redirect it to the issues tab

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-site#1419]
**Is your feature request related to a problem? Please describe.**
Currently, the Send Us a Pull Request text is not linked, if we link it the first-time contributors can see the issues and work on them

**Describe the solution you'd like**
Link the Send Us a Pull Request text to redirect it to the issues tab

**Additional context**

![image](https://user-images.githubusercontent.com/97069900/203521389-0d114387-4ff9-4ab1-b03e-60c3251fa088.png)

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by Madhawa97** [comment]
Hey @YoshithaRathnayake. Could you please mention the related page?

**Comment by YoshithaRathnayake** [comment]
https://github.com/sef-global/sef-site/issues

If we link the issues page the first-time contributors easily can know the issues, get assigned and contribute no? @Madhawa97

**Comment by YoshithaRathnayake** [comment]
Can you assign me @Madhawa97 ?

**Comment by Madhawa97** [comment]
Hey @YoshithaRathnayake. I'm not sure where the "Send Us a Pull Request" text is. Can you post the link, please?

**Comment by YoshithaRathnayake** [comment]
https://github.com/sef-global/sef-site#contribution

![image](https://user-images.githubusercontent.com/97069900/206942622-69c95cf3-65a4-4971-a834-f932502ff1c2.png)

@Madhawa97

**Comment by Madhawa97** [comment]
Thanks @YoshithaRathnayake. You can work on this.

**Comment by YoshithaRathnayake** [comment]
> Thanks @YoshithaRathnayake. You can work on this.

Thank you for assigning me @Madhawa97
