### ISSUE TITLE
Remove the unwanted codes from scholarx 2022 css file

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-site#1424]
**Is your feature request related to a problem? Please describe.**
Currently, there are unused codes in the css file of the scholarx 2022

**Describe the solution you'd like**
Remove the unwanted codes from scholarx 2022 css file

**Additional context**
https://github.com/sef-global/sef-site/blob/04eb140d1f8ad113efa2c83976431b9d50f1f286/scholarx/2022/styles.css#L86-L92

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Sorry I couldn't mention this in the PR #1417 bcs I faced to a power cut during the it was merged.

**Comment by janithlahirukariyawasam** [comment]
Actually @YoshithaRathnayake , I changed that part also but it wasn't merge in to the main repository. If you can please remove that part.
Thank You.
![style2022](https://user-images.githubusercontent.com/88109775/203605971-e1f1bfa0-ce41-4339-8219-465a080ed551.png)

**Comment by YoshithaRathnayake** [comment]
> Actually @YoshithaRathnayake , I changed that part also but it wasn't merge in to the main repository. If you can please remove that part. Thank You. ![style2022](https://user-images.githubusercontent.com/88109775/203605971-e1f1bfa0-ce41-4339-8219-465a080ed551.png)

Sure I will remove it @janithlahirukariyawasam
