### ISSUE TITLE
Remove the reading time of the featured articles

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-site#1425]
**Describe the bug**
Currently, there are bugs to fixed in the featured articles related to the reading time

**To Reproduce**
1. Go to https://sefglobal.org/scholarx/past-programs/2021 | https://sefglobal.org/scholarx/past-programs/2020
3. Scroll down to 'Featured Articles'

**Expected behavior**
Remove the reading time of the featured articles

**Screenshots**

2021
![image](https://user-images.githubusercontent.com/97069900/203542708-afe31f5e-c5f4-47ec-8e35-1972bc592909.png)

2020
![image](https://user-images.githubusercontent.com/97069900/203542875-b5f7a9a1-3303-4507-b570-10d3bd0db6dd.png)

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by Prasadkpd** [comment]
Shall I work on this?

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake Shall I work on this?

Please, I will work on this @Prasadkpd

**Comment by YoshithaRathnayake** [comment]
@anjula-sack
