### ISSUE TITLE
Change the order of the links in the footer

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-site#1427]
**Is your feature request related to a problem? Please describe.**
Currently, the order is wrong in the links of the footer

**Describe the solution you'd like**
Change the order of the links in the footer as follows,

1. Home
2. Projects
3. Team
4. Blog
5. _**Handbook**_
6. **_Join Us_**

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by dilankavishka** [comment]
Can i work on this?

**Comment by Prasadkpd** [comment]
Shall I work on this?

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake Shall I work on this?

Please, I will work on this @Prasadkpd

**Comment by YoshithaRathnayake** [comment]
Shall I work on this? @anjula-sack
