### ISSUE TITLE
Overlaping issues in ScholarX page (Smartphones)

### ISSUE THREAD

**Issue by janithlahirukariyawasam** [sef-global/sef-site#1428]
**Describe the bug**
There are overlapping issues in FAQ for Mentees/Mentor sections when you use smartphones to view the section

**To Reproduce**
1. Go to 'ScholarX page'
2. Scroll down to 'FAQ for Mentees/Mentor' section (Issue is visible for some smartphones.)

**Expected behavior**
Able to view that section using any smartphone.

**Screenshots**
![overlap](https://user-images.githubusercontent.com/88109775/203762362-ebc8b493-0348-49fd-88da-431638fb50d5.png)

**Additional context**
After fixing the bug.
![image](https://user-images.githubusercontent.com/88109775/203764381-70edd22f-67d0-4063-826e-151f1055fcaf.png)

**Are you working on it?**
Yes

**Comment by janithlahirukariyawasam** [comment]
Shall I work on this?

**Comment by YoshithaRathnayake** [comment]
> Shall I work on this?

Sure, go ahead @janithlahirukariyawasam
