### ISSUE TITLE
The margin top of the IRC page header is increased

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-site#1430]
**Is your feature request related to a problem? Please describe.**
Currently, the margin top of the IRC page header is increased

**Describe the solution you'd like**
Decrease the margin top of the IRC page header

**Describe alternatives you've considered**
![image](https://user-images.githubusercontent.com/97069900/203816276-ba66d9c5-a785-4b95-bf07-e0ad59855e1f.png)

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by dilankavishka** [comment]
can i work on this?

**Comment by YoshithaRathnayake** [comment]
> can i work on this?

Sure

**Comment by YoshithaRathnayake** [comment]
If you need a help let me know? @dilankavishka

**Comment by dilankavishka** [comment]
I started working on this, but there is a problem; could you assist me with that? @YoshithaRathnayake . The problem is that there is a common class called "section" that determines the top padding for several pages, including the Scholarx and Upspeak. So, how should I proceed? Is it necessary to create a new class and set the top padding for the IRC page?

**Comment by YoshithaRathnayake** [comment]
> I started working on this, but there is a problem; could you assist me with that? @YoshithaRathnayake . The problem is that there is a common class called "section" that determines the top padding for several pages, including the Scholarx and Upspeak. So, how should I proceed? Is it necessary to create a new class and set the top padding for the IRC page?

No no don't do like them, just use the bootstrap classes @dilankavishka

**Comment by YoshithaRathnayake** [comment]
https://github.com/sef-global/sef-site/blob/788bc19be8d71f0e6460f65d4d3c7cd75945f02a/irc.html#L40

Just reduce the mt-5 to mt-3 like below @dilankavishka 

````html

 <section class="section pb-0 bg-gradient-white mt-3">
````
