### ISSUE TITLE
Fix the overlapping image issue in "Past One Live" Page

### ISSUE THREAD

**Issue by janithlahirukariyawasam** [sef-global/sef-site#1432]
**Describe the bug**
Fixing Overlapping issue in "Past One Live" Page.
Some times Text overlaps on the header-onlive.svg image.

**To Reproduce**
1. Go to 'One Live'
2. Click on 'See More' (View the Section using different devices)
3. See error

**Expected behavior**
Able to view the Past One Live page using any device.

**Screenshots**
![Overlap Oneive past error](https://user-images.githubusercontent.com/88109775/203905140-3334d367-882e-41d0-8099-aa5d271bebe6.png)

**Are you working on it?**
Yes

**Comment by janithlahirukariyawasam** [comment]
Shall I work on this?

**Comment by YoshithaRathnayake** [comment]
> Shall I work on this?

Sure, go ahead @janithlahirukariyawasam
