### ISSUE TITLE
Fix navbar of the AcadeMix Page in the mobile view

### ISSUE THREAD

**Issue by janithlahirukariyawasam** [sef-global/sef-site#1433]
**Describe the bug**
Fix Navbar of the AcadeMiX Page

**To Reproduce**
1. Go to 'AcadeMiX Page'
2. View Navbar Using Smartphones
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/88109775/203922589-b6d8a926-6260-4773-b684-a3869cd1bfed.png)

**Are you working on it?**
Yes

**Comment by janithlahirukariyawasam** [comment]
Shall I work on this?

**Comment by YoshithaRathnayake** [comment]
> Shall I work on this?

Sure, go ahead @janithlahirukariyawasam

**Comment by YoshithaRathnayake** [comment]
Why did you close this. Can't you fix it? @janithlahirukariyawasam If you can't let me know we will assign it to another.

**Comment by janithlahirukariyawasam** [comment]
@YoshithaRathnayake Actually The issue in the Academix-frontend Repository.
Also the favicon issue.
So we have to open the issue in that repository. I thought AcademicX in the SEF-site Repo like ScholarX , Student Ambassador, Engineering Team & etc.

Sorry For The Inconvenience You Faced!

**Comment by YoshithaRathnayake** [comment]
> 

No worries. It's ok @janithlahirukariyawasam
