### ISSUE TITLE
Favicon is not visible in the AcadeMix Page

### ISSUE THREAD

**Issue by janithlahirukariyawasam** [sef-global/sef-site#1434]
**Describe the bug**
SEF logo not visible in Title of the AcadeMiX Page

**To Reproduce**
1. Go to 'AcadeMiX'
2. View the Title of the Page
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/88109775/203923345-01017a12-2113-41ba-b7d7-317ba7d964af.png)

**Are you working on it?**
Yes

**Comment by janithlahirukariyawasam** [comment]
Shall I work on this?

**Comment by YoshithaRathnayake** [comment]
> Shall I work on this?

Sure, go ahead @janithlahirukariyawasam

**Comment by YoshithaRathnayake** [comment]
Why did you close this. Can't you fix it? @janithlahirukariyawasam If you can't let me know we will assign it to another.
