### ISSUE TITLE
Change the background color of the 'Are you a ScholarX alumini?' section in Scholarx Success Stories

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-site#1438]
**Is your feature request related to a problem? Please describe.**
Currently, the background color of the 'Are you a ScholarX alumini?' section in Scholarx Success Stories and the success stories are same. We can't see a difference between them

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/97069900/204069939-38e5a960-80ce-45b1-a6ce-da171ace931f.png) 

#f8fdff

Add this color to the 'Are you a ScholarX alumini?' section in Scholarx Success Stories Page (FAQ section bg color)

**Additional context**
![image](https://user-images.githubusercontent.com/97069900/204069961-cf1477a5-3c45-46bd-821a-3bc9f033e948.png)

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by dilankavishka** [comment]
Can i work on this?

**Comment by shashidil** [comment]
Shall I work on this?

**Comment by YoshithaRathnayake** [comment]
> Shall I work on this?

I will work on this ok?

**Comment by Madhawa97** [comment]
@YoshithaRathnayake was this discussed in a standup? IIRC we agreed to go ahead with this because it looks much more cleaner and `#f8fdff` didn't look good with the footer.

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake was this discussed in a standup? IIRC we agreed to go ahead with this because it looks much more cleaner and `#f8fdff` didn't look good with the footer.

No I think it wasn't discussed in a standup. was it? If it not bad shall we add a another colour, will discuss on the upcoming standup ok? @Madhawa97
