### ISSUE TITLE
Implement mentor/mentee dropdown menu in ScholarX Archive page

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/sef-site#1439]
**Is your feature request related to a problem? Please describe.**
Currently, on the ScholarX Archive page, only the list of mentors is displayed. 
You can view it by visiting [https://sefglobal.org/scholarx/archive/](https://sefglobal.org/scholarx/archive/).

**Describe the solution you'd like**
The mentees' details are also available in the payload received from the [API](https://script.google.com/macros/s/AKfycbw0TVyldiK5ijUxjLJkhrxHpxZpIjoeLytZqrvOlftYeHywn1hBEnL0aHGIS8hOFxPp/exec) as `mentee2021`, `mentee2020` and `mentee2019`. 

implement the dropdown menu to display the mentees and mentors accordingly.

**Describe alternatives you've considered**
None

**Additional context**
![Screenshot 2022-11-26 at 21 11 50](https://user-images.githubusercontent.com/70215958/204096987-1faea743-d5fa-40fe-ad75-dea160ac5a53.jpg)
Once the selected menu item in the above dropdown menu is changed, the profile list should update accordingly.

**Are you working on it?**
No

**Comment by janithlahirukariyawasam** [comment]
@Madhawa97 Shall I work on this?

**Comment by Madhawa97** [comment]
Sure @janithlahirukariyawasam. Go ahead.
