### ISSUE TITLE
Create a new page for resources. 

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#144]
Create a new page for media/resources, things like logos and logo guidelines could be hosted here. (Add dummy data. Only the structure is needed.)

The page should contain.
- A table (or something creative) which contains resource name and button to download the item.
- A place to display guidelines. (add dummy paragraphs with headings) 

Use this template [template.html](https://github.com/SustainableEducationFoundation/LiveWeb/blob/master/template.html)

Components: [components.html](https://github.com/SustainableEducationFoundation/LiveWeb/blob/master/examples/components.html)

**Comment by Gravewalker666** [comment]
ill do it.

**Comment by Gravewalker666** [comment]
Done.
#147 pr

**Comment by jayasanka-sack** [comment]
Good job @Gravewalker666 👍
