### ISSUE TITLE
Implement a modal with mentor/mentee details in ScholarX Archive page

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/sef-site#1441]
**Is your feature request related to a problem? Please describe.**
Currently, on the ScholarX Archive page, mentor/ mentee details are not displayed.
You can visit the page at [https://sefglobal.org/scholarx/archive/](https://sefglobal.org/scholarx/archive/).

**Describe the solution you'd like**
Once a viewer clicks a profile of a mentor/mentee in the archive, a modal should appear with all the details of that mentor/ mentee. 
This can be similar to the one we have in the [https://sefglobal.org/scholarx/past-programs/2021/](https://sefglobal.org/scholarx/past-programs/2021/) page.
![Screenshot 2022-11-28 at 13 48 11](https://user-images.githubusercontent.com/70215958/204227755-e4eeb63a-60bb-4af3-aa95-ae7ea05215e2.jpg)

**Describe alternatives you've considered**
None

**Additional context**
All the details are available in the [API](https://script.google.com/macros/s/AKfycbw0TVyldiK5ijUxjLJkhrxHpxZpIjoeLytZqrvOlftYeHywn1hBEnL0aHGIS8hOFxPp/exec) and have already used in the [https://sefglobal.org/scholarx/archive/](https://sefglobal.org/scholarx/archive/) page.

The following details should be displayed.

**For the mentors:**
- Name
- Title
- Image (hyperlinked to the LinkedIn profile)
- Bio
- Areas of expertise
- Projects
- Mentees[]

**For the mentees:**
- Name
- Image (hyperlinked to the LinkedIn profile)
- Mentor's name
- University

**Are you working on it?**
No

**Comment by YoshithaRathnayake** [comment]
Can I work on this?

**Comment by Madhawa97** [comment]
> Can I work on this?

Sure Yoshitha. Go ahead.

**Comment by YoshithaRathnayake** [comment]
> Sure Yoshitha. Go ahead.

Please can you tell me what should I do? because I don't have an idea how to do it.

**Comment by Madhawa97** [comment]
Yes, @YoshithaRathnayake. You can use JQuery. I'll DM you regarding this.

**Comment by YoshithaRathnayake** [comment]
> Yes, @YoshithaRathnayake. You can use JQuery. I'll DM you regarding this.

Sure thank you @Madhawa97
