### ISSUE TITLE
IRC Landing Page Structure

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#145]
Create a landing page for IRC. 
The page should include the following details. But we need only the structure. Use dummy texts when creating the page.

- What is IRC
- Image of the IRC call for SL researchers
- sign up link
- profiles of the researchers

Use this template [template.html](https://github.com/SustainableEducationFoundation/LiveWeb/blob/master/template.html)

Components: [components.html](https://github.com/SustainableEducationFoundation/LiveWeb/blob/master/examples/components.html)

**Comment by BhathiyaTK** [comment]
I'll do this.
