### ISSUE TITLE
Implement COHORT filters in archive page

### ISSUE THREAD

**Issue by janithlahirukariyawasam** [sef-global/sef-site#1453]
**Describe the bug**
Currently, we haven't implemented COHORT filters on the archive page.

**Expected behavior**
Will able to use the filter by year (COHORT) .

**Screenshots**
![image](https://user-images.githubusercontent.com/88109775/205454494-ab84c84f-6642-4518-be2b-16ef00e9cbd3.png)

**Are you working on it?**
Yes

**Comment by janithlahirukariyawasam** [comment]
Shall I work on this Guys? Can you merge the previous pull request also?

**Comment by YoshithaRathnayake** [comment]
> Shall I work on this Guys? Can you merge the previous pull request also?

Sure
