### ISSUE TITLE
Some meta tags are missing in the scholarx success stories page

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-site#1455]
**Is your feature request related to a problem? Please describe.**
Currently, some meta tags are missing in the scholarx success stories page

**Describe the solution you'd like**
Add these meta tags to the scholarx success stories page

````html
<meta name="author" content="Sustainable Education Foundation">
````

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by Madhawa97** [comment]
shall we add this with another PR? @YoshithaRathnayake. Probably with an issue assigned to you. Because this page is still under development and may have lots of missing details like this.

**Comment by YoshithaRathnayake** [comment]
> shall we add this with another PR? @YoshithaRathnayake. Probably with an issue assigned to you. Because this page is still under development and may have lots of missing details like this.

Ok I'll try @Madhawa97

**Comment by YoshithaRathnayake** [comment]
Shall I work on this? @anjula-sack
