### ISSUE TITLE
Convert the .svg image file types to .png or .jpg image file types

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-site#1456]
**Is your feature request related to a problem? Please describe.**
Currently, In like join us page the og:image is a .svg image therefore it's not loading in the og:image

**Describe the solution you'd like**
Change the .svg image file types to .png or .jpg image file types

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this?

**Comment by shashidil** [comment]
Shall I fix this?

**Comment by YoshithaRathnayake** [comment]
I will work on this ok?

**Comment by miniskynet** [comment]
Hi @shashidil, since this is first come first serve basis I had to assign this to @YoshithaRathnayake.
