### ISSUE TITLE
Replace the SEF data holder URL

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#1463]
**Is your feature request related to a problem? Please describe.**
- We need to replace the Heroku dataholder URL with our new sub domain

**Describe the solution you'd like**
- Replace the following URL 
`https://sef-dataholder.herokuapp.com` with `https://apps.sefglobal.org/`

Check if the online videos are loading.
https://sefglobal.org/onelive/archive/

**Are you working on it?**
No

**Comment by anjula-sack** [comment]
@Tharindu37 can you work on this?

**Comment by YoshithaRathnayake** [comment]
Shall I work on this?

**Comment by Tharindu37** [comment]
@anjula-sack sure
