### ISSUE TITLE
Implement INDUSTRY filters for the mentors in ScholarX Archive page

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/sef-site#1465]
**Is your feature request related to a problem? Please describe.**
The Mentors of ScholarX Archive page cannot be filtered by their Industry.

**Describe the solution you'd like**
Implement INDUSTRY filters only for mentors. 

**Describe alternatives you've considered**
None

**Additional context**
![Screenshot 2022-12-09 at 10 24 40](https://user-images.githubusercontent.com/70215958/206627133-d83e0d68-e476-4de2-a5dc-fd5b08a55974.jpg)

Previous PR for Archive section: Implementing COHORT filters #1453 

**Are you working on it?**
No

**Comment by janithlahirukariyawasam** [comment]
@Madhawa97 I like to give a try to this Madhawa, Can you assign me?
Do we need to show these industry filters on the mentee's page?

**Comment by YoshithaRathnayake** [comment]
> @Madhawa97 I like to give a try to this Madhawa, Can you assign me? Do we need to show these industry filters on the mentee's page?

Sure go ahead @janithlahirukariyawasam

**Comment by Madhawa97** [comment]
> @Madhawa97 I like to give a try to this Madhawa, Can you assign me? Do we need to show these industry filters on the mentee's page?

Hey @janithlahirukariyawasam, Sure you can go ahead. I can see you have been assigned already. 
Yes actually I was hoping to address that later with another PR but yeah if you can, make the INDUSTRY filters visible only for the Mentors.

**Comment by janithlahirukariyawasam** [comment]
> > @Madhawa97 I like to give a try to this Madhawa, Can you assign me? Do we need to show these industry filters on the mentee's page?
> 
> Hey @janithlahirukariyawasam, Sure you can go ahead. I can see you have been assigned already. 
> Yes actually I was hoping to address with later with another PR but yeah if you can, make the INDUSTRY filters visible only for the Mentors.

Sure
