### ISSUE TITLE
Implement filter by UNIVERSITY for the mentees in ScholarX Archive page

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/sef-site#1466]
**Is your feature request related to a problem? Please describe.**
The Mentees of the ScholarX Archive page cannot be filtered by their University.

**Describe the solution you'd like**
Implement filter by University ONLY for the mentees on the ScholarX Archive page.

**Describe alternatives you've considered**
None

**Additional context**
![Screenshot 2022-12-09 at 10 31 18](https://user-images.githubusercontent.com/70215958/206627752-58970a6b-f665-4354-9022-0adffd548bdb.jpg)

Previous PR for Archive section: Implementing COHORT filters #1453
Ongoing: Implement INDUSTRY filters  #1465

**Are you working on it?**
No

**Comment by YoshithaRathnayake** [comment]
Shall I work on this?

**Comment by Madhawa97** [comment]
Sure go ahead @YoshithaRathnayake.

**Comment by YoshithaRathnayake** [comment]
> Sure go ahead @YoshithaRathnayake.

Thank you so much @Madhawa97

**Comment by YoshithaRathnayake** [comment]
@Madhawa97 I will do this. Please can you give me a help to do this?

**Comment by YoshithaRathnayake** [comment]
@Madhawa97 can you assign @janithlahirukariyawasam for this bcs it is little bit harder to do this for me

**Comment by janithlahirukariyawasam** [comment]
@YoshithaRathnayake Can you assign me?

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake Can you assign me?

Sure @janithlahirukariyawasam
