### ISSUE TITLE
Display a "No result found!" message in ScholarX Archive page

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/sef-site#1467]
**Is your feature request related to a problem? Please describe.**
Currently, It shows nothing when there are no matching results for a given filter, which might confuse the end user. 

**Describe the solution you'd like**
Display a "No result found!" message when there are no search results.

**Describe alternatives you've considered**
None

**Additional context**
![Screenshot 2022-12-09 at 10 38 56](https://user-images.githubusercontent.com/70215958/206628524-9552538a-c6f6-4633-8e91-15d9ebd73111.jpg)

**Are you working on it?**
No

**Comment by Madhawa97** [comment]
@pirijatharsan is currently working on this.

**Comment by Pirijatharsan** [comment]
ok
