### ISSUE TITLE
Hide INDUSTRY filters on mentee Page & UNIVERSITY filter on the mentor page

### ISSUE THREAD

**Issue by janithlahirukariyawasam** [sef-global/sef-site#1470]
**Describe the bug**
Currently INDUSTRY filters are visible on the mentees page.

**To Reproduce**
1. Go to 'ScholarX archive'
2. Select 'Mentees'
3. See error

**Expected behavior**
Hide INDUSTRY filters on mentees page.

**Screenshots**
![image](https://user-images.githubusercontent.com/88109775/206863893-d13b4803-5017-4000-9a04-fdd5f9c9f735.png)

**Additional context**

**Are you working on it?**
Yes

**Comment by janithlahirukariyawasam** [comment]
Shall I work on this? Do we need to hide UNIVERSITY filter on the mentor page ?

**Comment by Madhawa97** [comment]
You can go ahead. and Yes, we need to hide UNIVERSITY filter on the mentor page.
