### ISSUE TITLE
Fix the typo in the success stories page

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#1471]
**Is your feature request related to a problem? Please describe.**
- There's a typo in the success stories and scholars pages

**Describe the solution you'd like**
- Alumini should be alumni

<img width="458" alt="Screenshot 2022-12-11 at 9 06 08 AM" src="https://user-images.githubusercontent.com/43912578/206885115-febc8843-d9e6-488f-8b27-4696141dab0e.png">

**Additional context**
Try to find and replace it because there might be other places with the same mistake

**Are you working on it?**
No

**Comment by anjula-sack** [comment]
@dilankavishka can you work on this?

**Comment by dilankavishka** [comment]
Yeah sure.
