### ISSUE TITLE
Remove the search button in the archive page

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#1472]
**Is your feature request related to a problem? Please describe.**
- We don't need the search button because the search happens as the user types

**Describe the solution you'd like**
- Remove the search button on the archive page
- https://sefglobal.org/scholarx/archive/

<img width="679" alt="Screenshot 2022-12-11 at 9 15 20 AM" src="https://user-images.githubusercontent.com/43912578/206885345-28e4a771-a73a-4d6c-b573-d5e818d720c6.png">

**Are you working on it?**
- No

**Comment by anjula-sack** [comment]
@dilankavishka can you work on this?

**Comment by dilankavishka** [comment]
Yeah Sure.
