### ISSUE TITLE
Remove the upcoming events section from the onelive page

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#1473]
**Is your feature request related to a problem? Please describe.**
On the onelive page, we have a [section displaying upcoming onelive events](https://sefglobal.org/onelive/#section-events). We no longer require that section because the onelive program is discontinued.

**Describe the solution you'd like**
Remove the `upcoming events` section

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Are you working on it?**
No

**Comment by Danathelittle** [comment]
I would like to work on this!

**Comment by Piumal1999** [comment]
Sure @Danathelittle, go ahead

**Comment by Danathelittle** [comment]
@Piumal1999 thank you

**Comment by Piumal1999** [comment]
Hi @Danathelittle, any update on this?

**Comment by Danathelittle** [comment]
Sorry for the late!
