### ISSUE TITLE
Reduce the image size of OneLive page

### ISSUE THREAD

**Issue by dilankavishka** [sef-global/sef-site#1478]
**Is your feature request related to a problem? Please describe.**
Currently, the main image on OneLive page is very large.

**Describe the solution you'd like**
Make it little bit smaller.

**Describe alternatives you've considered**
None

**Additional context**
<img width="1606" alt="Screenshot 2022-12-18 at 11 06 37" src="https://user-images.githubusercontent.com/109354298/208283314-a9c5575e-b515-4a0d-a81d-7828c38e5ea4.png">

**Are you working on it?**
Yes

**Comment by dilankavishka** [comment]
Can i work with this?

**Comment by YoshithaRathnayake** [comment]
> Can i work with this?

Sure

**Comment by YoshithaRathnayake** [comment]
Shall I work on this? @anjula-sack

**Comment by Dilini-457** [comment]
I would like to work on this

**Comment by YoshithaRathnayake** [comment]
> I would like to work on this

Go ahead @Dilini-457

**Comment by YoshithaRathnayake** [comment]
Need any help? @Dilini-457
