### ISSUE TITLE
Reduce the image size of Student Ambassador page

### ISSUE THREAD

**Issue by dilankavishka** [sef-global/sef-site#1479]
**Is your feature request related to a problem? Please describe.**
Currently, the main image on Student Ambassador page is little bit large.

**Describe the solution you'd like**
Make it little bit smaller.

**Describe alternatives you've considered**
None

**Additional context**
<img width="1606" alt="Screenshot 2022-12-18 at 11 16 08" src="https://user-images.githubusercontent.com/109354298/208283541-671d460f-a0f4-4a5d-a741-49f8aaa744b6.png">

**Are you working on it?**
Yes

**Comment by dilankavishka** [comment]
Can i work on this?

**Comment by YoshithaRathnayake** [comment]
> Can i work on this?

Sure

**Comment by YoshithaRathnayake** [comment]
Shall I work on this? @anjula-sack

**Comment by nimeshkavindu** [comment]
Can you assign me to this?

**Comment by YoshithaRathnayake** [comment]
> Can you assign me to this?

Yeah sure, you can work on this @nimeshkavindu

**Comment by YoshithaRathnayake** [comment]
Need any help? @nimeshkavindu

**Comment by nimeshkavindu** [comment]
> Need any help? @nimeshkavindu

 I'll reach out if I get stuck.
