### ISSUE TITLE
Fix content difference in SA page

### ISSUE THREAD

**Issue by dilankavishka** [sef-global/sef-site#1483]
**Describe the bug**
There is a difference between in the main paragraph on mobile view and the desktop view.

**Expected behavior**
Fix the difference between in the main paragraph on mobile view and the desktop view.

**Screenshots**
1. mobile view.
<img width="444" alt="Screenshot 2022-12-22 at 17 44 57" src="https://user-images.githubusercontent.com/109354298/209133216-aa94ca89-f0eb-4de9-aa36-49301cdf7634.png">

2. desktop view.
<img width="1648" alt="Screenshot 2022-12-22 at 17 45 22" src="https://user-images.githubusercontent.com/109354298/209132752-c823a429-d598-4f4e-b02d-24b0060691ba.png">

**Additional context**
None.

**Are you working on it?**
Yes.

**Comment by dilankavishka** [comment]
Can i work on this? @anjula-sack

**Comment by anjula-sack** [comment]
> Can i work on this? @anjula-sack

sure, Go ahead @dilankavishka
