### ISSUE TITLE
Remove the apply now section from the join us page

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/sef-site#1486]
**Is your feature request related to a problem? Please describe.**
The join us page has a section as [Apply Now](https://sefglobal.org/join-us.html). We no longer require that section.

**Describe the solution you'd like**
Remove the `apply now` section.

**Describe alternatives you've considered**
None

**Additional context**
![Screenshot 2022-12-26 at 18 03 10](https://user-images.githubusercontent.com/70215958/209549961-3b1cee66-9ea7-471b-b3e5-652ce3afc6ee.jpg)

**Are you working on it?**
No

**Comment by Pirijatharsan** [comment]
Yes i will work on this

**Comment by Madhawa97** [comment]
sure @piriyatharsan
