### ISSUE TITLE
Add loading animation to blog article section and success stories cards - Engineering team page

### ISSUE THREAD

**Issue by dave-v0** [sef-global/sef-site#1495]
**Is your feature request related to a problem? Please describe.**
Add loading animation to the blog article section and success stories cards

**Describe the solution you'd like**
Add a CSS animation to the blog article section and success stories cards till it loads completely

**Describe alternatives you've considered**
Add animation to the cards and blog articles

**Are you working on it?**
Yes

**Comment by dave-v0** [comment]
@anjula-sack @Piumal1999 Can I work on this, please?

**Comment by anjula-sack** [comment]
What is the status of this? @DilinaBandara
