### ISSUE TITLE
Update ScholarX timeline and automate the indicator

### ISSUE THREAD

**Issue by dave-v0** [sef-global/sef-site#1496]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
Update ScholarX timeline and automate the indicator

**Describe the solution you'd like**
Update the text to 2023 and automate indicator using JavaScript according to month

**Are you working on it?**
Yes

**Comment by anjula-sack** [comment]
Can you just update the timeline for now? @DilinaBandara We don't need to automate it.

**Comment by dave-v0** [comment]
Sure @anjula-sack, I'll work on it :)
