### ISSUE TITLE
Update github leaderboard link with the new one

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#1502]
**Is your feature request related to a problem? Please describe.**
- We need to update the GitHub leaderboard link 

**Describe the solution you'd like**
- Replace https://sef-github-leaderboard.herokuapp.com/ with https://wehuddle.sefglobal.org/leaderboard
<img width="400" alt="image" src="https://user-images.githubusercontent.com/43912578/216800393-36ff89ad-a591-4e46-93a7-4772b8789e79.png">

**Are you working on it?**
No

**Comment by anjula-sack** [comment]
@dilankavishka can you work on this?

**Comment by dilankavishka** [comment]
@anjula-sack  sure
