### ISSUE TITLE
Implement Industry Filters on Archive Page.

### ISSUE THREAD

**Issue by janithlahirukariyawasam** [sef-global/sef-site#1512]
**Describe the bug**
Implement Industry filters on Archive Page 

**Expected behavior**
Dynamic Industry checkboxes
functional Industry Filters

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Why did you close this PR? @janithlahirukariyawasam

**Comment by janithlahirukariyawasam** [comment]
> Why did you close this PR? @janithlahirukariyawasam

Sorry Yoshitha Duplication
#1465

**Comment by YoshithaRathnayake** [comment]
> > Why did you close this PR? @janithlahirukariyawasam
> 
> Sorry Yoshitha Duplication #1465

Oh! It's ok @janithlahirukariyawasam
