### ISSUE TITLE
FIx alignment of items in press coverage section in tablet view.

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/sef-site#1523]
**Describe the bug**
The alignment of the last item in press coverage section in home page is off.

**To Reproduce**
1. Go to '[https://sefglobal.org/](https://sefglobal.org/)' in Tablet view.
2. Scroll down to 'Press Coverage' section
3. See the miss-aligned item.

**Expected behavior**
The last item should be centred in tablet view.

**Screenshots**
![Screenshot 2023-03-03 at 00 05 54](https://user-images.githubusercontent.com/70215958/222520720-7655de61-5ecc-4b56-afca-ba160d951d36.jpg)

**Smartphone (please complete the following information):**
 - Device: iPad
 - OS: iOS
 - Browser: Chrome
 - Version: Latest

**Are you working on it?**
No

**Comment by Nelka97** [comment]
I will work on this

**Comment by Madhawa97** [comment]
Sure, Go ahead @Nelka97
