### ISSUE TITLE
Fix LinkedIn URL not working issue & remove unwanted profile model fields

### ISSUE THREAD

**Issue by janithlahirukariyawasam** [sef-global/sef-site#1527]
**Describe the bug**
currently linkedln URL in the profile model not working & also we have to remove some unwanted fields on profile model.

**To Reproduce**
1. Go to 'ScholarX archive page'
2. Click on 'profile models'
3. See error

**Are you working on it?**
Yes

**Comment by janithlahirukariyawasam** [comment]
Can you assign me?

**Comment by Madhawa97** [comment]
sure @janithlahirukariyawasam
