### ISSUE TITLE
Update the mentor application dates and the join button

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#1528]
**Is your feature request related to a problem? Please describe.** 
We need to update the mentor application dates and the join button

**Describe the solution you'd like**
- Join the waiting list should be renamed to Apply as a mentor
- Button link should be https://scholarx.sefglobal.org/
<img width="444" alt="image" src="https://user-images.githubusercontent.com/43912578/224605426-6156315d-2f18-4cb4-bc48-4fbc0d9ac8d5.png">

- Update the mentor application date in FAQ section from 6th of March 2023 to 13th of March 2023

<img width="1193" alt="image" src="https://user-images.githubusercontent.com/43912578/224606688-dee8cb6c-1ab8-4117-8fb0-f523a5dce2da.png">

**Are you working on it?**
No

**Comment by Sanjana0823** [comment]
I would like to work on this.

**Comment by anjula-sack** [comment]
> I would like to work on this.

Go ahead! @Sanjana0319
