### ISSUE TITLE
Update the scholarx 2023 page images

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/sef-site#1530]
**Is your feature request related to a problem? Please describe.**
Current images in the [scholarx 2023 page](https://sefglobal.org/scholarx/2023/) mentor and mentee registration section are blurry/ low quality.

**Describe the solution you'd like**
Update those two images with the images obtained from [this hive thread](https://sef.discourse.group/t/the-scholarx-2023-page-improvements/474/9?u=madhawa).

**Describe alternatives you've considered**
none

**Additional context**
none

**Are you working on it?**
No

**Comment by Nelka97** [comment]
I'd like to work on this

**Comment by anjula-sack** [comment]
> I'd like to work on this

Go ahead @Nelka97
