### ISSUE TITLE
The ScholarX introduction paragraph and image needs refurbishing

### ISSUE THREAD

**Issue by miniskynet** [sef-global/sef-site#1533]
**Is your feature request related to a problem? Please describe.**
The opening paragraph as well as the image on the ScholarX page requires refurbishing.

**Describe the solution you'd like**
Replace the paragraph with new content and replace the image with a new vector art

**Additional context**
![image](https://user-images.githubusercontent.com/49517852/225361141-3cc6c950-2940-426c-887e-36f4c237966a.png)

**Are you working on it?**
No

**Comment by MethmaPeiris99** [comment]
Please assign me
