### ISSUE TITLE
Add the Scholarx 2023 timeline

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#1535]
**Is your feature request related to a problem? Please describe.**
- We need to add the scholarX 2023 timeline

**Describe the solution you'd like**
- Use the same timeline as on 2022 page
https://sefglobal.org/scholarx/past-programs/2022/

<img width="809" alt="image" src="https://user-images.githubusercontent.com/43912578/225692163-916e8a7d-a337-4574-8309-0cb050a5063a.png">

- Content as follows,

Mentor applications - 13 March, 2023 - 31 March, 2023
Mentors announced - 8th April 2023
Student application period - 8 April, 2023 - 12 May, 2023
Publish selected students - 27 May, 2023
Community bonding - 27 May, 2023 - 3 June, 2023
Official start date of ScholarX -3 June, 2023
Mid-Evaluation 15 Sep, 2023
End Evaluation 15 Dec, 2023
Graduation - 2024 Q1

**Are you working on it?**
No

**Comment by Sanjana0823** [comment]
I would like to work on this.
