### ISSUE TITLE
Implement the mobile view of ScholarX Archive Page

### ISSUE THREAD

**Issue by janithlahirukariyawasam** [sef-global/sef-site#1538]
**Is your feature request related to a problem? Please describe.**
We have to implement the mobile view of the ScholarX archive page.
Currently, filter Checkboxes are overlapped on the mentor/mentee table in mobile view.
Link to ScholarX Archive -  https://sefglobal.org/scholarx/archive/

**This overlap happens when the width of the screen become less than 992**
![image](https://user-images.githubusercontent.com/88109775/226165794-768b75bb-ff44-4e52-a700-b6d77b2520a5.png)

![image](https://user-images.githubusercontent.com/88109775/226165094-811c526a-d457-4a3e-821a-6ebe3084c4b4.png)

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/88109775/226165423-9f70d422-ecc7-4edb-9439-2a33fad15acb.png)

We can move all the checkboxes and dropdowns to the top of the mentor/mentee table when the **screen width is lesser than 992**.

**Are you working on it?**
No

**Comment by janithlahirukariyawasam** [comment]
@anjula-sack 
Can you assign me?

**Comment by anjula-sack** [comment]
> @anjula-sack Can you assign me?

Go ahead! You have done a really good job with the issue details. @janithlahirukariyawasam
