### ISSUE TITLE
Creating a new promotional section for EchonLabs

### ISSUE THREAD

**Issue by miniskynet** [sef-global/sef-site#1544]
**Is your feature request related to a problem? Please describe.**
Since EchonLabs provided us with a server for application deployment, we will be including promotional material of their company on our site, preferably on the main page.

**Describe the solution you'd like**
It would be ideal to create a section similar to the following "Press Coverage" section just below it: 

![image](https://user-images.githubusercontent.com/49517852/227774877-f9fcdd2d-74d8-424b-9ed1-b8f15078a2c5.png)

A logo will be provided in due time.

**Are you working on it?**
No

**Comment by Sanjana0823** [comment]
I would like to work on this.

**Comment by anjula-sack** [comment]
Here's the image @Sanjana0319 https://www.echonlabs.com/storage/2021/01/logo-vector.svg

**Comment by anjula-sack** [comment]
Let's use the Infrastructure partner as the title of this section. @miniskynet @Sanjana0319
