### ISSUE TITLE
Link ScholarX archive page to ScholarX page

### ISSUE THREAD

**Issue by janithlahirukariyawasam** [sef-global/sef-site#1551]
**Is your feature request related to a problem? Please describe.**
We have to link the ScholarX archive page to the ScholarX page just like our past programs.

**Are you working on it?**
Yes

**Comment by anjula-sack** [comment]
Let's hold on to this until we add the 2022 data

**Comment by janithlahirukariyawasam** [comment]
@anjula-sack Sure

**Comment by YoshithaRathnayake** [comment]
Can you assign me? @janithlahirukariyawasam
