### ISSUE TITLE
Update the ScholarX 2023 timeline

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#1552]
**Is your feature request related to a problem? Please describe.**
- We need to update the ScholarX timeline

**Describe the solution you'd like**
- Update the timeline as follows,
Mentor applications 13 March, 2023 - 14 April, 2023
Mentors announced 14 April, 2023
Student application period 14 April, 2023 - 12 May, 2023
<img width="788" alt="image" src="https://user-images.githubusercontent.com/43912578/229975914-9fa8d25e-ad28-4b0e-acde-e3775c5f9250.png">

- Update the FAQ sections as well

<img width="1168" alt="image" src="https://user-images.githubusercontent.com/43912578/229975949-f037023e-a9e2-4800-9377-2e6834765213.png">
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/43912578/229975997-39532e39-3316-49b5-ac73-e9faf896643d.png">

**Are you working on it?**
No

**Comment by Sanjana0823** [comment]
I would like to work on this.

**Comment by anjula-sack** [comment]
> I would like to work on this.

Go ahead @Sanjana0319
