### ISSUE TITLE
Update the ScholarX 2023 page

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#1554]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
- Remove apply as a mentor button
<img width="443" alt="image" src="https://user-images.githubusercontent.com/43912578/231051526-894b78ab-96ee-465a-aa0f-86bf914487f6.png">

- Update the following description

<img width="586" alt="image" src="https://user-images.githubusercontent.com/43912578/231051570-4790e145-6191-4183-9baa-93ae3880d563.png">

to 

> Do you consider yourself a qualified professional with a knack for mentoring? Now you can share your knowledge with budding young talent of Sri Lanka. Reach us via [sustainableedufoundation@gmail.com](mailto:sustainableedufoundation@gmail.com)

- Update the timeline 
   - Mentor applications | 13 March 2023 - 11 April 2023

- Update the mentor FAQ

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/43912578/231051684-26797bfa-c0c4-4396-b262-8a0a9acc2f1b.png">

> Applications for the mentors of the ScholarX program 2023 will open on 13th of March 2023 and will close 11th of April 2023. Since the application period is over, you may also submit your CV, a headshot, and expression of interest to [sustainableedufoundation@gmail.com](mailto:sustainableedufoundation@gmail.com)

</li></ul>

**Are you working on it?**
No

**Comment by Sanjana0823** [comment]
I would like to work on this.

**Comment by anjula-sack** [comment]
> I would like to work on this.

Go ahead @Sanjana0319
