### ISSUE TITLE
Team page 'See more' button is not functioning properly

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#1558]
**Describe the bug**
On the engineering team section of the team page, there's a "See more" button even though there are only 8 profiles. However, clicking on the button doesn't load any additional profiles, it simply hides the button.

**To Reproduce**
1. Go to [team page](https://sefglobal.org/team.html)
2. Go to Engineering Team Section
3. See error

**Expected behavior**
If there are only 8 profiles, the see more button should not be visible. 

**Screenshots**
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/27498587/231477397-73ffb416-3814-4660-9f88-ab6d2a136c01.png">

**Additional context**
N/A

**Are you working on it?**
No

**Comment by YoshithaRathnayake** [comment]
Shall I work on this?

**Comment by YoshithaRathnayake** [comment]
I think there is no data and in the button there is a css property as display none. Therefore, when we click the button it is hiding and nothing to show bcs there is no data @Piumal1999 
What do you think?

**Comment by YoshithaRathnayake** [comment]
![image](https://user-images.githubusercontent.com/97069900/231501615-72c6cd15-59fe-4e85-89a3-8c0ef551895d.png)

Here @Piumal1999 Its over from Janith Ayya

**Comment by YoshithaRathnayake** [comment]
@anjula-sack @Piumal1999 can you assign me?
