### ISSUE TITLE
Remove the functions related to loading upcoming onelive events

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#1561]
**Is your feature request related to a problem? Please describe.**
Since the onelive program is discontinued, we can remove the functions associated with loading upcoming onelive event

**Describe the solution you'd like**
Remove this function and its usages:
https://github.com/sef-global/sef-site/blob/e7a5ae486c9398f3392b5348f636c2adabd53f3d/onelive/functions.js#L2
https://github.com/sef-global/sef-site/blob/e7a5ae486c9398f3392b5348f636c2adabd53f3d/onelive/index.html#L351

Remove this upcoming-events template as well: https://github.com/sef-global/sef-site/blob/e7a5ae486c9398f3392b5348f636c2adabd53f3d/onelive/index.html#L331

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Are you working on it?**
No

**Comment by chirandevinda** [comment]
can I do this?

**Comment by Piumal1999** [comment]
Sure, assigned @chirandevinda
