### ISSUE TITLE
Update the onelive youtube API url

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#1562]
**Is your feature request related to a problem? Please describe.**
sef-dataholder is now deployed on dataholder.sefglobal.org. So, we need to update the related URLs.

**Describe the solution you'd like**
Update the youtube API Url here:
https://github.com/sef-global/sef-site/blob/e7a5ae486c9398f3392b5348f636c2adabd53f3d/onelive/functions.js#L53
https://github.com/sef-global/sef-site/blob/e7a5ae486c9398f3392b5348f636c2adabd53f3d/onelive/archive/functions.js#L5

The new URL is : `https://dataholder.sefglobal.org/youtube/onelive?maxResults=3`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Are you working on it?**
No

**Comment by gpsakthivel** [comment]
Hi @Piumal1999, Can I take this issue and work on it?

**Comment by Piumal1999** [comment]
Sure @gpsakthivel Go ahead

**Comment by gpsakthivel** [comment]
Thanks brother @Piumal1999

**Comment by gpsakthivel** [comment]
Hi @Piumal1999, Changes are done.
Attaching PR link for reference: https://github.com/sef-global/sef-site/pull/1565
