### ISSUE TITLE
Add the apply as a mentee button to the ScholarX 

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#1563]
**Is your feature request related to a problem? Please describe.**
- We need to add the apply as a mentee button

**Describe the solution you'd like**
- Rename the Join the mentee waiting list button to apply as a mentee
- Link it to https://scholarx.sefglobal.org/
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/43912578/232234030-ccad060d-56ca-4ccc-b89d-fffb095f6166.png">

**Are you working on it?**
No

**Comment by Sanjana0823** [comment]
I like to work on this.
