### ISSUE TITLE
Improvement in Footer

### ISSUE THREAD

**Issue by rahulrana701** [sef-global/sef-site#1568]
the footer is unnecessarily having left spacing when we are looking at smaller devices , it would be better if they are aligned properly...
 
<img width="151" alt="Screenshot 2023-04-18 205927" src="https://user-images.githubusercontent.com/123585591/232828669-4b00f3e4-b153-4f48-90c9-52f3101c5b67.png">
this looks better than above one..
<img width="139" alt="Screenshot 2023-04-18 210109" src="https://user-images.githubusercontent.com/123585591/232828672-e24f696d-80d8-40cd-b333-e5606097bef1.png">

**Comment by rahulrana701** [comment]
hi @Piumal1999 you can assign this issue to me , I can work on this issue...

**Comment by rahulrana701** [comment]
hi @Piumal1999 are you still maintaining this project....

**Comment by YoshithaRathnayake** [comment]
#1331 @RahulRana701 It will fix from this I think
