### ISSUE TITLE
Remove the apply as a mentee button

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#1573]
**Is your feature request related to a problem? Please describe.**
- We need to remove the apply as a mentee button since the applications are closed

<img width="553" alt="image" src="https://github.com/sef-global/sef-site/assets/43912578/01198451-952d-461e-828f-1df13bf536c7">

**Describe the solution you'd like**
- Remove the apply as a mentee button
- Update the description with the following

> Are you a skilled young individual who needs a little push in the right direction? We got you covered. With our premium free mentoring program, you too can get insight into the industry of your choosing and get mentored under highly qualified industrial experts. Reach us via [sustainableedufoundation@gmail.com](mailto:sustainableedufoundation@gmail.com)

**Are you working on it?**
No

**Comment by Sanjana0823** [comment]
I would like to work on this.
