### ISSUE TITLE
Remove Profile repetition in ScholarX Archive

### ISSUE THREAD

**Issue by janithlahirukariyawasam** [sef-global/sef-site#1575]
**Describe the bug**
Currently there is a profile duplication issue we faced in ScholarX archive mentors page.

**To Reproduce**
1. Go to ScholarX Archive
2. Click on the Mentors section
3. See the error

**Expected behavior**
Remove the profile repetition.

**Additional context**
No.

**Are you working on it?**
Yes

**Comment by janithlahirukariyawasam** [comment]
Can you assign me?

**Comment by Isuru4043** [comment]
@janithlahirukariyawasam are you working on this?

**Comment by janithlahirukariyawasam** [comment]
> @janithlahirukariyawasam are you working on this?

No

**Comment by RamithaHeshan33** [comment]
@anjula-sack @YoshithaRathnayake can you assign me to do this?
