### ISSUE TITLE
Use CheckBoxes to implement Mentor/Mentee Dropdown

### ISSUE THREAD

**Issue by janithlahirukariyawasam** [sef-global/sef-site#1576]
**Describe the bug**
Currently, we use a dropdown to manage mentor/mentee sections on ScholarX archive. But we have to use checkboxes instead of dropdown

**To Reproduce**
1. Go to ScholarX archive
2. See error

**Expected behavior**
Able to manage mentor/mentee sections using checkboxes instead of dropdowns.

**Additional context**
No

**Are you working on it?**
Yes

**Comment by janithlahirukariyawasam** [comment]
Can you assign me?

**Comment by janithlahirukariyawasam** [comment]
@YoshithaRathnayake can you work on this?

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake can you work on this?

Sure @janithlahirukariyawasam

**Comment by Piumal1999** [comment]
@janithlahirukariyawasam Do we display both mentors and mentees if both checkboxes are checked?

**Comment by janithlahirukariyawasam** [comment]
> @janithlahirukariyawasam Do we display both mentors and mentees if both checkboxes are checked?

We need to avoid that Piumal
