### ISSUE TITLE
Make the necessary links to open in a new tab in the the Readme.md file

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-site#1583]
**Is your feature request related to a problem? Please describe.**
Currently, all the links in the readme.md file are opening in the same window

**Describe the solution you'd like**
Make the necessary links to open in a new tab in the the Readme.md file

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this?

**Comment by Nelka97** [comment]
I'd like to work on this.

**Comment by anjula-sack** [comment]
@YoshithaRathnayake are you working on this?

**Comment by Nelka97** [comment]
Any updates? Shall I work on this

**Comment by anjula-sack** [comment]
> Any updates? Shall I work on this

Go ahead @Nelka97

**Comment by Nelka97** [comment]
Thank you

**Comment by Nelka97** [comment]
Hi @anjula-sack, I tried to make it work using HTML anchor tag, but it doesn't work in Github. Do you know any other method?

**Comment by anjula-sack** [comment]
> Hi @anjula-sack, I tried to make it work using HTML anchor tag, but it doesn't work in Github. Do you know any other method?

Can you try it like this? @Nelka97 

```markdown
[Link Text](URL "Title" target="_blank")
```

Here's an example:

```markdown
[Visit Example Website](https://www.example.com "Example Website" target="_blank")
```

**Comment by Nelka97** [comment]
Thank you @anjula-sack. I will try it.

**Comment by Nelka97** [comment]
Looks like it doesn't work. I also came across this thread : https://stackoverflow.com/a/42156438/10317115

**Comment by anjula-sack** [comment]
> Looks like it doesn't work. I also came across this thread : https://stackoverflow.com/a/42156438/10317115

oh, I think we can close this issue @Nelka97.  Some people actually prefer opening the links in the same tab as well. You can work on another issue.
