### ISSUE TITLE
Update the new leaderboard link in the readme.md file

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-site#1584]
**Is your feature request related to a problem? Please describe.**
Currently, there is the old leaderboard link in the readme.md file

**Describe the solution you'd like**
Update the new leaderboard link in the readme.md file

**Additional context**
![image](https://github.com/sef-global/sef-site/assets/97069900/8e3fc738-9455-4081-bbdf-53ac08b2b902)

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this?

**Comment by Nelka97** [comment]
I'd like to work on this

**Comment by Nelka97** [comment]
Any updates? Shall I work on this

**Comment by anjula-sack** [comment]
Hi @Nelka97, You can work on this.

**Comment by anjula-sack** [comment]
@Nelka97 What is the status of this?

**Comment by anjula-sack** [comment]
Hi @Nelka97, Are you working on this?

**Comment by Nelka97** [comment]
Yes @anjula-sack. Sorry for the delay. I have an issue with my PC.

**Comment by anjula-sack** [comment]
> Yes @anjula-sack. Sorry for the delay. I have an issue with my PC.

No worries
