### ISSUE TITLE
Change AcademiX page link in engineering-team page

### ISSUE THREAD

**Issue by sathsarabandaraj** [sef-global/sef-site#1587]
**Describe the bug**
Link to the AcademiX page in https://sefglobal.org/engineering-team/

**To Reproduce**
1. Go to https://sefglobal.org/engineering-team/
2. Check the link to AcademiX page [ currently linked to [https://sef-academix.herokuapp.com/](https://sef-academix.herokuapp.com/) ]

**Expected behaviour**
Go to https://academix.sefglobal.org/ on button click

**Screenshots**
![image](https://github.com/sef-global/sef-site/assets/62067185/0ed8237c-1f3b-4e3f-9c84-b3b818707415)

**Are you working on it?**
No

**Comment by chamilwickramasinghe** [comment]
Shall I work on this

**Comment by anjula-sack** [comment]
Hey @chamilwickramasinghe, are you working on this?

**Comment by Nelka97** [comment]
Shall I work on this ?

**Comment by anjula-sack** [comment]
> Shall I work on this ?

Sure go ahead @Nelka97

**Comment by Nelka97** [comment]
Thank you

**Comment by anjula-sack** [comment]
@Nelka97 What is the status of this?
