### ISSUE TITLE
Fix the images on the blog cards

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-site#1591]
**Describe the bug**
Currently, the images appear stretched and it would be better to have them properly cropped.

**To Reproduce**
1. Go to 'https://sefglobal.org/engineering-team/'
2. Scroll down to 'Blog Articles from Our Engineers'
3. See error

**Expected behavior**
Fix the images on the blog cards using bootstrap

**Screenshots**
![image](https://github.com/sef-global/sef-site/assets/97069900/ed21c2fa-a2ce-42fe-bc24-cd6d865eb1b5)

**Comment by YoshithaRathnayake** [comment]
@jayasanka-sack this is the issue u wanted to create right?

**Comment by jayasanka-sack** [comment]
@YoshithaRathnayake Mmm… I cannot recall.

**Comment by jayasanka-sack** [comment]
Anyway, this is a good catch! This needs to be fixed

**Comment by Isuru4043** [comment]
Shall I work on this?

**Comment by mkskaushalya** [comment]
Hello @YoshithaRathnayake, I can fix this issue.

When inserting an image here, instead of inserting it directly, please insert it into a div with a fixed size and give the correct size to that div. This issue can be solved.

![image](https://github.com/sef-global/sef-site/assets/87746596/30e9b0e7-c588-47cf-bd1d-5db0ab942a86)

**Comment by YoshithaRathnayake** [comment]
> Hello @YoshithaRathnayake, I can fix this issue.
> 
> When inserting an image here, instead of inserting it directly, please insert it into a div with a fixed size and give the correct size to that div. This issue can be solved.
> 
> ![image](https://private-user-images.githubusercontent.com/87746596/324576401-30e9b0e7-c588-47cf-bd1d-5db0ab942a86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NjAwMjEsIm5iZiI6MTcxMzg1OTcyMSwicGF0aCI6Ii84Nzc0NjU5Ni8zMjQ1NzY0MDEtMzBlOWIwZTctYzU4OC00N2NmLWJkMWQtNWRiMGFiOTQyYTg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA4MDg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3ZTAyNGFjMTEwYjk3YjQwNGQ3ZWIxNjIxYWIzYjdkMThmMWRiMzRiZGJlNDU3NWMwMDEyYWZiNDlmOGMzOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AtgfNrbJ7qp1zXZK3Uks64NsrOOUu2hhS_TNjtxYefY)

If I assign you can you fix it? @mkskaushalya

**Comment by ifham-mohamed** [comment]
Hi @anjula-sack @YoshithaRathnayake !

This is the issue which is I solved & here's the PR of it #1623
