### ISSUE TITLE
Link the join us button on the team page to the handbook

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#1601]
**Is your feature request related to a problem? Please describe.**
- We need to link the join us button on the team page to the handbook

**Describe the solution you'd like**
- Link the join us button on the SEF engineering team page to sef handbook.  The link is below

https://handbook.sefglobal.org/engineering-team/team/

**Are you working on it?**
No

**Comment by Sanjana0823** [comment]
I would like to work on this,
