### ISSUE TITLE
Link the "Learn More" button on the Join Us page to the handbook

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-site#1606]
**Is your feature request related to a problem? Please describe.**
- We need to link the `Learn More` button on the Join Us page to the handbook

**Describe the solution you'd like**
- Link the "Learn More" button on the SEF Join the Team page to sef handbook.  The link is below

https://handbook.sefglobal.org/engineering-team/team

**Are you working on it?**
No

**Comment by ChamodP** [comment]
i'd like to work on this

**Comment by YoshithaRathnayake** [comment]
> i'd like to work on this

Sure, go ahead @ChamodP
