### ISSUE TITLE
Decrease the engineering team page width

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-site#1608]
**Describe the bug**
Currently, the width of the engineering page is increased

**To Reproduce**
1. Go to ['Engineering Team Page'](https://sefglobal.org/engineering-team/)
2. See error

**Expected behavior**
Decrease the width of the engineering team page

**Screenshots**
![image](https://github.com/sef-global/sef-site/assets/97069900/73374bb7-ac1b-4ded-92af-6850cd9923e1)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [Latest]

**Additional context**
I noticed that it will disappear when I click the "See More" button in Blog Articles from Our Engineers section

Before
![image](https://github.com/sef-global/sef-site/assets/97069900/c49b214b-0a34-4d8b-aebe-6bdbb1d827e9)

After
![image](https://github.com/sef-global/sef-site/assets/97069900/55c88e31-c740-4d0c-9535-b52a3c263b76)

**Are you working on it?**
No

**Comment by Isuru4043** [comment]
shall I work on this?

**Comment by Madhawa97** [comment]
Sure
