### ISSUE TITLE
Fix the profile image not loading issue in Blog Articles section on the Engineering Team page

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-site#1609]
**Describe the bug**
Currently, the profile image not loading issue in Blog Articles section on the Engineering Team page

`Eg: In the below screenshot the Piumal Rathnayake's profile image is not loaded

**To Reproduce**
1. Go to ['Engineering Team Page'](https://sefglobal.org/engineering-team/)
2. Scroll down to 'Blog Articles from Our Engineers Section'
3. See error

**Expected behavior**
Fix the profile image not loading issue in Blog Articles section on the Engineering Team page

**Screenshots**
![image](https://github.com/sef-global/sef-site/assets/97069900/f37c50eb-0906-4f66-8d21-0842d26257d7)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [Latest]

**Are you working on it?**
No

**Comment by elkhechafi** [comment]
can you assign to me this issue please, I want to contribute

**Comment by Isuru4043** [comment]
shall I work on this @YoshithaRathnayake

**Comment by Isuru4043** [comment]
@YoshithaRathnayake  shall I work on this?

**Comment by mayura-andrew** [comment]
@Isuru4043 sorry for the late response. Yes, you can go on this issue 🚀

**Comment by Isuru4043** [comment]
I am also sorry for the late response.  I found out where the bug happened.

![Screenshot 2024-04-13 183753](https://github.com/sef-global/sef-site/assets/85481462/56fc3af1-2155-4e27-9f5b-5582bc2cb326)

![Screenshot 2024-04-13 183922](https://github.com/sef-global/sef-site/assets/85481462/bb529c4d-ae6d-4290-bb5d-a584d32c01b1)

I think the URL, which is underlined in blue is invalid. But I don't have access to change the URL. I think only maintainers have access.

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake shall I work on this?

Oh yeah you can, sorry for the late reply. I was little bit busy these days sure you can go ahead @Isuru4043

**Comment by Isuru4043** [comment]
@YoshithaRathnayake No worries, but I don't have access to change the URL as I mentioned in the previous comment. I think only maintainers have access to change the URL.

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake No worries, but I don't have access to change the URL as I mentioned in the previous comment. I think only maintainers have access to change the URL.

It is in which file? @Isuru4043

**Comment by Isuru4043** [comment]
@YoshithaRathnayake It is in sef-site\engineering-team\index.html

**Comment by YoshithaRathnayake** [comment]
https://github.com/sef-global/sef-site/blob/master/engineering-team/index.html
This file ? @Isuru4043

**Comment by Isuru4043** [comment]
@YoshithaRathnayake yes, this is the file. Also the link of Google Apps script that needs to be changed is on the 328th line.

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake yes, this is the file. Also the link of Google Apps script that needs to be changed is on the 328th line.

Ah you are telling the you don't have access for that Google Apps script? @Isuru4043 
Can you send me that file link I'll ask from @anjula-sack and let you know

**Comment by Isuru4043** [comment]
@YoshithaRathnayake Yeah , you got it.  https://script.google.com/macros/s/AKfycbyUdfhk9WWFLoMWxQvNIEUNl793RbXGnyo-ZIYRn9K1T6QFN1_9G8Ln9NpTCCJba2dzOg/exec   this is the link of google apps script I don't have access to change to

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake Yeah , you got it. https://script.google.com/macros/s/AKfycbyUdfhk9WWFLoMWxQvNIEUNl793RbXGnyo-ZIYRn9K1T6QFN1_9G8Ln9NpTCCJba2dzOg/exec this is the link of google apps script I don't have access to change to

Ok sure I'll ask and lyk @Isuru4043

**Comment by Isuru4043** [comment]
@YoshithaRathnayake ok, thank you so much

**Comment by anjula-sack** [comment]
@Isuru4043 Can you find his medium profile image? Then I can update the sheet.

**Comment by Isuru4043** [comment]
https://miro.medium.com/v2/resize:fill:96:96/1*glWfICYlbi8RfQHIWN8xOQ.jpeg   this is the URL for his medium profile image. @anjula-sack

**Comment by anjula-sack** [comment]
@Isuru4043 Thank you for figuring out the issue. I changed the URL. If you are interested you can work on issue in the following repositories.

https://github.com/sef-global/scholarx-frontend/issues
https://github.com/sef-global/scholarx-backend/issues
