### ISSUE TITLE
Fix the "Learn More" button link on the Join Us page opening in the same page

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-site#1612]
**Is your feature request related to a problem? Please describe.**
Currently, the "Learn More" button link on the Join Us page is opening in the same page

**Describe the solution you'd like**
Fix the "Learn More" button link on the Join Us page opening in the same page

**Are you working on it?**
No

**Comment by YoshithaRathnayake** [comment]
Still any one didn't ask to work on this @anjula-sack ? So shall I work on this

**Comment by Sanjana0823** [comment]
I would like to work on this.

**Comment by YoshithaRathnayake** [comment]
> I would like to work on this.

Sure @Sanjana0319

**Comment by RamithaHeshan33** [comment]
@YoshithaRathnayake  Can you assign me to this issue

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake Can you assign me to this issue

Sure @RamithaHeshan33
