### ISSUE TITLE
Update the scholarX mentoring hours in the project sections

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#1614]
**Is your feature request related to a problem? Please describe.**
We need to update the number of hours in the scholars project card

**Describe the solution you'd like**
- Go to the home page and location the project cards
- Change the hours to 2500+ to 5000+
<img width="369" alt="image" src="https://github.com/sef-global/sef-site/assets/43912578/da60bae8-ded3-4cb1-b781-e845339f85f3">

**Are you working on it?**
No

**Comment by Michila0** [comment]
did it
