### ISSUE TITLE
Justifying the paragraphs in ScholarX 2023

### ISSUE THREAD

**Issue by RamithaHeshan33** [sef-global/sef-site#1618]
### Is your feature request related to a problem? Please describe.
On the [ScholarX](https://sefglobal.org/scholarx/2023/) web page, only the paragraph related to the topic "Take part as a mentee under ScholarX23" has been justified, and the paragraphs related to other topics have not been justified.

### Describe the solution you'd like
Justifying the two paragraphs related to the remaining two topics

### Additional context
**Before Fixing the Issue**
![before1](https://github.com/sef-global/sef-site/assets/142712365/3f44503f-0e41-4772-8443-ac66765b7d38)
![before2](https://github.com/sef-global/sef-site/assets/142712365/d225feba-f2d3-44ce-a75e-51dcae29d4ca)

**After Fixing the Issue**
![after1](https://github.com/sef-global/sef-site/assets/142712365/443f1ffb-a728-4c9b-9e80-7ab3761b72a8)
![after2](https://github.com/sef-global/sef-site/assets/142712365/344a05bc-1be1-4696-a99a-9f96a3419606)

### Are you working on it?
Yes

**Comment by RamithaHeshan33** [comment]
Can you assign me...?

**Comment by YoshithaRathnayake** [comment]
> Can you assign me...?

Yeah sure! @RamithaHeshan33

**Comment by YoshithaRathnayake** [comment]
@anjula-sack ?
