### ISSUE TITLE
Updating the SEE MORE button on the IRC page

### ISSUE THREAD

**Issue by RamithaHeshan33** [sef-global/sef-site#1624]
**Is your feature request related to a problem? Please describe.**
In the Researchers section of the [IRC](https://sefglobal.org/irc.html) page, when the user clicks the SEE MORE button, all researchers are displayed on the screen.

**Describe the solution you'd like**
Since there are many researchers, setting 8 researchers to appear on the screen when the user presses the SEE MORE button.

**Additional context**
Suggested solution

https://github.com/sef-global/sef-site/assets/142712365/d0eb9b27-c35a-4062-b238-396d2e85ad29

**Are you working on it?**
Yes

**Comment by RamithaHeshan33** [comment]
If it should be updated like this, @YoshithaRathnayake can you assign me to this?

**Comment by YoshithaRathnayake** [comment]
> If it should be updated like this, @YoshithaRathnayake can you assign me to this?

Yeah cool! @RamithaHeshan33 
@anjula-sack what about you, it will look better noh?

**Comment by anjula-sack** [comment]
> > If it should be updated like this, @YoshithaRathnayake can you assign me to this?
> 
> Yeah cool! @RamithaHeshan33 @anjula-sack what about you, it will look better noh?

yeah go ahead @RamithaHeshan33
