### ISSUE TITLE
Increase responsive of the footer

### ISSUE THREAD

**Issue by ifham-mohamed** [sef-global/sef-site#1626]
**Describe the bug**
when we use under 1024px with of screen the footer part is not much responsive 

**To Reproduce**
1. Go to https://sefglobal.org/
2. Click on Home or stay on Home
3. Scroll down up to the footer

**Expected behavior**
Footer should be responsive for all the screen size of devices

**Screenshots**

https://github.com/sef-global/sef-site/assets/141899095/bf2d8e85-b784-4736-80fc-a30bef197084

**Desktop :**
 - OS: Windows
 - Browser: Edge
 - Version 125.0.2535.37 (Official build) stable app, beta channel (64-bit)

**Are you working on it?**
Yes

**Comment by ifham-mohamed** [comment]
Hi @anjula-sack !

Here's that issue #1626 in the footer section

**Comment by mkskaushalya** [comment]
@ifhammohamed1111 I can fix this issue. Can you assign me?

**Comment by YoshithaRathnayake** [comment]
Here @ifhammohamed1111 @mkskaushalya this issue is fixed by this PR #1207 so I think no need of this once again noh?

**Comment by ifham-mohamed** [comment]
> Here @ifhammohamed1111 @mkskaushalya this issue is fixed by this PR #1207 so I think no need of this once again noh?

ohhh @YoshithaRathnayake i just show that PR and its struck with the merge conflict. 

Then what about #1431 shall I ?

**Comment by mkskaushalya** [comment]
> > Here @ifhammohamed1111 @mkskaushalya this issue is fixed by this PR #1207 so I think no need of this once again noh?
> 
> ohhh @YoshithaRathnayake i just show that PR and its struck with the merge conflict.
> 
> Then what about #1431 shall I ?

@ifhammohamed1111  I don't think this is resolved yet. I can make it more responsive than this.

![image](https://github.com/sef-global/sef-site/assets/87746596/b8321bfc-6374-45bf-869b-534565e3b83e)

The footer section should be updated here, including social media links and captions.

**Comment by YoshithaRathnayake** [comment]
> > > Here @ifhammohamed1111 @mkskaushalya this issue is fixed by this PR #1207 so I think no need of this once again noh?
> > 
> > 
> > ohhh @YoshithaRathnayake i just show that PR and its struck with the merge conflict.
> > Then what about #1431 shall I ?
> 
> @ifhammohamed1111 I don't think this is resolved yet. I can make it more responsive than this.
> 
> ![image](https://private-user-images.githubusercontent.com/87746596/330153682-b8321bfc-6374-45bf-869b-534565e3b83e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MjI1NjcsIm5iZiI6MTcxNTYyMjI2NywicGF0aCI6Ii84Nzc0NjU5Ni8zMzAxNTM2ODItYjgzMjFiZmMtNjM3NC00NWJmLTg2OWItNTM0NTY1ZTNiODNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDE3NDQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4YmFjNzI3ODE5ZGFkMTEzZTljN2VhYmI1MDU5NzIyY2U4MDBlYjZjZGI3NWM3YmRkMTYxNjAzYzcxODg4YmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hsZGtLUOL_ATpGSWxnoJj6oU9T9zL6outCkSk5VLwWI)
> 
> The footer section should be updated here, including social media links and captions.

You can try another issue @mkskaushalya

**Comment by YoshithaRathnayake** [comment]
> > Here @ifhammohamed1111 @mkskaushalya this issue is fixed by this PR #1207 so I think no need of this once again noh?
> 
> ohhh @YoshithaRathnayake i just show that PR and its struck with the merge conflict.
> 
> Then what about #1431 shall I ?

Will see most probably I will work on that! And you too try to find more issues and work on those @mkskaushalya @ifhammohamed1111 
And sorry for the inconvenience occurred @mkskaushalya @ifhammohamed1111

**Comment by ifham-mohamed** [comment]
yeah sure @YoshithaRathnayake 😊!

> > > Here @ifhammohamed1111 @mkskaushalya this issue is fixed by this PR #1207 so I think no need of this once again noh?
> > 
> > 
> > ohhh @YoshithaRathnayake i just show that PR and its struck with the merge conflict.
> > Then what about #1431 shall I ?
> 
> Will see most probably I will work on that! And you too try to find more issues and work on those @mkskaushalya @ifhammohamed1111 And sorry for the inconvenience occurred @mkskaushalya @ifhammohamed1111

Yeah sure @YoshithaRathnayake 😊!

**Comment by mkskaushalya** [comment]
> > > Here @ifhammohamed1111 @mkskaushalya this issue is fixed by this PR #1207 so I think no need of this once again noh?
> > 
> > 
> > ohhh @YoshithaRathnayake i just show that PR and its struck with the merge conflict.
> > Then what about #1431 shall I ?
> 
> Will see most probably I will work on that! And you too try to find more issues and work on those @mkskaushalya @ifhammohamed1111 And sorry for the inconvenience occurred @mkskaushalya @ifhammohamed1111

OK machn 🙌
