### ISSUE TITLE
Responsive issue in scholarx/past-programs card-deck

### ISSUE THREAD

**Issue by mkskaushalya** [sef-global/sef-site#1627]
**Describe the bug**
The cards at the bottom of scholarx/past-programs on your website are not responsive. And that section has no padding in the mobile view. The row-gap between cards is also not available in the tablet view.

**To Reproduce**
1. Go to [scholarx/past-programs](https://sefglobal.org/scholarx/past-programs/#past-scholarx) on [sefglobal](https://sefglobal.org/).
2. Change the screen size so that the screen size becomes small (768px>screen size>576px)
3. See error
4. Change the screen size so that the screen size becomes small (576px>screen size>0px)
5. See an error

**Expected behavior**
This card-deck section is made of a flex box. I would like to change its CSS and make it more responsive.

**Screenshots**
![image](https://github.com/sef-global/sef-site/assets/87746596/9c498b2d-3a7a-49a5-9834-bd0fb54c0f91)
![image](https://github.com/sef-global/sef-site/assets/87746596/3b5d9f64-f9e4-4ef1-bcac-a4ea7755361c)

**Desktop:**
 - OS: Windows 11
 - Browser: Google Chrome
 - Version: 124.0.6367.202 (Official Build) (64-bit)

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Nicee! Go ahead @mkskaushalya
