### ISSUE TITLE
Setting counting number feature on Our Project Section

### ISSUE THREAD

**Issue by RamithaHeshan33** [sef-global/sef-site#1629]
**Is your feature request related to a problem? Please describe.**
Setting counting feature on [Our Project](https://sefglobal.org/) section 

**Describe the solution you'd like**
Update index.html file

**Additional context**

https://github.com/sef-global/sef-site/assets/142712365/dbc22452-2994-4efc-99b6-85d6959228ea

**Are you working on it?**
Yes

**Comment by RamithaHeshan33** [comment]
If it should be updated like this, @YoshithaRathnayake can you assign me to this?

**Comment by YoshithaRathnayake** [comment]
> If it should be updated like this, @YoshithaRathnayake can you assign me to this?

Hmm, looks good for me @RamithaHeshan33 
@anjula-sack shall we?

**Comment by YoshithaRathnayake** [comment]
Go ahead! @RamithaHeshan33
