### ISSUE TITLE
Navbar of AcadeMix page should be same as the homepage 

### ISSUE THREAD

**Issue by NigeeHettige** [sef-global/sef-site#1631]
**Describe the bug**
The Navbar of the Academix page looks different. The font size Alignments and styles are different compared to other pages. Not only that also the content of the navbar is also different.

**To Reproduce**
1. Go to 'Initiatives'
2. Click on 'AcadeMix.'
3. See error

**Expected behavior**
The navbar should be the same as the home page and when clicking on the initiatives it should be able to drop down the initiatives which are in this page.

**Screenshots**
![image](https://github.com/sef-global/sef-site/assets/135543588/06d38c0e-f436-4a9d-89eb-0a73e4d82782)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by anjula-sack** [comment]
Hi @NigeeHettige, Thank you for raising the issue. However, AcademiX is a different application and not a part of the site. We are currently not maintaining that project so this is okay.
