### ISSUE TITLE
Remove the timeline from ScholarX page

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#1632]
**Is your feature request related to a problem? Please describe.**
- The timeline in the ScholarX page needs to be removed

**Describe the solution you'd like**
- Remove the timeline

https://sefglobal.org/scholarx/2023/

**Are you working on it?**
No

**Comment by Dilini-457** [comment]
@anjula-sack I would like to work on this

**Comment by anjula-sack** [comment]
Any updates @Dilini-457?

**Comment by YoshithaRathnayake** [comment]
> Any updates @Dilini-457?

Does this need to be done quickly? @anjula-sack
