### ISSUE TITLE
Add a button to got to scholarx on the new scholarx page

### ISSUE THREAD

**Issue by mayura-andrew** [sef-global/sef-site#1635]
**Is your feature request related to a problem? Please describe.**
Currently, there is no direct way to navigate from the ScholarX 2023 page to the new ScholarX platform. This can cause confusion and inconvenience for users looking to access the updated platform.

**Describe the solution you'd like**
Add a button on the https://sefglobal.org/scholarx/2023/ page that directs users to the new ScholarX platform at https://scholarx.sefglobal.org/.

**Describe alternatives you've considered**

**Additional context**

Here is an image showing the current ScholarX 2023 page where the new button should be added:

![image](https://github.com/sef-global/sef-site/assets/48531182/126d999b-7cb6-46e3-b524-bf91f98ecc32)

**Are you working on it?**
No

**Comment by kamalchakma1** [comment]
Hi @mayura-andrew can i work on this?

**Comment by mayura-andrew** [comment]
@kamalchakma1 Hi, yeah sure go head

**Comment by kamalchakma1** [comment]
ok @mayura-andrew,  can you assign it to me?

**Comment by mayura-andrew** [comment]
okay give me time

**Comment by kamalchakma1** [comment]
Thanks. I have created a pull request but got some errors. can you guide me what its happening or I have create new pull request.

**Comment by kamalchakma1** [comment]
Hi @mayura-andrew sorry I mistakenly closed previous PR. And I created new PR with updated readme , preview link and also added screenshot.
