### ISSUE TITLE
Validate the social media links

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#169]
- [ ] Validate the social media links added to the people in all pages

**Comment by jeevanthask** [comment]
I will do this

**Comment by jeevanthask** [comment]
done

**Comment by Piumal1999** [comment]
Well done!

**Comment by Piumal1999** [comment]
All links are correct. Right?
@jeevanthask

**Comment by jeevanthask** [comment]
yes!! but found some people without twitter accounts
