### ISSUE TITLE
Port everything to JSON

### ISSUE THREAD

**Issue by akshika47** [sef-global/sef-site#170]
At the moment most of our website content are hard coded to the page. This hard coupling would not be practical in the long term. Therefore, we need to port the text information in to JSON files so we can move them to our new website after it is built and at the same time have information to be used in the current version of the website!

@Piumal1999 You might have to split this issue in to sub tasks as this could be a larger task!

**Comment by Piumal1999** [comment]
I'll do it

**Comment by akshika47** [comment]
Great!!

**Comment by akshika47** [comment]
@Piumal1999 Do you wanna break this in to sub issues? I feel if we do it page by page. It would be much more easier and easy to track. But it is up to you. You can decide on the best way to tackle this question.

**Comment by Piumal1999** [comment]
| **Sub Issue** | **Issue no.** |
| ------------- | ------------- |
| Alumni Page | #173 |
| Team Page | #174 |
| About Us Page | #175 |
| Contact Page | #176 |
| Contribute Page | #177 |
| Home Page | #178 |

**Comment by Piumal1999** [comment]
Good job! Thank you @jeevanthask & @yohanym95

**Comment by akshika47** [comment]
Good Job Team!
