### ISSUE TITLE
Complete the Alumni

### ISSUE THREAD

**Issue by akshika47** [sef-global/sef-site#172]
Please expand this issue!

**Comment by yohanym95** [comment]
i will do this. but Also want details of  alumni page(new members).

**Comment by akshika47** [comment]
@yohanym95 could you speak to @hasitha95 or Tharika. Either of them should be able to give you the details.

This issue comes with the JSON port as well. So all the information should stored as a JSON file!

**Comment by yohanym95** [comment]
@Piumal1999 and @jayasanka-sack still didnt get a complete one to this issue.

**Comment by Piumal1999** [comment]
Thanks a lot! @yohanym95

**Comment by akshika47** [comment]
I added changes to this on the Trello board @Piumal1999

**Comment by Piumal1999** [comment]
@jeevanthask How much progress have we made?
