### ISSUE TITLE
Implement the UI of SA Landing Page

### ISSUE THREAD

**Issue by janithRS** [sef-global/sef-site#243]
Implement the UI of SA Landing Page based on the provided wireframe

**Comment by jayasanka-sack** [comment]
@Piumal1999 any updates on this?

**Comment by Piumal1999** [comment]
Nandika is working on this. I'll check the updates.
Cc: @jeevanthask

**Comment by jayasanka-sack** [comment]
Closing the issue since this issue has been divided to sub issues
