### ISSUE TITLE
Make amendments to FAQ component for a better mobile veiw

### ISSUE THREAD

**Issue by Gravewalker666** [sef-global/sef-site#278]
Existing FAQ component does not align well in the mobile view 

## Detailed Description
Redeveloping FAQ component in a more responsive way

## Context
It's necessary to be a responsive component  

## Your Environment

* Version used: Ubuntu 19.02, Apache2
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Chrome mobile view
* Link to your project: https://github.com/sef-global/sef-site/blob/master/src/main/webapp/examples/components.html

**Comment by jayasanka-sack** [comment]
`<!- Provide a general summary of the issue in the Title above ->`
Means provide a better **title** for the issue. Do not write under this comment.
