### ISSUE TITLE
Animation for loading profiles

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#279]
Need an animation for loading profile cards

## Detailed Description
It's good if we can add an animation to load the profile cards when the "SEE MORE" button on the team section is clicked.

## Context
It's important for a better user experience

## Possible Implementation
Use JQuery.

## Your Environment
* Version used:
* Browser Name and version: Google Chrome 
* Operating System and version (desktop or mobile): Ubuntu 19.04
* Link to your project:

**Comment by Piumal1999** [comment]
PR #280

**Comment by jayasanka-sack** [comment]
<!- Provide a general summary of the issue in the Title above ->
Means provide a better title for the issue. Do not write under this comment.
