### ISSUE TITLE
Rewrite bad CSS rules in global css file

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#281]
## Detailed Description

The existing custom CSS rules in `global.custom.css` is not well written. 
These are the issues with the current file,
- Bad class names
- Directly overriding theme's component without context
- No proper comments 

## Context

Keep using good programming practices makes future development easy.

## Possible Implementation

Rewrite `global-custom.css` file & update components page according to the rewritten rules.

## Your Environment
N/A

**Comment by Piumal1999** [comment]
Thanks @jayasanka-sack
