### ISSUE TITLE
Issues with the size and the hover action of profile cards

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#283]
## Detailed Description
The sizes of the profile cards are bigger than the expected size. And the hover function is not working

## Context
The component is used on every page. So it's urgent to resolve this issue.

## Possible Implementation
Issues with the CSS code

## Your Environment

* Version used: 
* Browser Name and version: Google Chrome
* Operating System and version (desktop or mobile): Ubuntu 19.04
* Link to your project:

## Screenshots
Current design
![Sustainable_Education_Foundation_-_2019-12-14_13 04 25](https://user-images.githubusercontent.com/27498587/70845406-4cb21400-1e74-11ea-9c1b-5e4ae67e1fda.png)

Correct design
![Sustainable_Education_Foundation_-_2019-12-14_13 03 43](https://user-images.githubusercontent.com/27498587/70845416-66535b80-1e74-11ea-8966-0a59f4022507.png)

**Comment by jayasanka-sack** [comment]
@Piumal1999 I've changed the class name from `imgContainer` to `hover-profile-card`.
I guess that might be the issue.

**Comment by Piumal1999** [comment]
Solved PR #284  . Thanks, @jayasanka-sack .
