### ISSUE TITLE
Add links for buttons on Onelive page

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#287]
**Is your feature request related to a problem? Please describe.**
Some of the buttons on the Onelive page don't have links.

**Describe the solution you'd like**
Add the links and complete the page.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jayasanka-sack** [comment]
This isn't solved yet. Anyone can work on this

**Comment by anjula-sack** [comment]
I'm working on this.
