### ISSUE TITLE
Replace dummy content on every page

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#294]
**Is your feature request related to a problem? Please describe.**
Actual contents are not shown in some pages

**Describe the solution you'd like**
We have to replace all dummy content

**Describe alternatives you've considered**
N/A

**Additional context**
Refer this Document: https://docs.google.com/document/d/1YYMlMCytklQcpxPLoMNgRZkKcoj9heNN/edit#heading=h.gjdgxs

**Comment by jayasanka-sack** [comment]
@Piumal1999 better if we can divide this to multiple issues.
