### ISSUE TITLE
Fix the testimonial on home page

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#297]
**Describe the bug**
The two arrow buttons are not clearly visible in the testimonial component which is on the Home page

**To Reproduce**
1. Go to 'https://sef-global.github.io/sef-site/src/main/webapp/'
3. Scroll down to 'testimonial section'

**Expected behavior**
Buttons should be clearly visible. And rhe alignment also should be fixed

**Screenshots**
![IMG_20191224_201951](https://user-images.githubusercontent.com/27498587/71417496-8dd3d080-268b-11ea-8555-495003bf685e.jpg)

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04
 - Browser: Google Chrome

**Smartphone (please complete the following information):**
 - Device: Pocophone F1
 - OS: MIUI 11
 - Browser: Google Chrome

**Additional context**
N/A

**Comment by Gravewalker666** [comment]
I will do this task
