### ISSUE TITLE
Navbar button not displaying in mobile view

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#298]
**Describe the bug**
The navbar menu drop-down button is not displaying in the mobile view.

**To Reproduce**
1. Go to 'https://sef-global.github.io/sef-site/src/main/webapp/' 
2. Go to mobile view
3. See error

**Expected behavior**
Dropdown menu button should be appeared

**Screenshots**
![IMG_20191224_202846](https://user-images.githubusercontent.com/27498587/71419019-726cc380-2693-11ea-90fc-3be60a670df8.jpg)

**Desktop (please complete the following information):**
 N/A

**Smartphone (please complete the following information):**
 - Device: Pocophone F1
 - OS: MIUI 11
 - Browser: Google Chrome

**Additional context**
N/A

**Comment by yohanym95** [comment]
I'll do it.

**Comment by Bawanthathilan** [comment]
I am working on this

**Comment by jayasanka-sack** [comment]
Okay
