### ISSUE TITLE
Different spacing in Flagship Program logos

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#303]
**Describe the bug**
Flagship Program logos spacing is not equal in index.html page.

**To Reproduce**

1. Go to index.html
2. Scroll down to "Our flagship Programs section"

**Expected behavior**
![Screenshot 2019-12-26 at 16 34 28](https://user-images.githubusercontent.com/33048395/71473600-9cda9000-27fd-11ea-93d5-afd7af0895c4.jpg)
Replace onlive logo with this image. 
[one-live-logo.png](https://user-images.githubusercontent.com/33048395/71558278-5728fc00-2a77-11ea-95ca-4e5b0091064e.png)
(Do not delete exsiting file)

**Screenshots**
Current behavior
![Screenshot 2019-12-26 at 16 35 46](https://user-images.githubusercontent.com/33048395/71473633-c85d7a80-27fd-11ea-9b05-6d1baf28551c.jpg)

**Comment by janithRS** [comment]
logo : [https://drive.google.com/open?id=1oNZpnt1CUKBzc-UdGAbFdQyqz_C7vv24](url)
