### ISSUE TITLE
Remove unwanted section from the ScholarX page

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#319]
**Is your feature request related to a problem? Please describe.**
We don't need the section which is with 3 clock icons on the ScholarX page. A screenshot is given below.
![IMG_20200104_213023](https://user-images.githubusercontent.com/27498587/71768128-74f3d680-2f39-11ea-8c47-542a273c95a5.jpg)

**Describe the solution you'd like**
Remove the section and send us a PR

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by BhathiyaTK** [comment]
I'll fix this.

**Comment by BhathiyaTK** [comment]
Issue solved in #361 PR.

**Comment by anjula-sack** [comment]
May I work on this issue?

**Comment by Piumal1999** [comment]
Thank you @BhathiyaTK

**Comment by Piumal1999** [comment]
Thank you @BhathiyaTK
