### ISSUE TITLE
Highlight counts Section in the index page

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#323]
**Is your feature request related to a problem? Please describe.**
The counts' section in the `index.html` page is not highlighted properly. 

**Describe the solution you'd like**
Make it highlighted using an appropriate way.
Suggestions: 
- Making the texts bigger
- Making counts bolder

**Additional context**

Screenshot:
![Screenshot 2020-01-09 at 18 03 48](https://user-images.githubusercontent.com/33048395/72068164-65460a80-330a-11ea-85a5-817b948e0bff.jpg)

**Comment by ManojLL** [comment]
i'm working on this
