### ISSUE TITLE
Link flagship programs' tiles with the pages

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#324]
**Is your feature request related to a problem? Please describe.**
Currently, the flagship programs tiles in the `index.html` page are not linked to the pages.

**Describe the solution you'd like**
Link them with the appropriate pages.

**Additional context**
Screenshot: 
![Screenshot 2020-01-09 at 18 10 29](https://user-images.githubusercontent.com/33048395/72068547-5449c900-330b-11ea-95bf-49bf239b9726.jpg)

**Comment by anjula-sack** [comment]
I'm working on it.
