### ISSUE TITLE
Modify Students/Experts section

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#325]
**Is your feature request related to a problem? Please describe.**
The current implementation is a bit different than the original design. (Students/Experts section in index.html page)

**Describe the solution you'd like**
- Please make it similar to the provided design. (Should be similar to the provided design, colors, borders, font sizes, etc..)
- Set text alignment to justify.
- All the custom CSS rules should add to the `global-custom.css` file.

Design: 
![Screenshot 2020-01-09 at 18 25 09](https://user-images.githubusercontent.com/33048395/72069532-6167b780-330d-11ea-80a0-171a77ca5512.jpg)

**Comment by yohanym95** [comment]
i am working on this issue.

**Comment by yohanym95** [comment]
@jayasanka-sack  is volunteers section ok?

**Comment by jayasanka-sack** [comment]
The whole section should be the same as the design

**Comment by Gravewalker666** [comment]
May I give it a try?

**Comment by Piumal1999** [comment]
Is this one completed? @jayasanka-sack

**Comment by jayasanka-sack** [comment]
yes!
