### ISSUE TITLE
Add team members to the JSON file

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#326]
**Is your feature request related to a problem? Please describe.**
The `team.json` file is incomplete & images aren't in the repo. 

**Describe the solution you'd like**
1. Go to the team page on the published site. https://sefglobal.org/about/team.html
1. Download the profile images. Create a new directory named `profiles` on `assets/img/` directory & copy those images. (use short file names)
1. Add team members to the `assets/contents/json/team.json` file.

**Comment by anjula-sack** [comment]
I'm working on it.

**Comment by anjula-sack** [comment]
I'm working on it.
