### ISSUE TITLE
Make testimonial section similar to the design

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#327]
**Is your feature request related to a problem? Please describe.**
The testimonial section on `index.html` page is a bit different than the provided design.

**Describe the solution you'd like**
Make it similar to the design.
- Reduce profile image size
- Increase font size
- Make Person name bolder
- Change the position text's color to black

Design: 
![Screenshot 2020-01-09 at 18 50 03](https://user-images.githubusercontent.com/33048395/72071010-dbe60680-3310-11ea-931e-c62ba3194ff0.jpg)

**Additional context**
Do not remove the arrows

**Comment by ManojLL** [comment]
I'm working on this
