### ISSUE TITLE
Remove the unwanted dummy text section on home page

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#328]
**Is your feature request related to a problem? Please describe.**
There is an unwanted section on the homepage

**Describe the solution you'd like**
Remove this section:
![Screenshot 2020-01-09 at 18 56 19](https://user-images.githubusercontent.com/33048395/72071408-ba394f00-3311-11ea-9e2c-9cd0e19e230f.jpg)

**Comment by DilshanNaveen** [comment]
I'm working this issue
