### ISSUE TITLE
Remove descriptions on profiles of ScholarX mentors

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#331]
**Is your feature request related to a problem? Please describe.**
Mentor descriptions on scholarx page are longer.

**Describe the solution you'd like**
Keep only the name and remove the description.

Just comment line 428 on scholarx.html page.
`<small class="h6 text-muted">{{intro}}</small>`

**Describe alternatives you've considered**
N/A

**Additional context**
Profiles are loaded using mustache.js. So you only have to edit the template.

**Comment by anjula-sack** [comment]
I'm working on it.
