### ISSUE TITLE
Remove portfolio link from the footer

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#332]
**Is your feature request related to a problem? Please describe.**
The portfolio link on the footer is not needed.

**Describe the solution you'd like**
1. Go to assets/content/static/footer.html
2. Remove the Portfolio link. (Line 127-130)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by anjula-sack** [comment]
I'm working on it
