### ISSUE TITLE
Remove unwanted section from IRC page

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#335]
**Is your feature request related to a problem? Please describe.**
We don't need the section which is with 3 clock icons on the IRC page. A screenshot is given below.
![IMG_20200104_213023](https://user-images.githubusercontent.com/27498587/71768128-74f3d680-2f39-11ea-8c47-542a273c95a5.jpg)

**Describe the solution you'd like**
1. Go to irc.html
2. Remove the section with clock icons

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by DilshanNaveen** [comment]
working on it
