### ISSUE TITLE
Replace headings on team page

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#337]
**Is your feature request related to a problem? Please describe.**
Headings (Team names) haven't added to the team page

**Describe the solution you'd like**
1. Go to team.html
2. Replace 'Lorem ipsum dolor sit amet' headings using the following headings
- Advisory Panel
- Consultants
- External Collaborators
- Executive Committee
- Tech Team
- Design Team

**Describe alternatives you've considered**
N/A

**Additional context**
If there's any problem please refer https://sefglobal.org/about/team.html

**Comment by anjula-sack** [comment]
I'm working on it.
