### ISSUE TITLE
Create Portfolio Page

### ISSUE THREAD

**Issue by bpdesilva** [sef-global/sef-site#34]
Create a static page with all the Videos Listed on the channel and page : https://www.youtube.com/channel/UClw7QbeW_FOJz_fDMvjXsJw/ and https://www.facebook.com/sustainableeducationfoundation/

The Argon theme must be utilised and must follow the color schemes and UX concepts of the current build of the site.

**Comment by CNIAngel** [comment]
Are these videos suppose to be embed on the static page or just linked?

**Comment by bpdesilva** [comment]
@CNIAngel  Either way is fine as long the same template is utilised.

**Comment by CNIAngel** [comment]
@bpdesilva I can follow the Argon system no problem.

**Comment by bpdesilva** [comment]
Cool send us a PR we will accept it 👍
