### ISSUE TITLE
Remove text in becoming a volunteer section on home page

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#347]
**Is your feature request related to a problem? Please describe.**
The dummy text in the volunteer section on the home page is unwanted. 

**Describe the solution you'd like**
Remove dummy text.
![Screenshot 2020-01-10 at 14 32 41](https://user-images.githubusercontent.com/33048395/72140128-105fce00-33b6-11ea-8d40-ce5e8f487586.jpg)

**Comment by anjula-sack** [comment]
I'm working on it.
