### ISSUE TITLE
Remove header from One Live page

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#348]
**Is your feature request related to a problem? Please describe.**
The "Meet the Real Life Heroes" header is unwanted.

**Describe the solution you'd like**
Replace it with **ONE** LIVE (`ONE` should be bold)
Remove excisting ONE LIVE header.

Expected outcome:
![Screenshot 2020-01-10 at 14 42 37](https://user-images.githubusercontent.com/33048395/72140752-74cf5d00-33b7-11ea-9a1f-ce9bd0b33e58.jpg)

**Comment by anjula-sack** [comment]
I'm working on it.
