### ISSUE TITLE
Photos of design team are smaller than others

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#355]
**Describe the bug**
Photos of the design team is smaller than the default size in team page

**To Reproduce**
1. Go to 'https://sef-global.github.io/sef-site/src/main/webapp/team'
2. Scroll down to 'Design team' section
3. See error

**Expected behavior**
All images having same size

**Screenshots**
![Sustainable_Education_Foundation_-_2020-01-10_19 41 13](https://user-images.githubusercontent.com/27498587/72158866-3058b700-33e1-11ea-8e67-9d1c5a571a4f.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04
 - Browser: Google Chrome

**Additional context**
Mobile view is okay.

**Comment by yohanym95** [comment]
i will fix it.

**Comment by yohanym95** [comment]
fixed the issue. #378

**Comment by jayasanka-sack** [comment]
The issue reponed because the PR was reverted. Anyone interested can work on this issue. 

I went through the bug and identified that **removing** the extra row class resolves this issue. (Marked with red line)
![image](https://user-images.githubusercontent.com/33048395/72552475-f7c34c80-38bc-11ea-944f-ecf226e49e10.png)

**Comment by Piumal1999** [comment]
If we remove that extra row class, "Show more" button will be left aligned. 

So my suggestion is,
1) Remove this line `<div class=row justify-content-center">`
2) Add that line before the button
```
<div class="container">
        <p class="display-3">Design Team</p>
        <!--Profile cards goes here-->
        <div id="designTeam"></div>
        <div class="row justify-content-center">
            <button id="btnShowMore_designTeam" class="btn btn-link btn-outline-white btn-info">SEE MORE</button>
        </div>
    </div>
```

Need comment @jayasanka-sack

**Comment by jayasanka-sack** [comment]
@Piumal1999 yeah! You are correct. 😇

**Comment by Piumal1999** [comment]
I'll do this
