### ISSUE TITLE
Replace the hero image of team page

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#356]
**Is your feature request related to a problem? Please describe.**
There's a watermark on current image on the team page.

**Describe the solution you'd like**
1. Download the given image and copy it to the img directory.(src/main/webapp/assets/img/)
2. Replace the img link on team page(Line 40) with the new image link 

Image: https://drive.google.com/file/d/0B_ugZCOs7nKlNXp3dlpQZXhQbktoVDJOdGJ4TkRXNmNRMXFR/view?usp=drivesdk

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by anjula-sack** [comment]
I'm working on it.
