### ISSUE TITLE
Replace external resources with CDN links

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#359]
**Is your feature request related to a problem? Please describe.**
We have to replace all the external resources with CDN links to reduce file sizes and loading times.

**Describe the solution you'd like**
- Replace all the external js scripts and CSS files with CDN links (Except argon files & custom CSS files)
   ex: 
   replace `<link href="assets/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet">`
   with,
   `<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">`
- Delete replaced packages from `assets/vendor`

**Comment by anjula-sack** [comment]
I'm working on it.
