### ISSUE TITLE
Blog on Github Hosting

### ISSUE THREAD

**Issue by bpdesilva** [sef-global/sef-site#36]
Create a method for blogging on Github Pages.

**Comment by sr6033** [comment]
Can you elaborate?

**Comment by bpdesilva** [comment]
@sr6033  We need a method to blog similar to : https://mmistakes.github.io/minimal-mistakes/year-archive/

**Comment by sr6033** [comment]
I understand that you need a blog that is static and hosted on github. My doubt is, how will you want to integrate the domain with this because the blog url will be different than your actual website?

**Comment by bpdesilva** [comment]
Can we direct the URL to https://sefglobal.org/blog ?

**Comment by bpdesilva** [comment]
@jayasanka-sack Blog seems to be down can you check the issue.
