### ISSUE TITLE
Fix header image on OneLive Page

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#364]
**Is your feature request related to a problem? Please describe.**
The header image of onelive page is not aligned properly.

**Describe the solution you'd like**
The header image should satisfy these criteria,  
- The image should align to the bottom right corner on all devices. 
- Maximum width: 100% of the viewport width
- Maximum height: 95% of the viewport height

Use: `assets/img/onelive/header%20clipped.svg`
Rename the file name to `one-live-header.svg`

**Comment by Gravewalker666** [comment]
Will do! 
@jayasanka-sack Any tips on doing this?

**Comment by jayasanka-sack** [comment]
@Gravewalker666 
Use a single image. 
Try [CSS background position property](https://www.w3schools.com/cssref/pr_background-position.asp)
