### ISSUE TITLE
Move Onelive description to the header

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#365]
**Is your feature request related to a problem? Please describe.**
The description on onelive page should be moved to the header.

**Describe the solution you'd like**
- Move the description on the second section ("OneLive" is an interact...) to the header. 
It should be similar to the [Join us page](https://sef-global.github.io/sef-site/src/main/webapp/join_us.html)
- Remove the second section. (the section with log and the description)

**Comment by anjula-sack** [comment]
I'm working on it.
