### ISSUE TITLE
Reduce the image size of 'be a speaker 'section on the OneLive page

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#366]
**Is your feature request related to a problem? Please describe.**
The image size of 'Be a speaker' on the onelive page is larger than the recomend a speaker section.

**Describe the solution you'd like**
- Reduce image size. It should be the same size as the image on recommend a speaker section. 

**Expected behavior:** 
![Screenshot 2020-01-13 at 21 19 59](https://user-images.githubusercontent.com/33048395/72269984-76648380-364a-11ea-92c6-3bfb16f85b4a.jpg)

**Additional context**
Just a suggesstion (Do not get confuced, just a suggestion 😉 ): 

![Screenshot 2020-01-13 at 21 21 16](https://user-images.githubusercontent.com/33048395/72270103-a449c800-364a-11ea-9d83-caca9c3ec71c.jpg)

**Comment by yohanym95** [comment]
I am working on it.
