### ISSUE TITLE
Move Student Ambassador link in the navigation bar to list under Projects

### ISSUE THREAD

**Issue by Gravewalker666** [sef-global/sef-site#368]
**Is your feature request related to a problem? Please describe.**
Link to Student Ambassador page is no longer needed in the navbar.

**Describe the solution you'd like**
Need to move SA link to the dropdown menu of projects link on navbar.

**Additional context**
- Current Behaviour 
![image](https://user-images.githubusercontent.com/45477334/72325584-6f358800-36d3-11ea-8062-8634c434dd6d.png)

**Comment by anjula-sack** [comment]
I'm working on it.
