### ISSUE TITLE
Remove SEF logo from the first section of homepage

### ISSUE THREAD

**Issue by Gravewalker666** [sef-global/sef-site#369]
**Is your feature request related to a problem? Please describe.**
SEF logo on the homepage is getting redundant with the same logo already on the navbar

**Describe the solution you'd like**
Removing the logo in the homepage

**Additional context**
- Current Behaviour
![image](https://user-images.githubusercontent.com/45477334/72325988-4792ef80-36d4-11ea-964a-a4bfdac8ad0a.png)
- Expected Behaviour
![image](https://user-images.githubusercontent.com/45477334/72326030-642f2780-36d4-11ea-9d53-b1408bef6a50.png)

**Comment by anjula-sack** [comment]
I'm working on it.
