### ISSUE TITLE
Replace dummy text in signup section on IRC page

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#376]
**Is your feature request related to a problem? Please describe.**
The signup section on IRC page is with dummy texts.

**Describe the solution you'd like**
- Move the signup section to the bottom of the page (before the footer)
- Replace the image with this image : [irc-signup.svg](https://drive.google.com/file/d/1QTSQCdQCDfg82D5JRTzqdEcHFqh8t0uu/view?usp=sharing)
- Replace header with: "Sign Up as a Researcher"
- Replace body text with: "Submit your details via our online form or drop us an email at sustainableedufoundation@gmail.com. We look forward to hearing from you!"
- Replace button text to "Sign Up"
- Link button to : https://docs.google.com/forms/d/e/1FAIpQLSc0Mman3viM-CmCDyLSwhHIY2QQmJHA6_I9awPadLM743FI4g/viewform

**Comment by anjula-sack** [comment]
I’m working on it.
