### ISSUE TITLE
Change first section of the team page to match with other pages

### ISSUE THREAD

**Issue by Gravewalker666** [sef-global/sef-site#379]
**Is your feature request related to a problem? Please describe.**
In the current team page design, the illustration goes after the text
![image](https://user-images.githubusercontent.com/45477334/72527846-a781c580-388f-11ea-9d76-0807b8b41e39.png)

**Describe the solution you'd like**
Make it to two columns so that the image would be placed right and text left

**Additional context**
- hint: Make it look like this
![image](https://user-images.githubusercontent.com/45477334/72527972-fb8caa00-388f-11ea-990f-abb6822da807.png)

**Comment by anjula-sack** [comment]
I'm working on it.
