### ISSUE TITLE
Remove the image on the second section of the Join Us page

### ISSUE THREAD

**Issue by Gravewalker666** [sef-global/sef-site#381]
**Is your feature request related to a problem? Please describe.**
Second image on the Join us page is unnecessary 

**Describe the solution you'd like**
Just remove the image and align the text to left

**Additional context**
- This is the section that needs to be changed
![image](https://user-images.githubusercontent.com/45477334/72529325-157bbc00-3893-11ea-8cd1-845534608564.png)

**Comment by anjula-sack** [comment]
I'm working on it.
