### ISSUE TITLE
Replace Header text on IRC page

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#388]
**Is your feature request related to a problem? Please describe.**
The header text of the IRC page has dummy content. Also, The header is incorect.

**Describe the solution you'd like**
- Replace the Title with `International Research Council`
- Replace the heading text with the following.

*The International Research Council (IRC) is a community created by the Sustainable Education Foundation (SEF) to showcase the work of Sri Lankan researchers. One of the main goals of IRC is to provide a digital platform to connect our community of researchers who are actively pursuing research projects in various fields all over the world.*

**Comment by anjula-sack** [comment]
I'm working on it.
