### ISSUE TITLE
Add FAQ section to the IRC page

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#389]
**Is your feature request related to a problem? Please describe.**
The FAQ section is missing on IRC page.

**Describe the solution you'd like**
Add a FAQ section after the profiles section.
You can get the code for the FAQ from the `onelive.html` page.
Get the content from the current site's IRC page. https://sefglobal.org/irc/

**Comment by anjula-sack** [comment]
I'm working on this.
