### ISSUE TITLE
Replace dummy texts on the mentor section of ScholarX page

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#390]
**Is your feature request related to a problem? Please describe.**
Dummy texts on "How to be a mentor' section of ScholarX page should be replaced with actual content.
![IMG_20200116_211103](https://user-images.githubusercontent.com/27498587/72539477-5d0b4380-38a5-11ea-9fbe-70f82dd57455.jpg)

**Describe the solution you'd like**
Replace dummy texts on 'How to be a mentor' FAQ section. 
(Page - src/main/webapp/scholarx.html)
Contents are given below.

**Describe alternatives you've considered**
N/A

**Additional context**

_Content_

"question": "What are the eligibility requirements?"
"answer": "We look for industry experts and academics who have excelled in their careers ideally with recognition from industry bodies/international agencies for their work or have demonstrated exceptional performance in their industry where they represent a minority group (e.g.: women in STEM industry, entrepreneurs of niche industries). \n\nWhile we have been very fortunate to host a high calibre of Sri Lankan mentors in our past program offerings, we are always on the lookout for exceptional mentors regardless of nationality."

"question": "How do I apply to be a mentor?"
"answer": "Submit your CV and expression of interest to sustainableedufoundation@gmail.com"

"question": "Do mentors receive any money for participating in ScholarX as a mentor?",
"answer": "No, this is a volunteer run program."

"question": "Can I participate in ScholarX as both a mentor and a student?"
"answer": "No. We do not encourage a dual hat approach as this will deteriorate the quality of the offering. Please choose whether participation as a mentor or a mentee achieve your career objectives the best and apply for the most suitable role."

"question": "I want to learn more about participating as a mentor in ScholarX. Where can I find more information?"
"answer": "If you have specific queries regarding the role of the mentor , please reach out to us via sustainableedufoundation@gmail.com"

> Use mentor section on https://sefglobal.org/scholarx/ as a reference.

**Comment by anjula-sack** [comment]
I'm working on this.
