### ISSUE TITLE
Replace dummy texts on the mentee section of ScholarX page

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#399]
**Is your feature request related to a problem? Please describe.**
Dummy texts on "How to be a mentee' section of ScholarX page should be replaced with actual content.

**Describe the solution you'd like**
1. Remove the images from both FAQ sections. Both FAQ sections should be on full width as in `onlive.html` page.
2. Set both FAQ sections background color to light-blue. (add `style="background-color: #f8fdff"` to the both section divs. ex: `team.html` page)
2. Replace dummy texts on 'How to be a mentee' FAQ section.
(Page - `src/main/webapp/scholarx.html`)
You can find the questions from the current site: https://sefglobal.org/scholarx/

**Comment by anjula-sack** [comment]
I'm working on this.
