### ISSUE TITLE
Center Headers on the Scholarx Page

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#400]
**Is your feature request related to a problem? Please describe.**
The following headers on `scholarx.html` page should be center aligned.
- How to be a mentor?
- Mentors
- How to be a mentee?

**Describe the solution you'd like**
Set alignment to center on the above-mentioned headers.

**Comment by BhathiyaTK** [comment]
I will fix this.

**Comment by BhathiyaTK** [comment]
Fixed and made a PR.

**Comment by Piumal1999** [comment]
Thank you @BhathiyaTK
