### ISSUE TITLE
Add a description to the hero section of SA page

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#402]
**Is your feature request related to a problem? Please describe.**
We have to add a description to the SA page( src/main/webapp/SA.html )

**Describe the solution you'd like**
Add the given description to the left side of the hero section of Student Ambassador page.

> Student Ambassadors (SA) of the Sustainable Education Foundation (SEF) will act as a liaison for SEF while also acting as an Evangelist for the SEF brand among your peers. This position is for student leaders who are passionate about developing their employability skills and sharing knowledge.

**Describe alternatives you've considered**
N/A

**Additional context**
Use these pages as references:
[https://sef-global.github.io/sef-site/src/main/webapp/irc](url)
[https://sef-global.github.io/sef-site/src/main/webapp/onelive](url)

**Comment by anjula-sack** [comment]
I'm working on this.
