### ISSUE TITLE
Remove unwanted section from SA page

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#403]
**Is your feature request related to a problem? Please describe.**
We don't need the "Role of a Student Ambassador" on Student ambassador page.

**Describe the solution you'd like**
1. Go to SA.html
2. Remove the "Role of a Student Ambassador" section

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by anjula-sack** [comment]
I'm working on this.
