### ISSUE TITLE
Navbar dropdown menu is not working on SA page

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#406]
**Describe the bug**
When the projects link on navbar has hovered, the dropdown menu appears behind the headings

**To Reproduce**
1. Go to 'https://sef-global.github.io/sef-site/src/main/webapp/SA.html'
2. Hover on 'Projects' link
3. See error

**Expected behavior**
Dropdown menu appears in front of Headings

**Screenshots**
![Student_Ambassador_-_2020-01-17_22 12 08](https://user-images.githubusercontent.com/27498587/72630087-9ca26000-3977-11ea-9a7d-106704e4c915.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04
 - Browser: Google Chrome

**Additional context**
This error occurs because of the z-index used on the container(line 35)
`<div class="container mt-md-5 d-none d-md-block" style="position: absolute; z-index: 1000">`
Removing the z-index may fix the bug

**Comment by anjula-sack** [comment]
I'm working on this.
