### ISSUE TITLE
Remove slogans in projects dropdown menu on navbar

### ISSUE THREAD

**Issue by Gravewalker666** [sef-global/sef-site#414]
**Is your feature request related to a problem? Please describe.**
In projects dropdown two of the listed have slogan while the other two haven't

**Describe the solution you'd like**
Remove all the slogans and use text-capitalized instead of text-uppercase

**Additional context**
- Current behaviour
![image](https://user-images.githubusercontent.com/45477334/72665395-1bf26b00-3a2e-11ea-9edc-4f50d22ebf89.png)

**Comment by anjula-sack** [comment]
I'm working on this.
