### ISSUE TITLE
Add profiles to IRC JSON file

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#417]
**Is your feature request related to a problem? Please describe.**
We have to add the researchers' details to the irc.json file

**Describe the solution you'd like**
1. Go to the IRC page on the published site. https://sefglobal.org/irc/
2. Download the profile images. Copy the images to `assets/img/profiles` directory. (use short file names)
3. Add researchers to the assets/contents/json/irc.json file.

Use these as references : 
https://sefglobal.org/irc/

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by osusara** [comment]
I'll Do this

**Comment by jayasanka-sack** [comment]
Did a small change in the description.

"Copy the images to `assets/img/profiles` directory."
