### ISSUE TITLE
Replace hero image of IRC page

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#418]
**Is your feature request related to a problem? Please describe.**
We have to add a new image as the hero image of IRC page

**Describe the solution you'd like**
1. Download this image and copy it to assets/img/irc/ directory
![Asset_1](https://user-images.githubusercontent.com/27498587/72676008-44bc4400-3ab2-11ea-824a-07dc84327c8a.png)
2. Replace the hero image of IRC page using it

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by yohanym95** [comment]
i am working on it.
