### ISSUE TITLE
Replace image on ScholarX page

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#419]
**Is your feature request related to a problem? Please describe.**
We have to add a new image to the 'call to action' section of ScholarX page

**Describe the solution you'd like**
1. Download this image and copy it to assets/img/scholarx/ directory
![scholarx_illustration](https://user-images.githubusercontent.com/27498587/72676550-51439b00-3ab8-11ea-9afc-a9bdfb70d0d4.png)
2. Replace the image of 'Find a mentor for me' section on ScholarX page using it

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by yohanym95** [comment]
i'll do it.
