### ISSUE TITLE
Signup button on ScholarX page is not aligned correctly

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#423]
**Describe the bug**
Signup button on ScholarX page is not aligned correctly.

**To Reproduce**
1. Go to 'scholarx.html'
2. Scroll down to 'Find a mentor for me' section
3. See error

**Expected behavior**
![Sustainable_Education_Foundation_-_2020-01-19_13 54 39](https://user-images.githubusercontent.com/27498587/72677523-4a6e5580-3ac3-11ea-9045-fcb5c6dc1118.png)

**Screenshots- Current Behavior**
![Sustainable_Education_Foundation_-_2020-01-19_13 57 53](https://user-images.githubusercontent.com/27498587/72677587-fb74f000-3ac3-11ea-97a1-122dcac539bb.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04
 - Browser Google Chrome

**Additional context**
To resolve this issue,
1. Remove 'pb-0' class from the section(line 388)
2. Replace it with 'pb-5' (Add a bottom padding to the section)

3. Change the bottom padding of paragraph to pb-3 (line 386)

**Comment by yohanym95** [comment]
i'll fix this.
