### ISSUE TITLE
Profile images are not loading in IRC page

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#430]
**Describe the bug**
Profile images are not loading in `irc.html` page
![Screenshot 2020-01-20 at 09 40 29](https://user-images.githubusercontent.com/33048395/72698163-e736fe80-3b68-11ea-9cf8-a6c1b1c5498a.jpg)

**To Reproduce**
1. Go to `irc.html`
3. Scroll down to profiles section

**Additional context**
The issue is the wrong image path in moustache template.
Please replace this line (line 197 in `irc.html`),
`<img src="assets/img/irc/{{image}}"`
with,
`<img src="assets/img/profiles/{{image}}"`

**Comment by yohanym95** [comment]
i'll fix this issue.

**Comment by yohanym95** [comment]
Fixed the issue #431
