### ISSUE TITLE
Add FAQ section to the Student Ambassador page

### ISSUE THREAD

**Issue by Gravewalker666** [sef-global/sef-site#434]
**Is your feature request related to a problem? Please describe.**
Student Ambassador page needs a FAQ section with these provided information 

**Describe the solution you'd like**
Add FAQ after the header section

**Additional context**
Add these FAQs to the section:

- What would I get as an ambassador?
  - SA’s will be trained and mentored throughout the program via our skills development program formulated with industry experts to give you the in-demand skills employers are seeking for like time management, adaptability and collaboration. The program will arm you to be career ready when you graduate from university. You will also be able to develop your leadership, project management and marketing skills when you deliver SEF programs at campus level.

- What’s my role as a Student Ambassador?
  - Conduct on campus sessions to spread the word on SEF in your respective Universities
  - Build a strong, sustainable SEF community and collaboration within other clubs/societies in your respective university
  - Share the work that SEF is doing among your peers via social media platforms
  - Blog/Vlog about your experience with SEF
  - Maintain the SEF brand name internally and externally from the University
  - Volunteer in a SEF core team/work stream

- What does it take to be a Student Ambassador?
  - A high degree of multi-tasking and time management capability
  - Good communication skills in English and Sinhala or Tamil
  - Exemplary leadership qualities

- When can I apply?
  - We recruit people throughout the entire year. Submit your application using the Apply Now button below.

**Comment by anjula-sack** [comment]
I'm working on this.
