### ISSUE TITLE
Join Us page : apply now button isn't linked properly

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#438]
**Is your feature request related to a problem? Please describe.**
The `apply now` button on `join_us.html` page isn't linked properly.

**Describe the solution you'd like**
Please link the button properly.

The way it should be is :
```
<a class="btn btn-purple text-uppercase mt-3" 
   href="https://sefglobal.org/apply/"
   >
   Apply now!
</a>
```

**Comment by yohanym95** [comment]
I'll fix it.

**Comment by jayasanka-sack** [comment]
Okay go ahead.
