### ISSUE TITLE
Remove Yasantha Rajakarunanayake from the team page

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#439]
**Is your feature request related to a problem? Please describe.**
Dr.Yasantha Rajakarunanayake is no longer in the team. 

**Describe the solution you'd like**
Remove him from the team page. 
Profiles are loaded from `assets/contents/json/team.json`file.

![Screenshot 2020-01-22 at 00 49 40](https://user-images.githubusercontent.com/33048395/72835636-15275a80-3cb1-11ea-872e-8b3139af0871.jpg)

**Comment by JaniduJ** [comment]
I'll fix this issue

**Comment by jayasanka-sack** [comment]
Okay go ahead
