### ISSUE TITLE
Change in the Wording

### ISSUE THREAD

**Issue by akshika47** [sef-global/sef-site#44]
The wording in the Home page has to be changed. 

Existing text : 

Sustainable Education Foundation (SEF) is a volunteer driven organisation founded by the former Google Student Ambassador and an alumni of University of Moratuwa.

Akshika Wijesundara. SEF was founded with the short term goal of making the Sri Lankan education system the most effective and the most dynamic education system in the world. SEF’s long term goal is to disrupt and democratise the global education system where it is available for everyone, in doing so, foundation contributes to the United Nations’ sustainable development goal of “Quality Education”.

It should change to:

Sustainable Education Foundation (SEF) is a volunteer driven organisation founded by the former Google Student Ambassador and an alumni of University of Moratuwa **Akshika Wijesundara**. 

SEF was founded with the short term goal of making the Sri Lankan education system the most effective and the most dynamic education system in the world. SEF’s long term goal is to disrupt and democratise the global education system where it is available for everyone, in doing so, foundation contributes to the United Nations’ sustainable development goal of “Quality Education”.

**Comment by biswaroop1547** [comment]
I will fix it !

**Comment by akshika47** [comment]
https://github.com/SustainableEducationFoundation/LiveWeb/pull/92 Please someone review the pull request.
