### ISSUE TITLE
Fix hero section on the scholarX page

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#440]
**Is your feature request related to a problem? Please describe.**
The hero section of the `scholarx.html` page needs to be modified.

**Describe the solution you'd like**
1. Add `img/scholarx/findmentor.png` to the right side of the hero section. (as in `team.html` page)
2. Move text to the left side and make text left aligned

Expected outcome:

![Screenshot 2020-01-22 at 01 09 29](https://user-images.githubusercontent.com/33048395/72837056-db0b8800-3cb3-11ea-9d40-d2f5015bd9b3.jpg)

**Comment by BhathiyaTK** [comment]
I will work on it.

**Comment by jayasanka-sack** [comment]
Okay, go ahead

**Comment by BhathiyaTK** [comment]
Fixed in #446
