### ISSUE TITLE
Fix 'Find a mentor' section in scholarX page

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#441]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
1. Centre the title & button
2. Set paragraph text alignment to justify
3. Remove image
4. Change button text to apply
5. Link button with `sustainableedufoundation@gmail.com` email using [mailto:](https://www.rapidtables.com/web/html/mailto.html)

Expected outcome: 
![Screenshot 2020-01-22 at 01 17 49](https://user-images.githubusercontent.com/33048395/72837747-0347b680-3cb5-11ea-89eb-18f6214e671c.jpg)

**Comment by anjula-sack** [comment]
I'm working on this.
