### ISSUE TITLE
Add smooth scrolling animations to pages

### ISSUE THREAD

**Issue by osusara** [sef-global/sef-site#445]
**Is your feature request related to a problem? Please describe.**
In some pages, there are buttons that are linked to elements within the same page. Example "Learn More" button in join_us.html. It's better if they have a smooth scroll. Now they just jump to the linked section.

**Affected pages**
index.html "Explore" button (Landing Page).
onelive.html "Learn More" button (One Live Page).
join_us.html "Learn More" button (Join Us Page).

**Describe the solution you'd like**
I suggest, scroll the page smoothly to the linked section.

**Comment by Gravewalker666** [comment]
I will do this!

**Comment by jayasanka-sack** [comment]
@Gravewalker666 refer to this link. might be helpful
https://stackoverflow.com/questions/7717527/smooth-scrolling-when-clicking-an-anchor-link 

```
var $root = $('html, body');

$('a[href^="#"]').click(function () {
    $root.animate({
        scrollTop: $( $.attr(this, 'href') ).offset().top
    }, 500);

    return false;
});
```
