### ISSUE TITLE
No consistency when loading blog page from nav-bar and footer

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#454]
**Describe the bug**
After clicking the blog link from the nav-bar the blog page will load in the same page. But after clicking the blog link from the footer, the blog page will get loaded in a new tab in the browser.

**To Reproduce**
1. Go to the Home page.
2. Click on the blog link in the navigation bar.
3. Now go back to the Home page
4. Scroll down until the footer.
5. Now click the blog link in the footer.

**Expected behavior**
Either the blog page should load in the same page or in a different page in both events.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome

**Comment by janethavi** [comment]
I would like to fix this issue. Please let me know If we need to open the blog page in a separate tab or in the same tab.

**Comment by jayasanka-sack** [comment]
I guess opening on the same page is fine. 
@akshika47 Isn't it?

**Comment by Piumal1999** [comment]
@jayasanka-sack I also think so

**Comment by jayasanka-sack** [comment]
@janethavi Let's make it open in the same tab.

**Comment by janethavi** [comment]
Sure! I will work on it. @jayasanka-sack
