### ISSUE TITLE
Add suitable icons for navbar on mobile view

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#457]
**Is your feature request related to a problem? Please describe.**
Same icon is used for 5 links in the navbar on mobile view.

Current view:
![IMG_20200125_232056](https://user-images.githubusercontent.com/27498587/73125178-e5869400-3fc9-11ea-9dc5-a154a815731e.jpg)

**Describe the solution you'd like**
Replace the icons relative to the link.

**Describe alternatives you've considered**
N/A

**Additional context**
Navbar path: assets/content/static/navbar.html

**Comment by yozaam** [comment]
Yes since we have fontawesome this will be as simple as changing the classnames from ni ni-ui-04 d-lg-none to the ones we want, Please may I work on this?

If anyone else is curious, 
```
<i class="ni ni-air-baloon"></i>

<i class="fa fa-bicycle"></i>
```

ni is from the argon icons :D

**Comment by Gravewalker666** [comment]
@yozaam Go on buddy! Work on this issue and send us your PR!! :)

**Comment by yozaam** [comment]
okay, doing it 😺
