### ISSUE TITLE
Remove unwanted text from the SA page

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#459]
**Is your feature request related to a problem? Please describe.**
We don't need the last line of text on the hero section of SA page.

**Describe the solution you'd like**
- Go to Student Ambassador file. (SA.html)
- Delete the last line of description on hero section. Leave only the first line.

Expected Description:
Student Ambassadors (SA) of the Sustainable Education Foundation (SEF) will act as a liaison for SEF while also acting as an Evangelist for the SEF brand among your peers.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by yozaam** [comment]
Hello, If I want to fix multiple issues should I do it through multiple PR's ?

**Comment by jayasanka-sack** [comment]
@yozaam  You can fix multiple issues within a single PR.
