### ISSUE TITLE
Add a new statement in home page

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#466]
**Is your feature request related to a problem? Please describe.**
In the first page, there should be a statement in between our flagship programs and the Student/Expert/Volunteer section saying " You could be a student, expert or a volunteer. At SEF have something in store for everyone "

**Comment by osusara** [comment]
I'll do this too 😄

**Comment by jayasanka-sack** [comment]
Great! 🤩

**Comment by jayasanka-sack** [comment]
Post the pr link to the gitter channel. It's time to sleep lol 😁

**Comment by akshika47** [comment]
I made a slight change
@osusara the statement should be: "You could be a student, expert or a volunteer. At SEF, we have something in store for everyone!"

**Comment by Suthan97** [comment]
> I'll do this too 😄

Are you still working on the issue?

**Comment by osusara** [comment]
> 
> 
> > I'll do this too 😄
> 
> Are you still working on the issue?

@Suthan97 Sorry for the late reply. Go on, do this one. 👍

**Comment by Suthan97** [comment]
I don’t have experience

**Comment by Suthan97** [comment]
Sorry for the last message mistakenly sent to you. 😐

**Comment by Suthan97** [comment]
> > > I'll do this too 😄
> > 
> > 
> > Are you still working on the issue?
> 
> @Suthan97 Sorry for the late reply. Go on, do this one. 👍

Ok thank you 😊

**Comment by anjula-sack** [comment]
@Suthan97 are you still working on this?

**Comment by akshika47** [comment]
@Suthan97 are you still working on this?
