### ISSUE TITLE
Reduce hero image size on the Join us Page

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#467]
**Is your feature request related to a problem? Please describe.**
Hero Image sizes of program pages are still big(except ScholarX page). It should be reduced or trimmed to be like on the home page. check the home page's hero image. That is the ideal size.

**Describe the solution you'd like**
Expected outcome: 
![Screenshot 2020-01-29 at 22 05 24](https://user-images.githubusercontent.com/33048395/73376510-8d120800-42e3-11ea-83be-f8fc8bd0e38e.jpg)

**Comment by ruwanliyanage123** [comment]
I'm working on this

**Comment by ruwanliyanage123** [comment]
Sorry, I have been assigned to an emergency project. I'm busy with those
days. So then I unable to contribute for that assignment.
Thank you,
Regards,
Ruwan Liyanage.

**Comment by Gravewalker666** [comment]
@ruwanliyanage123 Oh! no worries at all brother.

**Comment by Bawanthathilan** [comment]
I'm working on this
