### ISSUE TITLE
Change FAQ headings on the ScholarX page

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#468]
**Is your feature request related to a problem? Please describe.**
ScholarX FAQ headings should change from "How to be a mentor?" to "FAQ for Mentors" and "How to be a mentee?" to "FAQ for mentees" This page will later be changed as we will be launching the next batch of mentors

**Comment by osusara** [comment]
I'll do this

**Comment by jayasanka-sack** [comment]
Okay! 😇
