### ISSUE TITLE
Update the Team Page

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#474]
**Is your feature request related to a problem? Please describe.**
We need to update the team page with the latest content

**Describe the solution you'd like**
1. Go to Team details json file(assets/content/json/team.json) 
2. Move Minuri Adasuriya's profile (line 153-169) to the advisory panel section. Change her description to "Diversity & Inclusion Lead, Asia at Lendlease"
3. Move Suresh Peiris's profile(line 105-112)  to the consultants section. Change his description to "Consultant".

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by yozaam** [comment]
Doing it 👍
