### ISSUE TITLE
Remove the unwanted file

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#476]
**Is your feature request related to a problem? Please describe.**
There's an unwanted file in the root directory called ":"
https://github.com/sef-global/sef-site/blob/master/: 

**Describe the solution you'd like**
Delete the ":" file from the directory

**Describe alternatives you've considered**
N/A

**Additional context**
![IMG_20200202_102022](https://user-images.githubusercontent.com/27498587/73603229-fcb71a00-45a5-11ea-8398-8f5c07258667.jpg)

**Comment by anjula-sack** [comment]
I'm working on this.
