### ISSUE TITLE
Replace apply form links

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#479]
**Is your feature request related to a problem? Please describe.**
Current form links need to be replaced because those links are absolute and the pointed forms will be deleted when we publish the new site. 
affected links;
1. Apply now button on the `join_us.html`
2. Apply button on the `SA.html` page

**Describe the solution you'd like**
1. Link apply now button on the `join_us.html` to `apply.html`
2. Link apply button on the `SA.html` page to `sa-apply.html`

**Comment by anjula-sack** [comment]
I'm working on this.

**Comment by jayasanka-sack** [comment]
Okay, go-ahead 😇
