### ISSUE TITLE
Replace FAQ description under "what is ScholarX?"

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#486]
**Is your feature request related to a problem? Please describe.**
Currently the ScholarX description and the FAQ description under "what is ScholarX?" are the same.
![image](https://user-images.githubusercontent.com/43912578/73856497-8b07f600-485b-11ea-85c0-dce7dcb447c6.png)

**Describe the solution you'd like**
Need suggestions for the issue.

**Comment by jayasanka-sack** [comment]
Shall we remove what is scholarX from FAQ? 
@akshika47 @Piumal1999 @Gravewalker666

**Comment by akshika47** [comment]
Yes please

**Comment by anjula-sack** [comment]
I'm working on this.
