### ISSUE TITLE
Edit item on past onelives

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#493]
**Is your feature request related to a problem? Please describe.**
The first item on past onlives (`onelive.html`) should be changed for now.

**Describe the solution you'd like**
Replace the Name with: Dr. Hasini Jayathilaka
Replace the link with:
https://www.facebook.com/sustainableeducationfoundation/videos/vb.1833231326936705/338708860279593/?type=2&theater

**Comment by yohanym95** [comment]
i'll fix it.

**Comment by jayasanka-sack** [comment]
@yohanym95 any update on this?

**Comment by yohanym95** [comment]
i'm working on it.
