### ISSUE TITLE
Fix grammar mistake in the home page

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#498]
**Is your feature request related to a problem? Please describe.**
The "You could be a student, ..."  tag line has a grammar mistake. It should be 'an expert'.

**Describe the solution you'd like**
Replace it with,
"You could be a student, an expert or a volunteer. At SEF, we have something in store for everyone!"

**Comment by Suthan97** [comment]
I will fix it :)

**Comment by jayasanka-sack** [comment]
Okay! This needs to complete within an hour.

**Comment by Suthan97** [comment]
@jayasanka-sack  I will fix it..

**Comment by Suthan97** [comment]
Ok 👍

**Comment by jayasanka-sack** [comment]
@Suthan97 could you please DM me on gitter?

**Comment by jayasanka-sack** [comment]
@Suthan97 since we are in a hurry on publishing the site, this change should be done asap. 
Are you still working on this?
