### ISSUE TITLE
Add SEO meta tags to the site

### ISSUE THREAD

**Issue by Gravewalker666** [sef-global/sef-site#509]
**Is your feature request related to a problem? Please describe.**
Meta tags that came with Creative Tim UI kit were not replaced and now it shows there description for our site
![image](https://user-images.githubusercontent.com/45477334/74588504-331f7b00-5023-11ea-91d3-94cb2482d349.png)

**Describe the solution you'd like**
Add SEO meta tags into the `<head></head>` 

**Describe alternatives you've considered**
N/A

**Additional context**
*We will provide the descriptions and titles and images that need to be set for the meta tags by updating this issue.*

**Comment by Gravewalker666** [comment]
@jayasanka-sack Can you see to providing the necessary material and texts to make this solution happen?

**Comment by jayasanka-sack** [comment]
Use hero images on each page as the image.
Use the same hero description as the description.
Change author to Sustainable Education Foundation. 

These changes should be present on each page. 

@Gravewalker666 Could you please provide the list of necessary tags here, please?

**Comment by Gravewalker666** [comment]
`<meta name="description" content="description">`
`<meta property="og:image" content="path/to/image">`

**Comment by anjula-sack** [comment]
I'm working on this.
