### ISSUE TITLE
Increase the margin of the team titles 

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#512]
**Is your feature request related to a problem? Please describe.**
The padding between profiles and the headings are too low.

**Describe the solution you'd like**
Increase the bottom margin of the titles.  ( `team.html` page )

![Screenshot 2020-02-20 at 09 58 36](https://user-images.githubusercontent.com/33048395/74901056-afb9ad00-53c7-11ea-8750-102a8783717a.jpg)

**Comment by ManojLL** [comment]
I am working on this
