### ISSUE TITLE
Issue in Linked-in font awesome icon

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#514]
**Describe the bug**
After Upgrading the font awesome version from V4 to V5 Linked-in icon is not visible in the team page

**To Reproduce**
1. Go to Team page
2. Hover over the team members' photos
3. Linked-in font awesome icon is not visible

**Expected behavior**
Linked-in icon should be visible

**Screenshots**
![Screenshot from 2020-02-23 10-35-03](https://user-images.githubusercontent.com/35697678/75103944-5dc39200-5628-11ea-8697-bed7af50b4e2.png)

**Comment by jayasanka-sack** [comment]
Thanks for pointing this out @janethavi !
