### ISSUE TITLE
Reorganize newly added fields in scholarx.json

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#522]
**Is your feature request related to a problem? Please describe.**
- Social links are not properly organized right now.

**Describe the solution you'd like**
- Social links have to go under a new key and it should be an array.
"socialLinks" : [
   {
    "platform" : "Linkedin",
    "icon" : "fa-linkedin",
     "url" : "..."
   },
    {
    "platform" : "Facebook",
    "icon" : "fa-linkedin",
     "url" : "..."
   },
]
- Same with the project. The key should be "projects" and it should be an array.
- The keys should not contain white spaces and must use simpleCamel case format.
- Add this content from this link https://docs.google.com/spreadsheets/d/1zOEfTBTTBDdDKcafHI44CY73v2obLEnnOupNBzzO0Do/edit?usp=sharing

**Comment by anjula-sack** [comment]
I'm working on this.

**Comment by jayasanka-sack** [comment]
@anjula-sack Let's close this issue and divide it into two sub-issues. 

1. Create the structure
1. Fill data
