### ISSUE TITLE
Deploy scholarx-2020 branch to surge on each pull request merge

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#523]
**Is your feature request related to a problem? Please describe.**
The scholarX branch needs a preview.

**Describe the solution you'd like**
Create a script to deploy the scholarx-2020 branch to surge on each pull request merge using travis.

Deploy it here: https://scholarx-2020.surge.sh
DM me to get a token. Test with your own domain for now. 

**Additional context**
Check [this PR to get an idea.](https://github.com/sef-global/sef-site/pull/374) It was built to generate preview links for the PRs. This requirement is to deploy the `scholarx-2020` branch after the PR was merged.

**Comment by Gravewalker666** [comment]
@jayasanka-sack I'd like to do this. Can you give me a hand? I don't know what to do exactly.

**Comment by jayasanka-sack** [comment]
yeah sure

**Comment by jayasanka-sack** [comment]
Closing this issue since the scholarX page has to be delivered by tomorrow.
