### ISSUE TITLE
Replace current FAQ's for mentees.

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#529]
**Is your feature request related to a problem? Please describe.**
- FAQ's are going to be changed.

**Describe the solution you'd like**
- Add this FAQ's instead of the current ones.

What are the eligibility requirements?
Our priority is given to applicants of Sri Lankan origin. However, if we have an excess of mentors, we will look at expanding the offering to foreign students as well.

You must be at least 18 years of age when you register
You must currently be a full time or part-time student undertaking an undergraduate or postgraduate course.
You have not already been accepted as a mentee in ScholarX more than once

What are the selection criteria?

The application form consists of a series of questions regarding your field of study, extracurricular experience and interest in the program, designed to allow for the best possible match between mentors and mentees. The application process is competitive so we encourage students to be as thorough as possible in answering the short answer section of the application form. 

We require all applicants to demonstrate a high standard of English proficiency and a genuine curiosity to learn and innovate. In their responses, applicants must also show ambition to achieve their career goals and articulately express how the mentoring program will assist with achieving their overall academic and/or professional objectives.

Once selections and assignments are made, mentees will be contacted with further information on how to proceed.

How are mentors assigned?

Mentor information and areas of expertise are published on the SEF website and social media. Students will be asked to pick their top three choices in mentors and will be assigned to selected mentors based on these choices as well as the relative strength of their application. 

How do I apply?

Applications for this year’s instalment of the ScholarX program open on 4th March 2020 and will close 14th April 2020. Keep an eye on the ScholarX page on our website for the application link.

**Comment by AselSiriwardena** [comment]
Can I get assigned?

**Comment by anjula-sack** [comment]
You are assigned. @AselSiriwardena

**Comment by jayasanka-sack** [comment]
The page is `/scholarx/2020/index.html`
