### ISSUE TITLE
Change the scholarX directory structure

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#531]
**Is your feature request related to a problem? Please describe.**
- Need a new file structure for scholarx. 

**Describe the solution you'd like**
- move the images from the images folder.
- take a copy of the current page and make it as the 2019 page.

**Describe alternatives you've considered**
![Screenshot from 2020-02-27 09-46-03](https://user-images.githubusercontent.com/43912578/75411655-04b86e80-5946-11ea-9f58-60e5f1e3d29d.png)

### Use `scholarx-2020` branch

**Comment by jayasanka-sack** [comment]
I'll work on this

**Comment by anjula-sack** [comment]
Okay @jayasanka-sack
