### ISSUE TITLE
Add a new section on the 2020 scholarX page to display past scholarX programs

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#539]
**Is your feature request related to a problem? Please describe.**
- Currently you can't check past year scholarx pages.

**Describe the solution you'd like**
- Add a new section on the 2020 scholarX page.
![Screenshot from 2020-02-27 20-01-40](https://user-images.githubusercontent.com/43912578/75454820-10cf1b00-599c-11ea-977b-d49346c67dbc.png)
- use `../past-scholarx.html#past-scholarx` for archive link

**Comment by jayasanka-sack** [comment]
It's easy to maintain if we had a page to display our past scholarx programs. There's an already created page for this `scholarx/archives/index.html`. All the scholarX pages should link with this page. So we can update only this page when there's a new scholarX program. 

This page should be a super simple one. Have a look at this: https://summerofcode.withgoogle.com/archive/

This is the requirement:

- Requirement 1
1. Create a basic page to display past scholarX. (Provide the texts and a basic design)
2. Link it with 2019 page

- Requirement 2
1. Add a new section on the 2020 scholarX page which links to the archive page. (Provide the content and basic design)

**Comment by anjula-sack** [comment]
I'm working on this.

**Comment by jayasanka-sack** [comment]
@anjula-sack The link should be `../archives`
