### ISSUE TITLE
Create a card to add blog posts.

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#540]
**Is your feature request related to a problem? Please describe.**
- There are going to be a new section with featured stories (from past year) 

**Describe the solution you'd like**
- Create a new section below faq's for mentees.
- Add "Featured Stories" as the title
- Create a new card
- Add card to the section
- Use this as a dummy content
https://blog.sefglobal.org/2019/11/scholarx-class-of-2019-sx19/

- The design should be something like this.
![Screenshot from 2020-02-28 15-17-12](https://user-images.githubusercontent.com/43912578/75537695-7f17ea00-5a3d-11ea-85a6-d7ee74075722.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by jayasanka-sack** [comment]
Could you please describe how the section should appear? (The design)
And what do you mean by feature stories? the blog posts?

Divide this into two sub-issues. 

1. Develop a section using the provided design with mock data. (We can focus on the design when reviewing)
2. Add content to the developed section. (We can focus on the data when reviewing)

**Comment by jayasanka-sack** [comment]
I'm working on this.
