### ISSUE TITLE
Create a empty profile modal for mentors

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#541]
**Is your feature request related to a problem? Please describe.**
- Need a mentor profile page to add to the scholarx 2020 page.

**Describe the solution you'd like**
- The profile card should contain only the image and the name. Remove the linkedin button from the current card.
- The card should be clickable. A modal should appear when clicking the card.
- It should be an empty modal for now.

**Describe alternatives you've considered**
- This page will popup when clicked on mentors name.

**Additional context**

**Comment by anjula-sack** [comment]
@jayasanka-sack Please review this.

**Comment by jayasanka-sack** [comment]
@anjula-sack This is kind of a big issue. It's easy to develop and also for review if we can divide this issue into sub-issues as following. Create these issues one by one. For your ease, I've divided the requirement into three sub-requirements.
  
- Requirement 1

1. The profiles should be loaded from the JSON file (already implemented)
1. The profile card should contain only the image and the name. Remove the linkedin button from the current card.
1. The card should be clickable. A modal should appear when clicking the card.
1. It should be an empty modal for now.

- Requirement 2
1. Update the content of the profile modal using the provided design. (Provide the design)
2. No need to load them from the JSON file. Just hardcode dummy data.

- Requirement 3
1. Load mentor details to the profile modal using the `mentors.json` file

**Comment by anjula-sack** [comment]
I'm working on this.

**Comment by anjula-sack** [comment]
I'm working on this.

**Comment by anjula-sack** [comment]
I'm working on this.
