### ISSUE TITLE
Load mentor details to the profile modal using the mentors.json file

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#544]
**Is your feature request related to a problem? Please describe.**
- The profile modal is not linked with json file.

**Describe the solution you'd like**
- Load mentor details to the profile modal using the mentors.json file

**Describe alternatives you've considered**

**Additional context**

**Comment by AselSiriwardena** [comment]
I can work on this after the profile modal is done.

**Comment by jayasanka-sack** [comment]
okay, @AselSiriwardena go ahead! :)

**Comment by jayasanka-sack** [comment]
@AselSiriwardena Are you available?

We are in a hurry on delivering the scholarX page

**Comment by jayasanka-sack** [comment]
I'm working on this since this is a little bit urgent

**Comment by AselSiriwardena** [comment]
@jayasanka-sack I’m really sorry i was not available that day.
I have checked for the model but pr was not approved that time.
Again Im sorry!
This will not happen again
