### ISSUE TITLE
Change the order of the content of scholarX 2020 page

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#551]
**Is your feature request related to a problem? Please describe.**
The current section order needs to be changed.

**Describe the solution you'd like**
The correct order should be:

1. Hero section
2. Timeline
3. Mentors
1. Featured stories
2. FAQ for mentees 
2. FAQ for mentors
3. Past scholarX links
1. Apply

## Use `scholarx-2020` branch

**Comment by akshika47** [comment]
Please add the mentors section after the timeline and add a signup button in the hero section as well.

**Comment by jayasanka-sack** [comment]
Okay sure.

**Comment by jayasanka-sack** [comment]
Updated the description

**Comment by anjula-sack** [comment]
Where will be the past scholarx section @jayasanka-sack

**Comment by jayasanka-sack** [comment]
> Where will be the past scholarx section @jayasanka-sack

Thanks @anjula-sack . Updated the description

**Comment by anjula-sack** [comment]
I'm working on this!
