### ISSUE TITLE
Mentors are not loading on scholarx 2019 page 

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#554]
**Describe the bug**
Scholarx 2019 page mentors are not loading.

**To Reproduce**
1. Go to scholarx-2019 page
2. Scroll down to mentors section
3. See error

**Expected behavior**
Mentors should be loaded to the page.

**Screenshots**
![Screenshot from 2020-02-29 15-31-33](https://user-images.githubusercontent.com/43912578/75605407-a12a6e80-5b08-11ea-8b4f-476b7188da55.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by 99sumedha** [comment]
im working on this..

**Comment by jayasanka-sack** [comment]
@99sumedha Are you still working on this?
