### ISSUE TITLE
Add navigation and the footer to the scholarX archive page

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#556]
**Is your feature request related to a problem? Please describe.**
The navigation and the footer are missing on the scholarx archive page. `/scholarx/archive/index.html`

**Describe the solution you'd like**
Add navigation and the footer to the scholarX archive page. Just refer the `/scholarx/archive/index.html` page to get an idea. 

## use scholarx-2020 branch

**Comment by anjula-sack** [comment]
I'm working on this.
