### ISSUE TITLE
Scholarx page : Last two mentor images are not working

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#557]
The last two profile images are not working on the scholarx page. 

![Screenshot 2020-02-29 at 16 23 38](https://user-images.githubusercontent.com/33048395/75606142-da1a1180-5b0f-11ea-8368-0f68906fcaab.jpg)

##  branch : `scholarx-2020`

**Comment by anjula-sack** [comment]
I'm working on this.

**Comment by jayasanka-sack** [comment]
Chethiya: https://avatars1.githubusercontent.com/u/232585?s=460&v=4

**Comment by jayasanka-sack** [comment]
Nishantha : https://nrajakaruna.files.wordpress.com/2010/09/flames-with-eb-2010.jpg

**Comment by jayasanka-sack** [comment]
@anjula-sack use this images

**Comment by anjula-sack** [comment]
I'll add them @jayasanka-sack
