### ISSUE TITLE
Make ScholarX 2020 page responsive

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#563]
**Describe the bug**
ScholarX 2020 page is not responsive. 

**To Reproduce**
1. Go to scholarx currebt page
2. Click on mobile view
3. See error its not responsive

**Expected behavior**
Look for the bug and make page responsive again

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Browser chrome

**Additional context**

**Comment by jayasanka-sack** [comment]
I'm working on this
