### ISSUE TITLE
Rewrite the FAQ component in  ScholarX 2019 page 

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#579]
**Describe the bug**
- ScholarX 2019 page is not responsive. Because of FAQ component.

**To Reproduce**
1. Go to scholarx 2019 page
2. Click on mobile view
3. See error it's not responsive

**Expected behavior**
- Rewrite the FAQ component referring to the scholarx 2020 page
### Refer pr #582 .
 
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Browser chrome

**Additional context**

**Comment by yozaam** [comment]
Is this closed?

**Comment by anjula-sack** [comment]
@yozaam No. You can work on this.

**Comment by anjula-sack** [comment]
I'm working on this.
