### ISSUE TITLE
Rewrite the FAQ component in IRC page

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#580]
**Describe the bug**
- IRC page is not responsive. Because of the FAQ component.

**To Reproduce**
1. Go to IRC page
2. Click on mobile view
3. See error it's not responsive

**Expected behavior**
- Rewrite the FAQ component referring to the scholarx 2020 page
### Refer pr #568 .
 
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Browser chrome

**Additional context**

**Comment by Piumal1999** [comment]
I'll do this

**Comment by anjula-sack** [comment]
Okay :)

**Comment by jayasanka-sack** [comment]
@Piumal1999 The issue isn't fixed yet.

**Comment by anjula-sack** [comment]
@Piumal1999 please refer pr #568

**Comment by jayasanka-sack** [comment]
Refer to anjula's PR #582

**Comment by Piumal1999** [comment]
Ok
