### ISSUE TITLE
Resize the image in scholarX archive page

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#585]
**Is your feature request related to a problem? Please describe.**
- Current card-image is bigger than what we need. (2000x2000)

**Describe the solution you'd like**
- Resize the image 
- Use CSS if you need to crop the image.
![Screenshot from 2020-03-03 09-31-46](https://user-images.githubusercontent.com/43912578/75741850-d9f95c00-5d31-11ea-96b8-c0792bf4ad8f.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by Suthan97** [comment]
I will do it.

**Comment by anjula-sack** [comment]
Ok :)
