### ISSUE TITLE
Issue on FAQ card style

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#587]
**Describe the bug**
A border that doesn't follow the style guidelines is displaying on the FAQ cards.

**To Reproduce**
1. Go to 'https://sefglobal.org/scholarx/2020/'
2. Scroll down to 'FAQ section'
3. See error

**Expected behavior**
N/A

**Screenshots**
![ScholarX_Sustainable_Education_Foundation_-_2020-03-04_23 38 13](https://user-images.githubusercontent.com/27498587/75909389-06b48d00-5e72-11ea-99ff-8ceed46d12c8.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04
 - Browser: Google Chrome
 - Version: 79.0.3945.88 (Official Build) (64-bit)

**Additional context**
N/A

**Comment by Gravewalker666** [comment]
@Piumal1999 Does this bug still linger? I checked several times but I don't see this preview in my localhost or sefglobal.org. Can you check from your environment again and see if it's still there?

**Comment by Piumal1999** [comment]
Error still occurs on my environment. Maybe its because my browser is not updated to the latest version. I think it's ok to close this issue if no one else is facing this bug.

**Comment by jayasanka-sack** [comment]
It has been reported by @99sumedha too. ( On firefox I guess )  @99sumedha Could you please provide your environment details?

Try to use a testing tool to check browser compatibility.

**Comment by akshika47** [comment]
It happens on Safari (Mac OS) as well. What seems to be the problem?

**Comment by Gravewalker666** [comment]
I'll have a look and try to solve this one.
