### ISSUE TITLE
Align hero image to center in archive page

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#590]
**Describe the bug**
- Hero image in the archive page is not properly aligned in mobile view.

**To Reproduce**
1. Go to archive page
2. Go to mobile view
3. See error

**Expected behavior**
- Center the image in mobile view

**Screenshots**
![Screenshot from 2020-03-07 11-06-28](https://user-images.githubusercontent.com/43912578/76137500-c583cf00-6063-11ea-9ee9-d7be565d0e77.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Browser : chrome

**Additional context**

**Comment by AselSiriwardena** [comment]
I'll do this one

**Comment by jayasanka-sack** [comment]
Okay! :)
