### ISSUE TITLE
Display upcoming events within the OneLive page.

### ISSUE THREAD

**Issue by AuraOfDivinity** [sef-global/sef-site#604]
**Is your feature request related to a problem? Please describe.**
In the current site if a user wants to view the upcoming OneLive events and clicks on the "See upcoming events button" he is then redirected to Facebook.  

**Describe the solution you'd like**
It would be more convenient if we could display the upcoming events on the site itself without having to redirect to Facebook.

**Comment by Piumal1999** [comment]
I'll do this. Let me do some research on this and inform you soon.😁

**Comment by nisan-abeywickrama** [comment]
We can use the facebook Graph API.  I need the necessary authentication for the account to get the user events.
**https://developers.facebook.com/docs/graph-api/reference/event/**
