### ISSUE TITLE
Create new page on SEF Website for Events

### ISSUE THREAD

**Issue by bpdesilva** [sef-global/sef-site#61]
Create new page on SEF Website for events. Please include all our onelive and psychical events like SEF 360.

**Comment by jayasanka-sack** [comment]
ack.

**Comment by bpdesilva** [comment]
@jayasanka-sack Required Change or please re create a page for portfolio then include the above.

**Comment by akshika47** [comment]
Please put a link to the SEF360 page in the main page(sefglobal.org).
