### ISSUE TITLE
Update scholarX 2020 mentors details

### ISSUE THREAD

**Issue by saumiyaa** [sef-global/sef-site#618]
**Is your feature request related to a problem? Please describe.**

- Error in mentor title

**Describe the solution you'd like**

- Change 'Assistant' to 'Associate' for Nishanta Rajakaruna in `mentors.json` 

https://docs.google.com/spreadsheets/d/1zOEfTBTTBDdDKcafHI44CY73v2obLEnnOupNBzzO0Do/edit#gid=193573752  (highlighted in blue)

**Comment by anjula-sack** [comment]
I'm working on this.
