### ISSUE TITLE
Uncaught SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by nisan-abeywickrama** [sef-global/sef-site#620]
**Is your feature request related to a problem? Please describe.**

The console logs an **"Uncaught SyntaxError: Unexpected token 'export'"**  in popper.min.js

**Comment by jayasanka-sack** [comment]
Thanks for pointing it out @nisan-abeywickrama !

**Comment by yozaam** [comment]
Great catch but seeing as "popper.min.js" is part of an external CDN, I feel like there is nothing to be done on our side, can we close the issue?

Unless this is because of calling the CDN twice in the same webpage?
