### ISSUE TITLE
Create a dummy video gallery for past onelive 

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#624]
**Is your feature request related to a problem? Please describe.**
- We need a one live video archive to show videos from our SEF youtube channel. 

**Describe the solution you'd like**
- There's an index in `onelive/archive` directory.
- Add a button called show more because we will be showing 5 items per time.

**Comment by anjula-sack** [comment]
I'm working on this.

**Comment by Gravewalker666** [comment]
@anjula-sack show more icon won't be necessary, If you are going for a specific video archive page. Isn't it? Or at least load like 10, 15 videos in the page. 
Put 3 or 5 videos in the one live landing page and add a show more button there to redirect to video archive page.

**Comment by anjula-sack** [comment]
@Gravewalker666 ok, for now, this page is dummy page content won't be loaded.
