### ISSUE TITLE
Capitalize Frequently Asked Questions in Onelive page

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#665]
**Describe the bug**
Some questioned isn't capitalized. 

**To Reproduce**
1. Visit: https://sefglobal.org/onelive/
2. Navigate to FAQ section

**Expected behavior**
Capitalize the first letter of each question

**Screenshots**
![image](https://user-images.githubusercontent.com/33048395/79688129-bf3f6000-8269-11ea-9099-8e66c9a96c67.png)

**Comment by ManojLL** [comment]
I'm working on this
