### ISSUE TITLE
Typos in SEF Website

### ISSUE THREAD

**Issue by miluckshan-j** [sef-global/sef-site#709]
**Describe the bug**
There are some spelling mistakes in a few pages

[Home](https://sefglobal.org/)
* Change Projects -> Onelive under header to 'OneLive'

[ScholarX](https://sefglobal.org/scholarx/2020/)
* Change button text 'CHECKOUT...' to 'CHECK OUT' in archives section

[Meet Our Team](https://sefglobal.org/team.html)
* Change '... Motion Miricales,Wibble ...' to '... Motion Miracles, Wibble ...' under Consultants

**Comment by Gimhan-minion** [comment]
Are you working on this @miluckshan-j

**Comment by jayasanka-sack** [comment]
Thanks for pointing these typos @miluckshan-j!

**Comment by nejawittatchy** [comment]
I'm working on this
