### ISSUE TITLE
Add SEF gmail to the website

### ISSUE THREAD

**Issue by akshika47** [sef-global/sef-site#723]
**Is your feature request related to a problem? Please describe.**
SEF Gmail is not shown on our website. It should be added

**Describe the solution you'd like**
Add the SEF Gmail (info[AT]sefglobal[DOT]org) on the website. It needs to be obvious for anyone to contact us. Looking for a suggestion on where to place the email address as well.

**Comment by bhagyesh2000** [comment]
Hello, Should I add "Email-Us" next to social media icons at the bottom? I think it won't be good to add on top of the website so it would look better on the bottom of the website

**Comment by yozaam** [comment]
> Hello, Should I add "Email-Us" next to social media icons at the bottom? I think it won't be good to add on top of the website so it would look better on the bottom of the website

Sounds good, since there are already four icons on top 👍

**Comment by akshika47** [comment]
@bhagyesh2000 yes, that sounds good.

**Comment by yozaam** [comment]
We have nucleo, fontawesome, and argon CDN's you'll easily find an ✉️ or @ icon in these three, 
it's preferable not to add any dependencies, 
also make sure all pages display it in the footer ( it will since it is a static component :) 
all the best
