### ISSUE TITLE
Add stylings to the apply button on join us page

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#756]
**Describe the bug**
The button doesn't have a raising animation like all other button. Also when hovering, the color of text turns to blue.

**To Reproduce**
1. Go to 'https://sefglobal.org/join-us.html'
2. Scroll down
3. See error

**Expected behavior**
A raising animation for the button
When hovered, the colour shouldn't change

**Screenshots**
![IMG_20200825_232837](https://user-images.githubusercontent.com/27498587/91210368-bcc6a880-e72a-11ea-866f-9988594e3af7.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 19.04
 - Browser [e.g. chrome, safari] Google Chrome

**Additional context**
You can refer other pages to fix this

**Comment by AlexARNcode** [comment]
Hi, Can I work on that?

**Comment by Piumal1999** [comment]
> Hi, Can I work on that?

@AlexARNcode 
Yes of course❤️🤩. 
Also join our gitter channel. https://gitter.im/sef-global/community
Thank you
