### ISSUE TITLE
Add a loading animation for onelive archive cards

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#757]
**Is your feature request related to a problem? Please describe.**
When the load more button on https://sefglobal.org/onelive/archive/ is clicked, the cards load instantly.

**Describe the solution you'd like**
Add a fading or any other suitable loading effect to trigger when the load more button is clicked.

Hint:
1) you can find the loading function here --> "/onelive/archive/functions.js"

2)`$(renderedHtmlContent).appendTo('#youtube-videos').hide().fadeIn(1000);`
This gets renderedHtmlContent --> appends it to youtube-videos --> Hide it --> FadeIn

also, you can refer the fading command in "loadProfiles" function in "/onelive/functions.js" file.

**Describe alternatives you've considered**
N/A

**Additional context**
Please put a comment on the issue before start working on the issue

**Comment by nisan-abeywickrama** [comment]
I am working on this issue
