### ISSUE TITLE
Page not found 404 notice for fellowship

### ISSUE THREAD

**Issue by Gravewalker666** [sef-global/sef-site#759]
**Is your feature request related to a problem? Please describe.**
In fellowship public UI when the id doesn't match an existing certificate, it renders a blank page.

**Describe the solution you'd like**
Need to render Page not found 404 notice when there is no certificate for the requested id.

**Additional context**
For additional details on the project please refer [this](https://sef.discourse.group/t/developing-an-admin-platform-for-sef-fellowship-program/20?u=gravewalker) thread.

**Comment by nisan-abeywickrama** [comment]
Can i be assigned to work on this issue?

**Comment by Gravewalker666** [comment]
Sure @nisan-abeywickrama
