### ISSUE TITLE
Adding Partners and Collaborators to the main website

### ISSUE THREAD

**Issue by akshika47** [sef-global/sef-site#76]
We need to add the following partners and collaborators in the main website.

- Aiesec
- Rotaract
- IEEE INSL
- Royal College Astronomical Society
- WSO2
- University societies that we have partnered with for events(check the correct name of the org)
   - University of Sabaragamuwa IT society (check with Tharika)
   - University of Moratuwa Entrepreneurship Society
   - University of Uva Wellassa Computer Science Society 
   - SLIIT FOSS(I think, check with @hasitha95 )
   - IIT (check with @bpdesilva) - There was another organisation we partnered on this project, need to 
     check that.
   - University of Kelaniya
   - UCSC Open source society(need to check the name with @ivantha)
- Happy Sri Lankans
- Hatch
- oDoc
- Lanka Software Foundation
- FOSS.lk
- Mozilla 
- UDecide
- All the sponsors from SEF360 event if they are not already added

There are some more which I might have missed, so please put them in the comment section.

**Comment by akshika47** [comment]
Some I have missed.

- Without Borders
- Coursenet
-  CIMA Students Association (check the right name on that)
-  St. Anthony's college Computer Society (it had a different name @jayasanka-sack knows)
- Motion Miracles

**Comment by jayasanka-sack** [comment]
I'll take care about this

**Comment by jayasanka-sack** [comment]
@Gravewalker666 Could you please complete this?

**Comment by Gravewalker666** [comment]
ok sure

**Comment by Gravewalker666** [comment]
Done!
Added all the stuff except universities.Please double check the links I'm not sure if these are official web sites or not

**Comment by jayasanka-sack** [comment]
#77

**Comment by jayasanka-sack** [comment]
Merged Pull Request #77 
Nice work @Gravewalker666 🥇 💯 
I'll try to find missing logos

**Comment by akshika47** [comment]
Good job.  There are two minor issues related to this issue.
https://github.com/SustainableEducationFoundation/LiveWeb/issues/79
https://github.com/SustainableEducationFoundation/LiveWeb/issues/80

**Comment by Gravewalker666** [comment]
#78

**Comment by jayasanka-sack** [comment]
merged Pull Request #78

**Comment by bpdesilva** [comment]
Commented refer #80
