### ISSUE TITLE
CSS issue in join-us page FAQ section

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#770]
**Describe the bug**
In the Join-Us page FAQ section, CSS is not the same as the rest of the FAQ sections which are in One-Live page, ScholarX etc. We need to follow the same CSS settings which are used in the rest of the FAQ sections to make the website look more consistent. Even the `+` button to expand the card is also in a different colour.

**To Reproduce**
1. Join-us page
2. Scroll down to the FAQ section 
3. Go to the One live page
4. See the difference.

**Expected behavior**
Join-us Page should also use the same CSS setting for FAQ which are used by the rest of the pages

**Comment by yozaam** [comment]
~I'm working on this~  @shivangigoel1302 nice work

**Comment by shivangigoel1302** [comment]
hey can you assign this to me

**Comment by Piumal1999** [comment]
> hey can you assign this to me

Sure! I'll assign you for the issue.

**Comment by shivangigoel1302** [comment]
I have made the PR #778

**Comment by shivangigoel1302** [comment]
> > hey can you assign this to me
> 
> Sure! I'll assign you for the issue.
I have made the PR #778. do check
