### ISSUE TITLE
Update Onelive "Apply" button to "Apply Now"

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#773]
**Is your feature request related to a problem? Please describe.**
The "Apply" button on "Be a onelive speaker" section on onelive page (sef-site/src/main/webapp/onelive/index.html) have to be changed to "Apply Now" 

![IMG_20201001_234134](https://user-images.githubusercontent.com/27498587/94847699-8d4d3f00-0440-11eb-8c79-ff83a8d0b864.jpg)

**Describe the solution you'd like**
Update the button text

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by sharmashantanu** [comment]
Working on it.

**Comment by yashgajaria** [comment]
Created a PR for this issue #774

**Comment by ggoel1998** [comment]
Is this still open?

**Comment by priyankaagrawal123** [comment]
I am interested. I can implement.
Please assign this issue to me.
