### ISSUE TITLE
Update IRC researchers

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/sef-site#776]
**Is your feature request related to a problem? Please describe.**
We need to add these profiles to IRC researchers list

Name | Description | LinkedIn |
-- | -- | -- 
Sanjanee Waniganeththi | Nuclear Physics | linkedin.com/in/sanjanee-waniganeththi-92b3a3111
Scynthya Nirukshan | Bioscience engineering | linkedin.com/in/gertrude-scynthya-nirukshan-a213476a
Sumudu Herath | Civil Engineering | linkedin.com/in/sumuduherath
Maneesha Perera | engineering | linkedin.com/in/maneeshaperera
Madhushi Bandara | computer science | linkedin.com/in/madhushib
Udara Abeydeera | Sustainable construction | linkedin.com/in/udara-abeydeera-1797a476
Sanath Wijesinghe | Law | linkedin.com/in/sanath-sameera-wijesinghe-99699097
Paranietharan Arunagirinathan | electrical engineering | linkedin.com/in/paranietharan-arunagirinathan-07162330
Deshya Wijesundera | Digital Design,Computer Architecture | linkedin.com/in/deshya-wijesundera-phd-2b3850168

**Describe the solution you'd like**
The are few steps that have to be done when resolving this issue.
1) Go to each person's linked in profile and download the profile picture
2) Rename the image names to their first names
3) Copy the images to /src/main/webapp/assets/img/profiles/ directory (Some images may be already exist in the directory)
4) Update the /src/main/webapp/assets/content/json/irc.json with given details (Add image name for the image field, Add LinkedIn Id for the linkedin field)

Hint: You can refer these pull requests --> #767  #743 

**Describe alternatives you've considered**
N/A

**Additional context**
Please put a comment before start working on the issue. So we can assign you for it.
Feel free to contact us via Gitter(https://gitter.im/sef-global/community) if you have any doubts. 
Or you can ask on this thread --> https://sef.discourse.group/t/updating-irc-page/171/6

**Comment by Jethet** [comment]
Hello Piumal, I am new to Hacktoberfest but would like to try complete this assignment.
The description looks really clear. Can I work on this? Do you have a deadline?
Best,
Henriette

**Comment by Piumal1999** [comment]
Of course @Jethet 🤩 ! You can work on the issue. Actually we don't have a deadline for the task. It'll be great if you can complete it as soon as possible. 
I'll assign you for the issue. Feel free to contact us if you need any help from our side.

Our gitter channel : 
https://gitter.im/sef-global/community

**Comment by Jethet** [comment]
@Piumal1999 I immediately have a few questions:
When i add the code in the irc.json file, do you want to list the persons alphabetically?

Then the format of the picture: I downloaded a photo and there is quite a bit of background around the person. I am pasting the picture here. Do you want me to add the entire picture or should I make a screenshot of the person and take out as much of the background as possible?
![0-](https://user-images.githubusercontent.com/35808885/95066226-66259480-0702-11eb-8d72-2ed2c192428f.jpg)

**Comment by Piumal1999** [comment]
@Jethet Actually we are listing the profiles according to their experience and qualifications. Let's add the new profiles after "Charini Nanayakkara's" profile and before Heshan Jayawardane's profile. (You can just use the order given in the table)

For your second question, i think its better if we can crop the image a little.

**Comment by Jethet** [comment]
Thanks for the quick reaction, that's clear and I will work accordingly.

**Comment by Jethet** [comment]
@Piumal1999 Scynthya Nirukshan does not have a picture on her LinkedIn profile. Is there another image I can use? I can also message her via LinkedIn to ask for a photo, if you think that is a good idea?

**Comment by Piumal1999** [comment]
I found an image @Jethet 

https://i1.rgstatic.net/ii/profile.image/418915344764932-1476888609195_Q512/Gertrude_Nirukshan.jpg

**Comment by Jethet** [comment]
Great, thanks @Piumal1999
