### ISSUE TITLE
Update the team page

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#784]
**Is your feature request related to a problem? Please describe.**
- We need to update the team page little bit.

**Describe the solution you'd like**
 Move below names to the Alumni section
- Nimesh Ekanayake
- Francisco Hettige Cristian Silva
- Thavarasa Vithusan
- Tharika Weerakoon

Add below names under the Executive committee 
- Viraj C. Kirinda - Program Manager
- Promodini Jayakodi - Assitant Program Manager
- Aathil Ahamed - Assitant Program Manager
- Shreeharan Hareendran - Digital Marketing Executive
Use LinkedIn images for the profile image

**Comment by kartikagarwal9** [comment]
Can you Assign , i can contribute
