### ISSUE TITLE
LinkedIn icon of profile pics in teams page changes position with the window's width

### ISSUE THREAD

**Issue by YohanAvishke** [sef-global/sef-site#800]
**Describe the bug**
When changing the browser window's width LinkedIn item changes vertical position.

**To Reproduce**
1. Go to https://sefglobal.org/team.html.
2. Scroll down to a profile.
3. Change the width of the window using dev tools while hovering the profile.

**Expected behavior**
The LinkedIn icon should be in a fixed position on the profile pic.

**Screenshots**
<p float="left">
  <img src="https://user-images.githubusercontent.com/36471249/96259739-a8d94d80-0fdb-11eb-84cf-97913112dd94.png" />
  <img src="https://user-images.githubusercontent.com/36471249/96259990-ffdf2280-0fdb-11eb-8296-4b9f79b67e02.png"/> 
</p>

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 86

**Smartphone (please complete the following information):**
 - N/A

**Additional context**
N/A

**Comment by nisan-abeywickrama** [comment]
Can I work on this issue?

**Comment by janethavi** [comment]
Sure @nisan-abeywickrama! Go ahead 😊
