### ISSUE TITLE
UX improvement in IRC page 

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#801]
**Is your feature request related to a problem? Please describe.**
In the International Research Council page, there are researchers' photos. Under each photo, there is a small blue icon to visit the LinkedIn profile of each individual. But from the user's experience aspect, it would be rather difficult to click on a small icon to visit the LinkedIn profile.

**Describe the solution you'd like**
It would be much easier if we can provide an additional option to view the LinkedIn profile once the researcher's photo is clicked.
Check for [PR](https://github.com/sef-global/sef-site/pull/799) to get an idea of how to complete this issue.

**Comment by harshika18** [comment]
Hi! Can I work on this issue?

**Comment by janethavi** [comment]
Close with #802
