### ISSUE TITLE
Remove default check option from the PR template

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#803]
**Describe the bug**
In the pull request template(`pull_request_template.md`) there is a checklist to tick the completed tasks. The 1st task (`This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.`) is ticked by default. 

**To Reproduce**
1. Go to 'pull_request_template.md'
2. Scroll down to checklist
3. See that the 1st checklist is ticked by default

**Expected behavior**
This default tick should be removed otherwise contributors will skip this option without reading.

**Comment by panvicka** [comment]
Hello, can I work on this? 
Thanks.

**Comment by jayasanka-sack** [comment]
> Hello, can I work on this?
> Thanks.

Yes, please go ahead! 😊

**Comment by panvicka** [comment]
> > Hello, can I work on this?
> > Thanks.
> 
> Yes, please go ahead!

I have created the PR. I didn't know GitHub’s special keyword references before!

**Comment by jayasanka-sack** [comment]
You have been added to our leaderboard! https://sefglobal.org/github-leaderboard/ 😍

Join [SEF Hive](https://sef.discourse.group) for the discussions
