### ISSUE TITLE
Improvement: Nice to have references.

### ISSUE THREAD

**Issue by YohanAvishke** [sef-global/sef-site#805]
**Is your feature request related to a problem? Please describe.**
It's nice to have references to SEF group pages and other projects in the Readme since sef-site is considered as the main hub for our groups and projects.

**Describe the solution you'd like**
Following are few suggessions to be added,
* Discourse: https://sef.discourse.group/
* Leaderboard:  https://sefglobal.org/github-leaderboard/
* Our projects,
  * Core: https://github.com/sef-global/sef-core
  * Academix
      * Backend: https://github.com/sef-global/sef-core
      * Frontend: https://github.com/sef-global/academix-frontend
  * ScholarX 
      * Backend: https://github.com/sef-global/scholarx
      * Frontend: https://github.com/sef-global/scholarx-frontend

**Describe alternatives you've considered**
N/A

**Additional context**
This is important to spread the word to the community on what to contribute? and to stay up-to-date with SEF.
WDYT? 
Anything else that should be in the references?

**Comment by YaiyaSam** [comment]
Hey, I'd like to work on this

**Comment by Gravewalker666** [comment]
Sure, go ahead
