### ISSUE TITLE
Add social media share options

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#825]
**Is your feature request related to a problem? Please describe.**
Add social media share icons of Facebook, Twitter, Linkedin to the Scholarx 2021 mentor and student page to share the page which contains the registration form

**Comment by akeel230** [comment]
i havent worked on this kind of issue before, to add the share icon are we gonna use bootstrap? @janethavi

**Comment by janethavi** [comment]
Sorry for the confusion @akeel230. Looks like this issue is no longer needed because the ScholarX registration forms are closed.

**Comment by akeel230** [comment]
Nah thats fine..😃
