### ISSUE TITLE
Update footer for the year 2021

### ISSUE THREAD

**Issue by Gimhan-minion** [sef-global/sef-site#838]
**Is your feature request related to a problem?**
- Current footer copyright contains for the year 2020.

**Describe the solution you'd like**
- It should be updated as '2021'

**Comment by aditya28sarin** [comment]
Can you assign me this issue

**Comment by janethavi** [comment]
Sure @aditya28sarin. You can go ahead!

**Comment by aditya28sarin** [comment]
I have updated the footer and if it is fine then you can merge my pull request

**Comment by gajindubandara** [comment]
Shall I work on this?

**Comment by Gimhan-minion** [comment]
Yeah sure go ahead! @gajindubandara. Please refer https://github.com/sef-global/sef-site/pull/839 this for the latest update
