### ISSUE TITLE
Add sef360 speaker. 

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#84]
Add following person to speakers list.

SULAIMAN RAMEEZ

Sulaiman Rameez is the Chairperson of the International Youth Council in Sri Lanka (IYCSL). In 2015, he joined the Youth and Innovation wing of the United Nations Development Programme of Sri Lanka, becoming one of the youngest Sri Lankans to work for the United Nations. He is currently pursuing his Attorneys at Law at Sri Lanka Law College. During his initial years at Law College, Sulaiman was placed first at the national round of the Brown Mosten Client Consultation Competition. He also won the Sri Lanka Inter-university Debating Championship in 2016. In 2017, Sulaiman returned to be a part of “Hulftsdorp Debates”, as chairperson; opening up the tournament to international teams for the first time in its organizational history and basing the tournaments motions on the Global Goals for Sustainable Development. As the former Secretary General and current vice-president of National Youth Model United Nations, Sulaiman is a strong advocate of young people playing an active role in realizing the sustainable development goals in Sri Lanka. Prior to joining UNDP, he was elected as the District Interact Representative of Rotary District 3220, Sri Lanka and The Maldives, where he overlooked and administered 65 Interact clubs with a collective membership of over 2000 young people. In April 2018, he represented Sri Lanka at the Willem C. Vis Moot (East) Commercial Arbitration Moot in Hong Kong and ranked #6 of the 126 partaking teams.  Sulaiman is also the founder and Editor in Chief of Sri Lanka’s first Legal newsletter; “The Hulftsdorp Post”. Above all, he is an ardent environmentalist and is known to frequently scale the mountains of Sri Lanka.

![image](https://user-images.githubusercontent.com/33048395/52869635-2516f000-316c-11e9-84db-85860771f1e3.png)

**Comment by Gravewalker666** [comment]
Ok I'll do it

**Comment by Gravewalker666** [comment]
Done #86

**Comment by jayasanka-sack** [comment]
Great!
