### ISSUE TITLE
Update the blog link in the SEF Site

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#844]
**Describe the bug**
Update the blog link in the entire website to the new link `https://sefglobal.medium.com/`
Please find the blog page access places in the following places
1) Navigation Bar
2) Footer

**Expected behavior**
The blog hyperlink should be redirected to the medium SEF Channel.

**Comment by rocklikereeju00** [comment]
Can I work on this issue ?

**Comment by janethavi** [comment]
Sure go ahead! @rocklikereeju00

**Comment by rocklikereeju00** [comment]
What I write ? (know more of SEF) or (SEF blog) or link with (© 2020 Sustainable Education Foundation - SEF) . Please help me here

**Comment by anjula-sack** [comment]
Just add it as "Blog" @rocklikereeju00

**Comment by janethavi** [comment]
We need some replacements for the following places
1) [Navbar](https://github.com/sef-global/sef-site/blob/master/assets/content/static/navbar.html#L82)
2) [Footer](https://github.com/sef-global/sef-site/blob/master/assets/content/static/footer.html#L64)

The above two links(`https://blog.sefglobal.org`) are not working. We need to replace the above links to our new link which is `https://sefglobal.medium.com/`

**Comment by rocklikereeju00** [comment]
Can I make again pull request ? What happen with my request ? I am new in github please help me.

**Comment by janethavi** [comment]
Hi @rocklikereeju00,
Welcome to opensource :+1:  As I can see, you have made the changes which were requested in your PR previously. But now the PR has been closed by you. If you still have the branch you can reopen the Pull request so we can review it and merge.
