### ISSUE TITLE
Update SEF team for year 2021

### ISSUE THREAD

**Issue by Gimhan-minion** [sef-global/sef-site#848]
**Is your feature request related to a problem?**
- Current team page isn't updated to the latest position of the SEF team.

**Describe the solution you'd like**
- Change the position of Jayasanka Weerasinghe from "Cheif Technical Officer" to "Chief Executive Officer"
- Change the position of Yohan Ediriweera from "Tech Lead" to "Chief Technical Officer" and move to "Executive Committee" 
- Change the order of Heshan Andrews to the top of the Dev team

**Comment by gajindubandara** [comment]
Can you assign this to me?

**Comment by Gimhan-minion** [comment]
Yeah sure @gajindubandara !
