### ISSUE TITLE
Remove AcadeMix from site temporarily

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#853]
**Describe the bug**
AcadeMix page access needs to be removed temporarily from the following places.
1) In the navigation bar under projects, remove AcadeMix item with its link.
2) In the Index page remove the AcadeMix card under the projects section.
3) In the Index page under `At SEF, We Have Something In Store For Everyone!` section remove the link of `AcadeMix` word in the Student section.

**Comment by gajindubandara** [comment]
Can you assign this to me?
