### ISSUE TITLE
Add tool tip functionality to logs

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#854]
**Is your feature request related to a problem? Please describe.**
In the index page when you scroll down to the press coverage section there is a list of logos. The logo names could not be found. Because of that reason, it is hard to find out what the organizations are.

**Describe the solution you'd like**
Add the tooltip functionality to the logo image. [Bootstrap tooltip](https://getbootstrap.com/docs/4.0/components/tooltips/) can be used for this purpose. We need the tooltips on the bottom of the logo. A sample image can be seen underneath.
![Screenshot from 2021-02-06 21-44-05](https://user-images.githubusercontent.com/35697678/107123726-1d0a6a80-68c5-11eb-9116-6363dc181674.png)

The names of the logos from left to right are as follows.
1) Pulse
2) ReadMe LK
3) SBS Sinhalese
4) IVolunteer International

**Comment by kumuditha-udayanga** [comment]
@janethavi  I'm working on this issue 🙂.
