### ISSUE TITLE
Change README logo

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#857]
**Describe the bug**
In the home page, press coverage section the readme press coverage logo needs to be updated. Replace the existing logo with the new logo.

**To Reproduce**
1. Go to 'https://sefglobal.org/'
2. Scroll down to 'Press Coverage'
3. See old logo of `Readme`

**Expected behavior**
The new logo needs to be added. Adjust the size of the new logo to match the rest of the logos on the home page. The new logo should not affect the consistency look with the rest of the logos.
![107512208_3369757173073130_4804089304883641529_o](https://user-images.githubusercontent.com/35697678/107602390-4aea0900-6c4f-11eb-9384-f4c8afa97d4c.png)

**Comment by AlexARNcode** [comment]
Hi, is the red background on purpose? Because all other logos of this section have a transparent background.

**Comment by janethavi** [comment]
Hi @AlexARNcode, the red background is mandatory because it's their logo. But you can do something like this. You can use this logo and crop it to a rectangle. So this logo won't look odd in that place.

**Comment by AlexARNcode** [comment]
Ok then, I'd like to work on this if that's ok with you? I've already resized the image to fit the other ones (same ratio, same height).

**Comment by janethavi** [comment]
Great to hear @AlexARNcode ! You may start working on this issue.
