### ISSUE TITLE
Update cards look in Onelive Page

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#858]
**Describe the bug**
In the [Home](https://sefglobal.org), `Our Project` section there are curvy edged cards. In the [One Live ](https://sefglobal.org/onelive/) page, `Take a look at our past One Lives` section there are a different set of cards(not curve edged cards)

**To Reproduce**
1. Go to 'One Live page' (From navigation bar Projects-> Onelive)
2. Scroll down to 'Take a look at our past One Lives'
3. See the inconsistency

**Expected behavior**
One Live `Take a look at our past One Lives` cards need be changed to curve edged cards. So One Live cards will look like home page cards. Use the exact CSS which is used in the Home page curve cards to keep the consistency.

**Comment by kangkanjr** [comment]
I will work on this.

**Comment by janethavi** [comment]
Sure @kangkanjr go ahead!

**Comment by larabee7777** [comment]
Hi everyone, I'm a beginner and I'd like a coding mentor and to help this project because it is about educational empowerment and that is close to my heart. I'm a native English speaker and have basic knowledge of HTML, CSS, Javascript, VB and cloud. I sent a message on Gitter too.

**Comment by larabee7777** [comment]
Hi I'd like to contribute if this is still open

**Comment by janethavi** [comment]
Hey, @kangkanjr Are you working on this issue?

**Comment by ashwindevx** [comment]
Hey @kangkanjr 

I'm looking to contribute to this issue.

Can you tell which folder has `Take a look at our past One Lives` code? I can't find it.

**Comment by kangkanjr** [comment]
@ashwindevx the task seemed quite easy but the documentation of the code base is not done properly, so I couldn't do too.

**Comment by ashwindevx** [comment]
> Hey @kangkanjr
> 
> I'm looking to contribute to this issue.
> 
> Can you tell which folder has `Take a look at our past One Lives` code? I can't find it.

@janethavi can you help?

**Comment by jayasanka-sack** [comment]
> Hey @kangkanjr
> 
> I'm looking to contribute to this issue.
> 
> Can you tell which folder has `Take a look at our past One Lives` code? I can't find it.

@ashwindevx I think this is the code you are looking for:
https://github.com/sef-global/sef-site/blob/28918a31433c5299343f8198dfe57007bc6427a7/onelive/index.html#L315

It's using mustache.js to render the cards. Editing the template would sufficient.

**Comment by janethavi** [comment]
Hi @ashwindevx! Shall I assign you to this issue?

**Comment by YaiyaSam** [comment]
hey, i would like to work on this

**Comment by janethavi** [comment]
Sure @YaiyaSam! go ahead
