### ISSUE TITLE
Change card view in scholarx

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#867]
**Describe the bug**
In the Scholarx page featured stories section, there are a set of cards. Those are different from the home page cards. 

**To Reproduce**
1. Go to `ScholarX page` (from navigation-> projects-> ScholarX)
2. Scroll down to `Featured Stories` section
3. Got to `Home page`
4. Scroll down to `Our Projects` section
5. See the difference

**Expected behavior**
The `Scholarx page`,` Featured Stories` cards need to be similar(with curved edges) to the `Home page` `Our Projects` cards. 
The images on the featured stories cards need to be fitted into the new curved cards.

**Comment by AlexARNcode** [comment]
Hi, I would be glad to work on that! :)

**Comment by janethavi** [comment]
Sure @AlexARNcode You can work on this issue!

**Comment by AlexARNcode** [comment]
Work in Progress : I'm applying the same exact style as the main homepage, but we're facing a little problem for the footer cards : The author and "x min read" are on 2 lines, which doesn't look good : 

![sef-card-wip](https://user-images.githubusercontent.com/53975649/108188220-9d27a000-710f-11eb-9bb7-498b67ecc471.png)

What should we do : 
- Put the author and the "x min read" on seperate lines ?
- Reducing the font size of the author name ?
- Something else ?

I've searched on the website if they were other examples of cards with this kind of data inside, but I didn't find any to take example from.

**Comment by janethavi** [comment]
@AlexARNcode Will you be able to increase the size(most probably the width) of the cards a bit more? So after doing that you might be able to fit the content to it.  If that doesn't work you may reduce the font size a bit. It would be nice if you can stretch the images to fit the whole top part of the card. I have attached a sample card below for more clarity. 

![sef card](https://user-images.githubusercontent.com/35697678/108368084-13b3c300-7220-11eb-8233-44e459d46ba1.png)

**Comment by AlexARNcode** [comment]
![Capture d’écran 2021-02-19 à 16 23 56](https://user-images.githubusercontent.com/53975649/108524138-03a6ec80-72cf-11eb-95fc-997387909e9e.png)

I think this is better, right?

**Comment by janethavi** [comment]
Will you be able to remove the padding between the card and the image? So it would be consistent. There is [another place](https://sefglobal.org/scholarx/2021/) we have these cards. So for consistency, we need to make all the cards look alike. 

Also another few suggestions 
1) Will you be able to make all the images the same size? 
2) Will you be able to make the font a bit bigger than this? (It will be more visible)
3) Also, the clock icon is not properly aligned to the reading time. Will you be able to fix that too?  
For reference, you can check the [Scholarx page](https://sefglobal.org/scholarx/2021/)

**Comment by AlexARNcode** [comment]
Hi,

> Will you be able to remove the padding between the card and the image? So it would be consistent. There is [another place](https://sefglobal.org/scholarx/2021/) we have these cards. So for consistency, we need to make all the cards look alike.

The link you gave me as example is precisely what is asked to be changed, so I'm a bit confused now : 

Should we make all cards look like Home page Our Projects cards (which is what I've understood), or should we make all cards look like Scholarx page, Featured Stories (which is what I understood that needed to be changed)?

Anyway, I understood your other 3 points.

Sorry if my questions are dumb 👍

**Comment by janethavi** [comment]
Sorry if this made any confusions. I explain a bit more. 
1) The card edges need to be curved so the **card** should look like the card which is on the [Home page](https://sefglobal.org/). 
2) The **content** on the card should be something like in the [ScholarX](https://sefglobal.org/scholarx/2021/) card. This means the image should be fitted to the card size and there should be no padding between the card and the image. 

**For more clarification, you can check the design which I have shared previously on this thread. This is what we are actually looking for.**
 
As I can see in the screenshot you have shared, You have done the `1st` step.  Thank you very much for that. It would be great if you can check into the 2nd point which I have mentioned. 

Hope you got the issue clarified. 💯

**Comment by AlexARNcode** [comment]
Don't be sorry mate, I should be the one to be :D !

Here it is (_please click on the image to view it full size_) :

![sef-site-cards-wip](https://user-images.githubusercontent.com/53975649/108604918-172a8400-73b1-11eb-8ffd-be27df01dd7d.png)


What font did you want to increase ? The title, the author, the "x min read", or a mix of that?

**Comment by janethavi** [comment]
Wonderful work @AlexARNcode!  Will you be able to increase the title font size a bit more? Also, the author name needs to be increased a bit more too. But the author name font size should be less than the title font size.

**Comment by AlexARNcode** [comment]
Thanks @janethavi :) !

Here you go :

![Screenshot_2021-02-21 ScholarX Sustainable Education Foundation](https://user-images.githubusercontent.com/53975649/108627028-b2743580-7453-11eb-95ee-637269814324.png)

Another thing : I realized that the first card's link is broken (https://blog.sefglobal.org/2019/11/scholarx-class-of-2019-sx19/). Should I change that in the same time, or will it be for another issue?

**Comment by janethavi** [comment]
Thank you for all the hard work @AlexARNcode! You have done a great job. You can put a PR. Me and another person will review it.
And for the blog link issue, will you be able to create an issue?

**Comment by akeel230** [comment]
Hey , @janethavi i would like to work on this.
