### ISSUE TITLE
Remove unwanted button in OneLive page

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#870]
**Describe the bug**
In the [OneLive Page](https://sefglobal.org/onelive/) `Take a look at our past One Lives` section there is a button called `SEE MORE`. But on other pages such as the [Team Page](https://sefglobal.org/team.html) `Alumni` section, there is just a hyperlink and no button. 

**To Reproduce**
1. Go to `Onelive Page`  and to the `Teams page`
2. See the difference.

**Expected behavior**
The `SEE MORE` button of the Onelive page should be removed and there should only be a hyperlink just as the Teams page.

**Comment by josemsanchez** [comment]
Can you assign this to me?

**Comment by janethavi** [comment]
Sure! Go Ahead 👍
