### ISSUE TITLE
Remove unwanted button in OneLive Archive page

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#871]
**Describe the bug**
In the [OneLive Archive Page](https://sefglobal.org/onelive/archive/) there is a button called `LOAD MORE`. But on other pages such as the Team Page `Alumni section`, there is just a hyperlink and no button.

**To Reproduce**
1) Go to `Onelive Archive` Page and to the `Teams` page.
2) See the difference.

**Expected behavior**
The `LOAD MORE` button of the Onelive page should be removed and there should only be a hyperlink just like the Teams page.

**Comment by YaiyaSam** [comment]
Hey, i would like to work on this

**Comment by Gravewalker666** [comment]
Hello @YaiyaSam,
Sure dude
