### ISSUE TITLE
Responsive Problem with Project Logos

### ISSUE THREAD

**Issue by akshika47** [sef-global/sef-site#881]
**Describe the bug**
When reducing the size of the web browser or the mobile view. The logos of the projects over-flows of their respective container (box). 

**To Reproduce**
1. Reduce the size of the browser or check-in mobile view

**Expected behavior**
Logos should stay within their container.

**Screenshots**
![image](https://user-images.githubusercontent.com/4003135/109374727-4d01c800-78dd-11eb-8b60-aa4bac4a119e.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: Google Chrome
 - Version: 10.15.3

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by hachi-studio** [comment]
@akshika47 I can fix this for you, feel free to assign it to me!

**Comment by hachi-studio** [comment]
On a side note I think the cards should go into a single col layout at a different breakpoint as it currently is display as a 3 col layout at 576px

**Comment by akshika47** [comment]
@janethavi would you be able to review this PR?
