### ISSUE TITLE
Update Team Page

### ISSUE THREAD

**Issue by akshika47** [sef-global/sef-site#889]
**Is your feature request related to a problem? Please describe.**
Team Page Needs to be updated as it is outdated. 

**Describe the solution you'd like**
1. Move retired volunteers to the Alumni Section
2. Add the latest volunteers to the Team page.

**Describe alternatives you've considered**
N/A

**Additional context**
This Issue needs more information to complete. Therefore, the person who works on this has to communicate with the management team to get information.

**Comment by akshika47** [comment]
@janethavi @jayasanka-sack shall we get this issue started? I have already created a Google form and shared it with the ScholarX team to gather head-shots. They are stored in the SEF Gmail Google Drive.

**Comment by janethavi** [comment]
Sure @akshika47! Is the data collection completed? So we can use the sheet to update the website.

**Comment by akshika47** [comment]
Yes, I have shared a Google Sheet with you. The second sheet contains details that are required for this issue.
