### ISSUE TITLE
Update the application form

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#894]
**Is your feature request related to a problem? Please describe.**
The apply.html page should be updated with the new application form.

**Describe the solution you'd like**
https://github.com/sef-global/sef-site/blob/dae6d8fd87045067f356ababe7eba1a4b4c6fe70/apply.html#L53
Replace the form link with the following:
https://docs.google.com/forms/d/e/1FAIpQLSdmgzDfHQkCi8YoOcH1god-uFqNL0HMPfu3YarHl5OIM17zwA/viewform?embedded=true

**Comment by kumuditha-udayanga** [comment]
Can I work on this issue?

**Comment by jayasanka-sack** [comment]
Sure, go ahead!
