### ISSUE TITLE
Remove unwanted directory and resources 

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#900]
**Describe the bug**
There is an unwanted directory that is not a part of the website. Remove the `examples` directory from the codebase. In that directory, there is a page called team.html On that page there are some profile images. Those profile images should also be removed from the repository. The corresponding JSON file should also be removed. It can be found in `assets/content/json/dummy-profiles.json`

**To Reproduce**
1. Go to '/examples/'
2. You can view each unwanted page 
3. Go to '/examples/team.html'
4. See the unwanted profile images

**Comment by YaiyaSam** [comment]
Hi, can you assign me to this issue?

**Comment by Gravewalker666** [comment]
@YaiyaSam Awesome, go ahead
