### ISSUE TITLE
Remove example directory of images from the repository

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#903]
**Describe the bug**
In the `/assets/img/` location there is a directory called examples. Double-check to confirm those images are not in use and remove the entire `/examples` directory. 

**To Reproduce**
1. Open the repo.
2. Go to `/assets/img/` location

**Comment by gajindubandara** [comment]
Can you assign this to me?

**Comment by janethavi** [comment]
Sure @gajindubandara Go ahead!
