### ISSUE TITLE
Spelling mistake in archive ScholarX page(2019)

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#904]
**Describe the bug**
In the `https://sefglobal.org/scholarx/archive/2019/` There are two FAQ sections for mentors.

**To Reproduce**
1. Go to 'https://sefglobal.org/scholarx/archive/2019/'
2. Scroll down and find both sections

**Expected behavior**
The second section should be changed to  `FAQ for Mentees`

**Comment by sabiat** [comment]
Sorry, I should have asked to have this assigned to me before working on it. Is it ok that I worked on it?
