### ISSUE TITLE
Hitcount Badge not working

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#907]
**Describe the bug**
In the README.md file the `Hit Count` Badge is not working. The domain of the URL should be changed to `.com` insdead of `.io`
`[![HitCount](http://hits.dwyl.com/sef-global/sef-site.svg)]`

**To Reproduce**
1. Check out the repository README.md file
4. See the hit count badge

**Expected behavior**
The hitcount should work.

**Screenshots**
![Screenshot 2021-04-06 120408](https://user-images.githubusercontent.com/35697678/113668677-3adf2a80-96d0-11eb-84ec-dcee354504cf.png)

**Comment by nejawittatchy** [comment]
I would like to work with this

**Comment by anjula-sack** [comment]
Sure. Go ahead! @nejawittatchy
