### ISSUE TITLE
Switch cards in the Scholarx archive page

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#908]
**Describe the bug**
On the `https://sefglobal.org/scholarx/archive/` page we have 2019 card 1st and 2020 card afterwards. It would be much better if we can have the 2020 card 1st and 2019 card afterwards.

**To Reproduce**
1. Go to 'https://sefglobal.org/scholarx/archive/'
2. Scroll down to 'Take a look at our past ScholarX' section
3. See on the left side we have 2019 card and on the right side, we have 2020 card.

**Expected behavior**
The 2020 card should be on the left side and the 2019 card should be on the right side. (switch the sides of the card)

**Comment by gajindubandara** [comment]
Can you assign this to me?
