### ISSUE TITLE
Remove warning notification on scholarx 2020 page

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#909]
**Describe the bug**
In the [https://sefglobal.org/scholarx/archive/2020/](https://sefglobal.org/scholarx/archive/2020/) page a warning message pops on top. 

**To Reproduce**
1. Go to [https://sefglobal.org/scholarx/archive/2020/](https://sefglobal.org/scholarx/archive/2020/)
2. See the warning message saying `Please notice that application for scholarX has been closed`

**Expected behavior**
This warning message should be removed entirely.

**Comment by YaiyaSam** [comment]
Hey, can I work on this?

**Comment by janethavi** [comment]
Sure go ahead! @YaiyaSam
