### ISSUE TITLE
Remove the old version of ISSUE_TEMPLATE

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#910]
**Describe the bug**
The old version of `ISSUE_TEMPLATE` can be found on the repository `sef-site/ISSUE_TEMPLATE.md` This is an old version of `ISSUE_TEMPLATE.md`. We currently use the new version of the issue template (`sef-site/.github/ISSUE_TEMPLATE/`). 

**To Reproduce**
1. Go to 'sef-site/ISSUE_TEMPLATE.md' in the repository

**Expected behavior**
Remove the old version of `ISSUE_TEMPLATE.md` completely. This old version can be found on `sef-site/ISSUE_TEMPLATE.md`

**Comment by gajindubandara** [comment]
Can you assign this to me?
