### ISSUE TITLE
On mobile view homepage carousel is not vissible properly

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#916]
**Describe the bug**
On the home page testimonials carousel section is not properly visible on the mobile view

**To Reproduce**
1. Go to 'home'
2. Scroll down to `testimonies` section
3. Load the page on mobile view
4. See the issue

**Expected behavior**
The carousel with testimonies should be properly visible

**Screenshots**
![Screenshot from 2021-04-17 11-29-17](https://user-images.githubusercontent.com/35697678/115103623-f295f700-9f70-11eb-8c27-912a726756a1.png)

**Comment by akshika47** [comment]
Thank you for picking this up! I also had the same problem.

**Comment by pasindur99** [comment]
I would like to work on this.!
