### ISSUE TITLE
Remove unwanted content from the scholarx2020 archive page

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#917]
**Describe the bug**
On the [scholarx2020 page](https://sefglobal.org/scholarx/archive/2020/), there are some unwanted content that needs to be removed.

**To Reproduce**
1. Go to [https://sefglobal.org/scholarx/archive/2020/](https://sefglobal.org/scholarx/archive/2020/)
2. Scroll down until FAQ for mentors, FAQ for mentees, Take a look at our past ScholarX and Find a mentor for me

**Expected behavior**
These entire sections need to be removed from the scholarx2020 page.
1) FAQ for mentors
2) FAQ for mentees
3) Take a look at our past ScholarX 
4) Find a mentor for me

**Comment by gajindubandara** [comment]
Can you assign this to me?
