### ISSUE TITLE
Remove unwanted content from the scholarx2019 archive page

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#918]
**Describe the bug**
On the [scholarx2019](https://sefglobal.org/scholarx/archive/2019/) page, there are some unwanted content that needs to be removed.

**To Reproduce**
1) Go to [https://sefglobal.org/scholarx/archive/2019/](https://sefglobal.org/scholarx/archive/2019/)
2) Scroll down until FAQ for mentors, FAQ for mentees, Find a mentor for me

**Expected behavior**
These entire sections need to be removed from the scholarx2020 page.
1) FAQ for mentors
2) FAQ for mentees
3) Find a mentor for me

**Comment by gajindubandara** [comment]
Can you assign this to me?
