### ISSUE TITLE
Create a table for 2020 scholarx mentees

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#921]
**Is your feature request related to a problem? Please describe.**
In the archive section of scholarx2020 a table needs to be created to add the mentees to the website.

**Describe the solution you'd like**
The table should contain an image, name, mentor and the university or a single mentee. When clicked on a single mentee the LinkedIn profile should be redirected. The data file can be found [here](https://docs.google.com/spreadsheets/d/1UquBXrpWIxdLdy5vOeflvtaKUgv6z-GhVMLK-g44gPU/edit#gid=0)

In the sheet scroll down for 2020(cell A24 onwards) The sheet format is as follows.
Column A:- Mentor Name.
Column D:- Students for the mentor.
Column E:- LinkedIn Link of the student.
Column F:- University of the student.

These data should be used when creating the table. The table format can be found [here](https://sefglobal.org/scholarx/archive/2019/)

When a student is selected from the table row his/her LinkedIn profile should be redirected. 
The image of the mentee can be taken from each individual's LinkedIn account.

**Comment by YaiyaSam** [comment]
Hey, I would like to work on this

**Comment by janethavi** [comment]
Sure go ahead! @YaiyaSam
