### ISSUE TITLE
Student Ambassador page not responsive in larger screens

### ISSUE THREAD

**Issue by nejawittatchy** [sef-global/sef-site#926]
****Describe** the bug**
In the Student Ambassador page the image is too large in large screen view.
**To Reproduce**
1. Go to Projects
2. Click on Student Ambassador
3. Scroll down

**Expected behavior**
The image should be smaller and right aligned.

**Screenshots**
<img width="1437" alt="Screenshot 2021-04-20 at 20 39 21" src="https://user-images.githubusercontent.com/59279435/115424723-948d3c00-a21c-11eb-99c5-f9af005206a4.png">
<img width="1437" alt="Screenshot 2021-04-20 at 20 41 40" src="https://user-images.githubusercontent.com/59279435/115424746-9951f000-a21c-11eb-934b-3977ed2f2925.png">
<img width="1437" alt="Screenshot 2021-04-20 at 20 42 03" src="https://user-images.githubusercontent.com/59279435/115424757-9c4ce080-a21c-11eb-8ca7-cec11194a795.png">

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur
 - Browser: Safari
 - Version: 14.0.3

**Comment by kumuditha-udayanga** [comment]
@nejawittatchy Can I work on this issue

**Comment by Chris-Blesson** [comment]
Hi @nejawittatchy I would like to work on this issue. Also will it be possible to make it hacktoberfest accepted. Thanks in advance

**Comment by Priyanka11-dev** [comment]
Hey @nejawittatchy,
can i work on this?

**Comment by nejawittatchy** [comment]
> Hey @nejawittatchy,
> can i work on this?

Sure go ahed @Priyanka11-dev

**Comment by Priyanka11-dev** [comment]
Hey @nejawittatchy ,
could u plz let know the size of the screen for which its not responsive as I am not able to reproduce it.
Thanks in advance.

**Comment by Piumal1999** [comment]
Closing because the issue couldn't be reproduced
