### ISSUE TITLE
Remove Gitter link from the footer

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#937]
**Is your feature request related to a problem? Please describe.**
We don't maintain the Gitter channel anymore. Therefore, we have to remove it from the site.

**Describe the solution you'd like**
Remove the gitter icon from the footer. 

<img width="1366" alt="PNG image" src="https://user-images.githubusercontent.com/33048395/116589768-9e105580-a93a-11eb-8277-ef042f280fed.png">

**Comment by pasindur99** [comment]
May I work on this issue?

**Comment by jayasanka-sack** [comment]
Sure @pasindur99 ! Go ahead!
