### ISSUE TITLE
ScholarX - landing page

### ISSUE THREAD

**Issue by akshika47** [sef-global/sef-site#94]
Hi guys,

We need to build the landing page for ScholarX. I have put the student and mentor guide in the Wiki to find the details(attached in this post as well).

The page should include the following details.

- What is ScholarX?
- Why ScholarX?
- Mentor List with their (at least)LinkedIn links
- ScholarX Video
- Student Guide - You can take this from the Student Guide
- How to be  a ScholarX? - there is a Google Form for this created.
- How to be a mentor? - Send your interest to our email (email link)
- FAQ

Since this is a large issue, I suggest we divide this in to multiple tasks. The two main sub tasks are as follows. 
1. Design the structure of the web page
2. Embed the wording and other material

If someone can create sub issues, it would be great! 

Let me know if there is something missing.

[ScholarX_Student_Guide.pdf](https://github.com/SustainableEducationFoundation/LiveWeb/files/2989579/ScholarX_Student_Guide.pdf)

[ScholarX_Mentor_Guide.pdf](https://github.com/SustainableEducationFoundation/LiveWeb/files/2989578/ScholarX_Mentor_Guide.pdf)

**Comment by jayasanka-sack** [comment]
Ack

**Comment by bpdesilva** [comment]
#110
