### ISSUE TITLE
Inconsistency in the scholarx archive cards

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#942]
**Describe the bug**
In the scholarx [archive page](https://sefglobal.org/scholarx/archive/) there are two cards at the bottom for 2019 and 2020. Those cards are different from the home page cards.

**To Reproduce**
1. Go to [archive page](https://sefglobal.org/scholarx/archive/)
2. Scroll down to the archive page
3. See the inconsistency

**Expected behavior**
Those cards should be like the cards which we have in the home page Our Projects section. 

**Screenshots**
Issue 
![Screenshot from 2021-05-08 19-15-52](https://user-images.githubusercontent.com/35697678/117541542-f974ce80-b031-11eb-9522-5f74af9d3a67.png)

The expected look of the card should be a curved one like below
![Screenshot from 2021-05-08 19-15-36](https://user-images.githubusercontent.com/35697678/117541558-0abddb00-b032-11eb-8d62-86415d91d853.png)

**Comment by kumuditha-udayanga** [comment]
@janethavi, Can i work on this issue.

**Comment by jayasanka-sack** [comment]
I gues we have a PR for this

**Comment by janethavi** [comment]
Fixed with #945
