### ISSUE TITLE
Add a "Show Less" button to Onelive page

### ISSUE THREAD

**Issue by Gimhan-minion** [sef-global/sef-site#947]
**Is your feature request related to a problem?**
- On the current OneLive page there is a section for speakers. In that section, there is a "Show more" button to load all the remaining speakers. Once the user clicks on this button user cannot contract back the speakers section.

**Describe the solution you'd like**
- To add a Show less button to contract this section once it's expanded.

**Additional context**
https://sef.discourse.group/t/adding-a-show-less-button-to-mentors-sections/265

**Comment by gajindubandara** [comment]
I would like to work on this
