### ISSUE TITLE
Add blog posts of ScholarX mentees in 2020

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#950]
**Is your feature request related to a problem? Please describe.**
The ScholarX mentees in 2020 have created blog posts during the time of mentoring. But these blog posts are not mentioned on the website.

**Describe the solution you'd like**
Currently in the [ScholarX-20 page](https://sefglobal.org/scholarx/archive/2020/), there is a table for mentees. When a mentee is clicked, his/her LinkedIn page will be redirected. With the new suggestion, when a mentee is clicked, a card should be poped. This card should contain the mentee details, the blog post links along with the Linkedin URL. A design of the card is shown below.
![blog-post (2)](https://user-images.githubusercontent.com/35697678/119948811-d9905500-bfb6-11eb-8b87-9d35a352cf6a.jpg)

The data(blog post URLs) can be found in [this document](https://docs.google.com/document/d/1n9ocPVu0XcbFFAKLMMHDKofSUSTkY5JGtS3GVdaUzZg/edit?usp=sharing).

**Additional context**
To ease the implementation, You can refer to the [ScholarX](https://sefglobal.org/scholarx/) page mentors cards. The logic and the implementation code snippets can be used from this page.

**Comment by miniskynet** [comment]
@janethavi are you working on this issue?

**Comment by janethavi** [comment]
Sorry @miniskynet This issue is not valid for the moment because the design is not finalized.

**Comment by miniskynet** [comment]
I see @janethavi thank you for letting me know :)
