### ISSUE TITLE
Fix Join us page button colour

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#951]
**Describe the bug**
On the join us page, the button colour changes to a different colour in the mobile view. 

**To Reproduce**
1. Go to [https://sefglobal.org/join-us.html](https://sefglobal.org/join-us.html)
2. Go to mobile view
3. Check the `Learn More` button

**Expected behavior**
The mobile view button colour should also be the desktop view button colour. Use the same CSS class for the mobile view button. 
 
**Screenshots**
![Screenshot from 2021-05-29 12-58-19](https://user-images.githubusercontent.com/35697678/120062040-9e0c8e00-c07d-11eb-8594-cf31f0432e80.png)

**Comment by gajindubandara** [comment]
I would like to work on this

**Comment by janethavi** [comment]
Go ahead @gajindubandara!
