### ISSUE TITLE
Fix Student Ambassadors page button colour

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#952]
**Describe the bug**
On the Student Ambassador's page, the button colour changes to a different colour in the mobile view.

**To Reproduce**
1. Steps to reproduce the behavior:
2. Go to [https://sefglobal.org/student-ambassador.html](https://sefglobal.org/student-ambassador.html)
3. Go to mobile view
4. Check the Learn More button

**Expected behavior**
The mobile view button colour should also be the desktop view button colour. Use the same CSS class for the mobile view button.

**Screenshots**
![Screenshot from 2021-05-29 13-02-17](https://user-images.githubusercontent.com/35697678/120062229-aaddb180-c07e-11eb-95ab-c516bc4bee4b.png)

**Comment by gajindubandara** [comment]
I would like to work on this

**Comment by janethavi** [comment]
Sure go ahead @gajindubandara!
