### ISSUE TITLE
Mentor linkedin hyperlinks in selected mentees 2021 are redirecting into a broken page

### ISSUE THREAD

**Issue by wathsala-vishwajith** [sef-global/sef-site#963]
**Describe the bug**
Some mentor linkedin account hyperlinks are broken and redirecting giving out 404.

**To Reproduce**
1. Go to [sefglobal](https://sefglobal.org/scholarx/2021/selected/)
2. Scroll down to Mentor Kasun Bandara
4. Click the hyperlink to see the error

**Expected behavior**
Links should be redirecting to linkedin correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/64484342/120752061-a6a21000-c526-11eb-9319-7f51686b0640.png)
![image](https://user-images.githubusercontent.com/64484342/120752088-b3beff00-c526-11eb-8a84-c923682637ca.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox,Chrome
 - Version Latest

**Comment by janethavi** [comment]
Fixed with #962
