### ISSUE TITLE
Implement a new webpage for UpSpeak 

### ISSUE THREAD

**Issue by Gimhan-minion** [sef-global/sef-site#965]
**Is your feature request related to a problem?**
- We need to create a new webpage for the Upspeak program

**Describe the solution you'd like**
- Create a new page using the following content.

**Description :** 
UpSpeak
Over the last few years of delivering SEF-initiated programs, we noticed one of the biggest challenges faced by undergraduate students was their ability to speak in English. While their reading and writing skills were very good, their level of spoken English was not on par. These were due to a number of reasons including,g inadequate resources to practice spoken English in a safe environment and focus on mastering academic English using rigid patterns not transferrable when speaking
In response to this, UpSpeak was introduced by SEF during June 2021. This is a free 12-week program aimed at creating a non-competitive safe environment for undergraduates in Sri Lanka whose second language is English and are looking to develop the following skills as published by Cambridge Papers in ELT:
- Develop their conversational competence,
- Become more proficient in the use of appropriate, rather than just accurate language,
- Learn to play with language and take risks with it,
- Building positive group dynamics for learning

**FAQ section**
- How do I apply for the program?
   - Our first cohort kicked off during June 2021. Keep an eye out on our social media sites for future cohort intakes.
- How do I become a facilitator?
   - Please email info@sefglobal.com with your CV and a cover letter with why you want to be a facilitator for the program
- How do we partner with SEF on the program?
   - Please email info@sefglobal.com with your Request For Proposal (RFP) regarding potential partnership opportunity.

**Logo**
![upspeak_logo_4_no_bg](https://user-images.githubusercontent.com/60275681/122012150-7ab24480-cdda-11eb-8608-74f642ba2bf2.png)

**Additional context**
- Create a thread in [SEF Hive](https://sef.discourse.group/) before start working on this issue. 
- Contact the dev team if you need more information.

**Comment by gajindubandara** [comment]
I would like to work on this

**Comment by Gimhan-minion** [comment]
Sure! Make sure you create a hive thread before start working on this.

**Comment by gajindubandara** [comment]
> Sure! Make sure you create a hive thread before start working on this.

Ok sure

**Comment by jayasanka-sack** [comment]
Let's move this into a hive thread and finalize a wireframe or a mockup. From now on, let's avoid creating issues for this kind of implementations that needs a design phase. (Requirement -> Design -> Implementation)

Closing the issue for now. Feel free to reopen when the task is ready. 

cc: @janethavi @YohanAvishke @Gravewalker666 @Piumal1999 @anjula-sack
