### ISSUE TITLE
Fix broken link in medium post 

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#969]
**Describe the bug**
In the ScholarX-2021 and ScholarX-2020 featured stories section, the first blog post(ScholarX Class of 2019 | SX19) has a broken link. Also, the read time is wrong.

**To Reproduce**
1. Go to [ScholarX-21](https://sefglobal.org/scholarx/2021/) and [ScholarX-20](https://sefglobal.org/scholarx/archive/2020/)
2. Scroll down to `Featured Stories` section
3. Click on the 1st blog post(ScholarX Class of 2019 | SX19)

**Expected behavior**
The correct blog post should be redirected. The link should be changed to as [https://sefglobal.medium.com/scholarx-class-of-2019-f69ac1c28077](https://sefglobal.medium.com/scholarx-class-of-2019-f69ac1c28077). Also, fix the reading time to 5mins

**Comment by deeola** [comment]
Hell janethavi, I would love to work on this

**Comment by janethavi** [comment]
Sure go ahead! @deeola

**Comment by deeola** [comment]
Thanks for assigning me. I am through with it but i'm having issues pushing it due to 403 error, is this something i need to fix from my end?

**Comment by janethavi** [comment]
Looks like you have not forked the repository. You need to fork this repository and then clone the forked repository to do the fix. Check this [link ](https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/)to get an idea about forking and creating a pull request

**Comment by deeola** [comment]
Yes, thank you. I created a pull request already.
