### ISSUE TITLE
Page to apply online - Volunteer Recruitment

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-site#97]
- [x] Create a page to SEF Volunteer Recruitment
path /apply

- [x] Embed following google form.
https://docs.google.com/forms/d/e/1FAIpQLSe1jflsOsYGmiGeWV9egnvH-yJPGz6PB2sNubZmOivq5xkAew/viewform

Embed code:
```
<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSe1jflsOsYGmiGeWV9egnvH-yJPGz6PB2sNubZmOivq5xkAew/viewform?embedded=true" width="640" height="2584" frameborder="0" marginheight="0" marginwidth="0">
Loading...
</iframe>
```

**Comment by 99sumedha** [comment]
I will do this

**Comment by Piumal1999** [comment]
i'll do it

**Comment by Gravewalker666** [comment]
I'll do it

**Comment by jayasanka-sack** [comment]
#100 merged

Congrats! @Piumal1999  💯
