### ISSUE TITLE
Differentiate a section in ScholarX-21(use the default white background)

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#970]
**Describe the bug**
In the [ScholarX-21](https://sefglobal.org/scholarx/2021/) page, the `Take a look at our past ScholarX` has the same background as the previous section. Therefore that section is not getting highlighted and it wont see as a separate section.

**To Reproduce**
1. Go to [ScholarX-21](https://sefglobal.org/scholarx/2021/) page.
2. Scroll down to `Take a look at our past ScholarX`.
3. See that section can't be differentiated from the previous section.

**Expected behavior**
`Take a look at our past ScholarX` section should be differentiated from the previous section. Therefore use the white background only to that section. Then it will be differentiated from the `FAQ section`

**Comment by deeola** [comment]
Hello, can i work on this issue?

**Comment by janethavi** [comment]
Sure go ahead! @deeola

**Comment by akeel230** [comment]
@janethavi requested changes are made , please take a look
