### ISSUE TITLE
Link SEF youtube channel to the footer

### ISSUE THREAD

**Issue by Gimhan-minion** [sef-global/sef-site#972]
**Is your feature request related to a problem?**
- Current SEF youtube channel is not mentioned on the website. 

**Describe the solution you'd like**
- Create a youtube icon alongside with rest of the social media icons in the footer.
- Youtube Channel - https://www.youtube.com/channel/UClw7QbeW_FOJz_fDMvjXsJw

**Comment by gajindubandara** [comment]
I would like to work on this
