### ISSUE TITLE
Profiles section of Scholarx, IRC and Team pages does not scroll up when "SEE LESS" button is clicked

### ISSUE THREAD

**Issue by miniskynet** [sef-global/sef-site#976]
**Describe the bug**
A "SEE LESS" button was implemented recently to the profiles sections of Scholarx,IRC and Team pages. However once the "SEE LESS" button is clicked, the page does not scroll up to the former profile section view, instead it remains at the lower end of the page in the "Frequently Asked Questions" section(or lower), which removes the profiles section from view.

**To Reproduce**
1. Go to [OneLive page](https://sefglobal.org/onelive/)
2. Scroll down to the profiles section
3. Click on the "SEE MORE" button
4. Scroll further down until you see the "SEE LESS" button, and click on it
5. Observe that the profiles section is out of view and the page is at "Frequently Asked Questions" section or lower.

**Expected behavior**
Once the "SHOW LESS" button is clicked, the view should scroll up to it's original profile section view

**Screenshots**
Once the "SEE MORE" button is clicked(Original view)
![image](https://user-images.githubusercontent.com/49517852/123233983-2bfe5c00-d4f8-11eb-81f0-cec299995a84.png)
Once the "SEE LESS" button is clicked
![image](https://user-images.githubusercontent.com/49517852/123234173-56501980-d4f8-11eb-8dfb-c93398e2e4f4.png)

**Desktop:**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [91.0.4472.114 (Official Build) (64-bit)]

**Additional context**
An event listener to the "SEE LESS" button, which would reference back to the h1 tag would suffice to solve this issue.

**Comment by miniskynet** [comment]
Hey @Gravewalker666 can you please assign this issue to me? 
I can't seem to find a way. Thank you :)

**Comment by Gravewalker666** [comment]
Yeah sure @miniskynet 🙂

**Comment by miniskynet** [comment]
@Gravewalker666 thanks again. Is there any way to contact you if I run into issues?

**Comment by Gravewalker666** [comment]
Yup @miniskynet you can ping for me here in this issue itself or in our slack group

**Comment by miniskynet** [comment]
@Gravewalker666 I tried to solve this issue by adding an onclick event to the "SEE LESS" button, which would scroll to the "Speakers" topic. However that does not seem to work. Is it because there are dynamic elements in the webpage? 
Thanks in advance.

**Comment by akshika47** [comment]
@anjula-sack do you happen to know how to fix this?

**Comment by anjula-sack** [comment]
Can't we use  `<a>` like this, `<a href="#idOfTheDiv">SEE MORE</a>` @miniskynet

**Comment by miniskynet** [comment]
@anjula-sack hey thank you for the response. Are you recommending to convert the "SEE LESS" button into a hyperlink from `<button id="btnShowLess" class="btn btn-link btn-outline-white btn-info">SEE LESS</button>` to `<a href="#idOfTheDiv" id="btnShowLess" class="btn btn-link btn-outline-white btn-info">SEE LESS</a>` ?

**Comment by miniskynet** [comment]
I tried it @anjula-sack 
It seems to work! Thank you :)

**Comment by anjula-sack** [comment]
yeah and the Id needs to be the id of the wrapper div of the profile so it will scroll to that div. @miniskynet

**Comment by miniskynet** [comment]
what would happen if the Id is assigned to the `h1` tag instead?
