### ISSUE TITLE
Remove not used HTML file

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#977]
**Describe the bug**
template.html file is not used on the site. 

**To Reproduce**
1. Go to [https://github.com/sef-global/sef-site](https://github.com/sef-global/sef-site)
2. See the `template.html` file 

**Expected behavior**
template.html file should be deleted from the repository

**Comment by gajindubandara** [comment]
I would like to work on this

**Comment by janethavi** [comment]
Sure go on @gajindubandara!
