### ISSUE TITLE
Remove gitter chat badge

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#978]
**Describe the bug**
Gitter is no longer used. 

**To Reproduce**
1. Go to [https://github.com/sef-global/sef-site](https://github.com/sef-global/sef-site)
2. See the `Gitter Join chat badge` on the README.md file

**Expected behavior**
Remove the Gitter badge from the `README.md` file

**Comment by gajindubandara** [comment]
I would like to work on this

**Comment by janethavi** [comment]
Sure go on @gajindubandara
