### ISSUE TITLE
Fix formating in the project menu Upspeak option

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-site#991]
**Describe the bug**
In the project list on the navigation bar, there is a project called `Upspeak`. The formatting should be similar to the logo. This small error can be found on the [UpSpeak](https://sefglobal.org/upspeak/) page title too.

**To Reproduce**
1. Go to [https://sefglobal.org/](https://sefglobal.org/)
2. Click on the Projects menu from the navigation bar.
3. See the option `Upspeak`

**Expected behavior**
`Upspeak` should be corrected to `UpSpeak`. The reason is, in the UpSpeak logo, we have followed this format. The correction should be done in the menu as well as in the page title.

**Comment by miniskynet** [comment]
Hello @janethavi can I work on this?

**Comment by janethavi** [comment]
Sure go ahead @miniskynet!

**Comment by miniskynet** [comment]
@janethavi hello can you please tell me where the page title is (I can only see the UpSpeak logo on the [page](https://sefglobal.org/upspeak/)).
Also it would be helpful if you can tell me the location for the navigation bar script. Thank you :)

**Comment by janethavi** [comment]
Hi @miniskynet
The navigation bar script can be found [here](https://github.com/sef-global/sef-site/blob/master/assets/content/static/navbar.html). The title of the Upspeak page can be found [here](https://github.com/sef-global/sef-site/blob/master/upspeak/index.html#L19).

**Comment by miniskynet** [comment]
@janethavi Thank you. I put a PR. Would be glad if you can check it out.
