### ISSUE TITLE
Replace Onelive page images with Cloudinary URLs

### ISSUE THREAD

**Issue by gajindubandara** [sef-global/sef-site#994]
**Is your feature request related to a problem? Please describe.**
Use Cloudinary image hosting  service to import images to the Onelive page 

**Describe the solution you'd like**
1. Use the below image URLs to update the image column in the google sheet

```
v1625328841/Onelive_Speakers/harshi_vwwo8q.jpg
v1625328837/Onelive_Speakers/keet_uvbizv.jpg
v1625328832/Onelive_Speakers/anish_eyrgnu.jpg
v1625328825/Onelive_Speakers/shadir_aa1rbm.jpg
v1625328814/Onelive_Speakers/chethiya_lruyjp.jpg
v1625328807/Onelive_Speakers/cd_yf3ucf.jpg
v1625328802/Onelive_Speakers/alagan_sekyjs.jpg
v1625328796/Onelive_Speakers/bernadine_a4rdmc.jpg
v1625328787/Onelive_Speakers/nipuna_mzqgfk.jpg
v1625328780/Onelive_Speakers/samin_ocu9ds.jpg
v1625328774/Onelive_Speakers/biman_psufap.jpg
v1625328768/Onelive_Speakers/isuru_bacx6z.jpg
v1625328758/Onelive_Speakers/kavindya_d5iabe.jpg
v1625328747/Onelive_Speakers/yasith_qmd8cx.jpg
v1625328724/Onelive_Speakers/yasantha_xqjyce.jpg
v1625328723/Onelive_Speakers/hasini_zw9vlu.jpg
```

google sheet link- https://docs.google.com/spreadsheets/d/1XQI7aOokHIzbpoA5cyC5xum7EJA3tv599QUNds-d6HQ/edit?usp=sharing

2. Replace `/assets/img/profiles/{{image}}` with `https://res.cloudinary.com/dsxobn1ln/image/upload/{{image}}` in the Onelive/index.html

**Comment by Gravewalker666** [comment]
@gajindubandara can't we just use `https://res.cloudinary.com/dsxobn1ln/image/upload/v1625328841/Onelive_Speakers/{{image}}` and keep only the image names (ex: `harshi_vww08q.jpg`) on the google sheet column??

**Comment by gajindubandara** [comment]
> @gajindubandara can't we just use `https://res.cloudinary.com/dsxobn1ln/image/upload/v1625328841/Onelive_Speakers/{{image}}` and keep only the image names (ex: `harshi_vww08q.jpg`) on the google sheet column??

The problem is  the number after the `https://res.cloudinary.com/dsxobn1ln/image/upload/` is not the same in every URL

**Comment by Gravewalker666** [comment]
> > @gajindubandara can't we just use `https://res.cloudinary.com/dsxobn1ln/image/upload/v1625328841/Onelive_Speakers/{{image}}` and keep only the image names (ex: `harshi_vww08q.jpg`) on the google sheet column??
> 
> The problem is the number after the `https://res.cloudinary.com/dsxobn1ln/image/upload/` is not the same in every URL

Ahh sorry, I didn't notice it
