### ISSUE TITLE
Use a google sheet to the ScholarX mentors's section instead of JSON file

### ISSUE THREAD

**Issue by gajindubandara** [sef-global/sef-site#995]
**Is your feature request related to a problem? Please describe.**
Currently, the ScholarX page is using a JSON file (scholarx/2021/mentors.json) to import data to the mentor's section. It's more efficient to use a google sheet to update the data than using a JSON file.

**Describe the solution you'd like**
1. Instead of using the JSON file, create a new google sheet and add the data into the sheet
2. Create a google script and deploy it 
3. Use the URL to import data from the sheet to the web page

**Comment by cmdrGuyson** [comment]
Can I please be assigned to this? @gajindubandara
